### ISSUE TITLE
The treatment-naive microbiome in new-onset Crohn's disease

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDBcuration#10]
Condition: Crohn's disease
URL: https://pubmed.ncbi.nlm.nih.gov/24629344/

**Comment by Khadeeejah** [comment]
Hi ill love to work on this

**Comment by Khadeeejah** [comment]
hi @ftzohra22 here is the link to my study for review
https://bugsigdb.org/Study_735

**Comment by cmirzayi** [comment]
Hi @Khadeeejah I noticed you have not submitted a completed mini-curation as described as the first step under Contribution Tasks in: https://github.com/waldronlab/BugSigDBcuration/issues/1. Can you please submit this survey? We cannot review your work until you do.

**Comment by cmirzayi** [comment]
Hi @Khadeeejah. Unfortunately it looks like you conflated 3 experiments into one here. They did three different samples: stool, rectum, and terminal ileum. You acknowledged that in your Body site curation but those each need to be separate experiments with separate results. For instance, Enterobacteriaceae was increased in rectum and terminal ileum samples but not stool samples--an important thing to distinguish. Additionally they did not use LEfSe and they controlled for many confounders. Please consider revising.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 0 (case-control as described in paper)
3. Entered all relevant experiments and no irrelevant experiments (1 point): Not scored due to incomplete curation
4. Body site correctly identified (i.e. does not include multiple sites) (1 point):
5. Condition entered according to contrast (correct EFO ontology) (1 point):
6. Contrast groups correctly identified (1 point):
7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point):
8. Antibiotic exclusion correctly identified (1 point):
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points):
10. Identified correct statistical test (1 point):
11. Identified MHT correction (1 point):
12. Correctly recorded matched on factors (1 point):
13. Entered correct number of statistical tests per experiment (1 point):
14. All diversity measures identified (1 point):
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point):
16. All signature sources correctly identified  (-1 for each error)  (2 points):
17. Abundance direction correctly selected (1 point):
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points):
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points):

Total (maximum 24 points): Not scored due to incomplete curation

**Comment by Khadeeejah** [comment]
@cmirzayi  thank you for your review, i would revise

**Comment by claregri** [comment]
Hi there, solid effort on this! Please see my comments below and be sure to read the statistical methods carefully (you can find more info in the supplementary data files at the end of the paper).
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0 (there is a text section discussing whole metagenomic sequencing with results listed that you can curate in another experiment)
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 0 (not sure where you got this from, there is no antibiotics exclusion)
9. Correctly identified sequencing details (2 points): 1 (sequencing platform should be Illumina)
10. Identified correct statistical test (1 point): 0
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 0 (go to statistical analysis section and input confounders, there are no matched factors in this study)
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 0 (though this study mentions these diversity measures, I couldn't find anywhere that provided statistical significance info, so they should be left blank)
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 0
16. All signature sources correctly identified  (-1 for each error)  (2 points): 0 (the source for all of your signatures is Figure 5b, but I think it should be Figure 1b) 
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (2 points): 0 (there are multiple taxa missing from your curations from what I can see in the table)
19. Correct use of NCBI taxonomy (2 points): 2

Score: 12/23

**Comment by Khadeeejah** [comment]
> Hi there, solid effort on this! Please see my comments below and be sure to read the statistical methods carefully (you can find more info in the supplementary data files at the end of the paper).
> 
> 1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
> 
> 2. Correct study design (1 point): 1
> 
> 3. Entered all relevant experiments and no irrelevant experiments (1 point): 0 (there is a text section discussing whole metagenomic sequencing with results listed that you can curate in another experiment)
> 
> 4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
> 
> 5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
> 
> 6. Contrast groups correctly identified (1 point): 1
> 
> 7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
> 
> 8. Antibiotic exclusion correctly identified (1 point): 0 (not sure where you got this from, there is no antibiotics exclusion)
> 
> 9. Correctly identified sequencing details (2 points): 1 (sequencing platform should be Illumina)
> 
> 10. Identified correct statistical test (1 point): 0
> 
> 11. Identified MHT correction (1 point): 1
> 
> 12. Correctly recorded matched on factors (1 point): 0 (go to statistical analysis section and input confounders, there are no matched factors in this study)
> 
> 13. Entered correct number of statistical tests per experiment (1 point): 1
> 
> 14. All diversity measures identified (1 point): 0 (though this study mentions these diversity measures, I couldn't find anywhere that provided statistical significance info, so they should be left blank)
> 
> 15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 0
> 
> 16. All signature sources correctly identified  (-1 for each error)  (2 points): 0 (the source for all of your signatures is Figure 5b, but I think it should be Figure 1b) 
> 
> 17. Abundance direction correctly selected (1 point): 1
> 
> 18. Members of Signatures identified correctly (2 points): 0 (there are multiple taxa missing from your curations from what I can see in the table)
> 
> 19. Correct use of NCBI taxonomy (2 points): 2
> 
> 
> 
> Score: 12/23

Thank you for your review.. I'll update it with all your corrections.

**Comment by atrayees** [comment]
I went through this curation and made some changes, but I do not find any statistical test for the experiments

**Comment by cmirzayi** [comment]
@atrayees 

There should be 3 experiments.  I would not curate Figure 1B or Figure 3. Figure 1B only has a partial subset of the full results. Figure 3 is not relevant.

Look at Table S2A in the supplements. Look for the Diagnosis variables and curate those with a q < 0.05. This is the combined ileal and rectal samples so it's two sites.

Then curate S2B separately as its own experiment as this is stool samples only.

Then curate S2C separately as this is a contrast of mucosal (rectal + ileal samples) vs. stool samples for people with newly diagnosed Crohn's Disease.

Also this is currently curated as LEfSe when it should be MaAsLin. Carefully review the methods to ensure everything matches and please ask questions on the Slack channel as this is a complex paper.

**Comment by atrayees** [comment]
I curated all the experiments, corrected the control and case groups, the confounding variables, and used 0.05 as the threshold (since nothing was mentioned).

**Comment by lwaldron** [comment]
If no threshold is mentioned, it's better to leave this blank (it's not required as far as I recall)

**Comment by atrayees** [comment]
Okay, thanks! I corrected all the experiments.
