### ISSUE TITLE
Characterisation of the koala (Phascolarctos cinereus) pouch microbiota in a captive population reveals a dysbiotic compositional profile associated with neonatal mortality

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#109]
Characterisation of the koala (Phascolarctos cinereus) pouch microbiota in a captive population reveals a dysbiotic compositional profile associated with neonatal mortality – Toby I. Maidment et al. – Microbiome 2023

https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-023-01527-9

**Comment by OdogwuRok** [comment]
I'm Sabastine Iroka, please assign this paper to me so I can curate it. Thanks

**Comment by Lonercode** [comment]
Hi @SvetlanaUP. I would like to be assigned to this work please.

Amanda Adoyi

Thank you :)

**Comment by Lonercode** [comment]
https://bugsigdb.org/Study_897
@AleruDivine

Thanks a lot for the review

**Comment by Lonercode** [comment]
@flourishralph

I seriously appreciate your review

**Comment by Lonercode** [comment]
@Scholarpat

Thank you for the review :)

**Comment by Lonercode** [comment]
Aloha @SvetlanaUP I am finished with the curation of this paper and thank you so much for the opportunity to do so. Here is the link to the curation: 
https://bugsigdb.org/Study_897

**Comment by Folakunmi21** [comment]
Hello @Lonercode Here are some corrections to your curation.

- You did not get the full mark for statistical test because the data transformation you entered was wrong. 
- There were no confounders in the study, controlling for contamination is a standard microbiological laboratory procedure. Confounders are factors that can influence the relationship between your variables, and subsequently the results of your experiment. 
- Supplementary table 11 is the only one showing differential abundance data.

CURATION RESULT 
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 0
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 0.5
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 0
16. All signature sources correctly identified  (-1 for each error)  (2 points): 1
17. Abundance direction correctly selected (1 point): 0
18. Members of Signatures identified correctly (2 points): 0
19. Correct use of NCBI taxonomy (2 points): 2

Total (maximum 23 points): 16.5

@SvetlanaUP study 897 reviewed

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_897 reviewed.
