### ISSUE TITLE
The aging mouse microbiome has obesogenic characteristics

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#114]
The aging mouse microbiome has obesogenic characteristics – Dana Binyamin et al. – Genome Medicine 2020

https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-020-00784-9

**Comment by 0x-Ryker** [comment]
Hi, I wish to curate this paper.

**Comment by SvetlanaUP** [comment]
Assigned.

**Comment by 0x-Ryker** [comment]
I'm done curating this project. Here's the link below:
https://bugsigdb.org/Study_813

**Comment by cmirzayi** [comment]
This is a good curation and just needs some small revisions to be perfect. Most importantly, Figures 5A and 5B should be curated as separate experiments. One is an experiment with increasing weight. Another is increasing body fat%. Also Figure 3 should be curated as though it's not about the condition of interest, it is available and should be easy to curate.

Group 1 and Group 0 names should be spelled out and defined clearly so that people analyzing the data know what they mean.

I don't see where the antibiotic exclusion came from.

No matching in lab experiments generally.

I don't see where Shannon, Chao1, and Simpson came from. Methods say they only used Faith's.

Figure 3 which compares aged vs. adult mice could be curated.

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 0 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 0 |
| 8 | Antibiotic exclusion correctly identified | 1 | 0 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 0 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 0 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 0 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 1 |
| 17 | Abundance direction correctly selected | 1 | 0 |
| 18 | Members of Signatures identified correctly | 2 | 1 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 13 |
