### ISSUE TITLE
Dental Biofilm Microbiota Dysbiosis Is Associated With the Risk of Acute Graft-Versus-Host Disease After Allogeneic Hematopoietic Stem Cell Transplantation

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#115]
Dental Biofilm Microbiota Dysbiosis Is Associated With the Risk of Acute Graft-Versus-Host Disease After Allogeneic Hematopoietic Stem Cell Transplantation – Vitor Heidrich et al. – Frontiers in Immunology 2021

https://www.frontiersin.org/articles/10.3389/fimmu.2021.692225/full

**Comment by Gboladee** [comment]
May I please have this paper assigned to me

**Comment by SvetlanaUP** [comment]
Assigned.

**Comment by leenaaize** [comment]
hello @SvetlanaUP @cmirzayi , I would like to curate this please

**Comment by Analyst-Joan** [comment]
Joan C. Chukwuemeka

Please can I be assigned this article for curation. Thanks

**Comment by Analyst-Joan** [comment]
Good day @cmirzayi @SvetlanaUP @lwaldron 

I have completed the curation for this [article](https://www.frontiersin.org/journals/immunology/articles/10.3389/fimmu.2021.692225/full).

You can find the BugSigDB link at [Study_904](https://bugsigdb.org/Study_904) for your review. 

Looking forward to make changes or improvements that will be required, If any.

Thank you.
Joan C. Chukwuemeka [Joan Chuks]

**Comment by Omabekee** [comment]
A near-perfect curation! @Analyst-Joan  Fantastic!⭐
Some points to take note:
1. It's good for source descriptions (for signatures) to be descriptive enough so that anyone who comes across the study in the future can immediately tell what's going on without going too deep into the whole curation.
2. It's okay to curate experiments with alpha diversity and no differential abundance results, in such cases, the experiment (s) will not have signatures.

**CURATION RESULTS**
1. All elements marked "Needs review" (none "Incomplete") (1 point): **1**
2. Correct study design (1 point): **1**
3. Entered all relevant experiments and no irrelevant experiments (1 point): **0.5**
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): **1**
5. Condition entered according to contrast (correct EFO ontology) (1 point): **1**
6. Contrast groups correctly identified (1 point): **1**
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): **1**
8. Antibiotic exclusion correctly identified (1 point): **1**
9. Correctly identified sequencing details (2 points): **2**
10. Identified correct statistical test (1 point): **1**
11. Identified MHT correction (1 point): **1**
12. Correctly recorded matched on factors (1 point): **1**
13. Entered correct number of statistical tests per experiment (1 point): **1**
14. All diversity measures identified (1 point): **1**
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): **1**
16. All signature sources correctly identified  (-1 for each error)  (2 points): **2**
17. Abundance direction correctly selected (1 point): **1**
18. Members of Signatures identified correctly (2 points): **2**
19. Correct use of NCBI taxonomy (2 points): **2**

**Total: 22.5**

@SvetlanaUP , review of Study 904 complete. ✅

**Comment by Analyst-Joan** [comment]
Good morning @Omabekee 
Thanks a lot for the feedback. 
I've gone through the curation on BugSigDB [Study_904](https://bugsigdb.org/Study_904) and noted down the improvements you made. 
I'd be sure to implement this in my future curation.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_904 reviewed,.
