### ISSUE TITLE
Predominance of Escherichia-Shigella in Gut Microbiome and Its Potential Correlation with Elevated Level of Plasma Tumor Necrosis Factor Alpha in Patients with Tuberculous Meningitis

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDBcuration#12]
Condition: Meningitis
URL: https://journals.asm.org/doi/10.1128/spectrum.01926-22

**Comment by Busayo-ojo** [comment]
Hi, I would like to work on this article. 
Busayo Ojo

**Comment by ftzohra22** [comment]
Assigned

**Comment by chondatondaponda** [comment]
Hi, I saw that the assigned label was removed for this, can I work on this article? 
Chiharu Hannah Honda

**Comment by lwaldron** [comment]
@ftzohra22 what is the correct status of this article?

**Comment by Busayo-ojo** [comment]
Hi @lwaldron It's unassigned, I had requested to be assigned the article after completing my first assigned article.
@ftzohra22 didn't know initially that it was my second request, she later informed me that I would be unasigned so others that have not gotten any can work on it.

**Comment by ftzohra22** [comment]
@chondatondaponda yes you can work on this article. Assigned to you.

**Comment by chondatondaponda** [comment]
@Busayo-ojo thank you for the clarification, and @ftzohra22 @lwaldron thank you for the assignment!

**Comment by claregri** [comment]
Hi Chiharu, you had a good start here! Figure 3 doesn't have any p-values, which is a clue that it's not curatable by our standards - it's characterizing the microbiomes of the different groups, but not statistically comparing them in a way we can curate. The significantly different taxa are found in the Supplementary tables at the end of the paper, as you noted in your comment above. Also, there should never be more than 2 signatures per experiment (increased in the case group, decreased in the case group) - if there is more than one source in the paper that contains differential abundance info for an experiment's comparison groups, you should combine and list all of the sources in the "Source" field for the signature. 

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 0 (observational, not case-control would be more appropriate here)
3. Entered all relevant experiments and no irrelevant experiments (1 point): 
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2
10. Identified correct statistical test (1 point): 0 (this should have just been Welch's t-test - papers often reference many statistical tests, but the one that your experiment in particular is using is often found in the caption of the figure/table that you're curating)
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 0
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): not scored due to incorrect curation
17. Abundance direction correctly selected (1 point): not scored
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): not scored
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): not scored

Total (maximum 24 points): not scored

**Comment by cmirzayi** [comment]
Hi @chondatondaponda Thank you so much for your contributions to the BugSigDB project. I wanted to check to see if you wanted to finish this curation. I understand that with the Outreachy applicant selection process over, you may no longer wish to help out with BugSigDB or have other priorities right now.

If not, I will open it up to other curators to finish the curation.

**Comment by atrayees** [comment]
Paper reviewed; some signatures were missing, and I added them! The rest of it is fine.
