### ISSUE TITLE
Exploring the relationship between the gut microbiome and mental health outcomes in a posttraumatic stress disorder cohort relative to trauma-exposed controls

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#124]
Exploring the relationship between the gut microbiome and mental health outcomes in a posttraumatic stress disorder cohort relative to trauma-exposed controls – Stefanie Malan-Muller et al. – European Neuropsychopharmacology 2022

https://www.sciencedirect.com/science/article/abs/pii/S0924977X21016539

NOTE: This paper is without open access, here is downloaded pdf: [Exploring-the-relationship-between-the-gut-microbiome-and-m_2022_European-Ne 2.pdf](https://github.com/waldronlab/BugSigDBcuration/files/12871014/Exploring-the-relationship-between-the-gut-microbiome-and-m_2022_European-Ne.2.pdf)

**Comment by CLAREISMO** [comment]
Hi SvetlanaUP.  I Would love to curate the paper. Thanks!

**Comment by CLAREISMO** [comment]
Hello SvetlanaUP. I would love to curate the article. Thank you!

**Comment by Win13nie** [comment]
Winnie Wahome

**Comment by Win13nie** [comment]
Assign Winnie Wahome

**Comment by SvetlanaUP** [comment]
@CLAREISMO assigned!

**Comment by CLAREISMO** [comment]
> @CLAREISMO assigned!

Thank you!

**Comment by SvetlanaUP** [comment]
@CLAREISMO please let us know if you still want to curate this even though it's no longer during the Outreachy contribution period.

**Comment by keamybams** [comment]
Hello Svetlana, I would love to be assigned to this. 

Ruth Bamgbose. 

Thank you.

**Comment by zheeburg** [comment]
Isaac Adedoja

Hi @SvetlanaUP, I will love to work on this. Please assign to me

**Comment by Lonercode** [comment]
Aloha @SvetlanaUP. I Would love to curate this :)

**Comment by keamybams** [comment]
Hello @SvetlanaUP this paper is ready to be reviewed https://bugsigdb.org/Study_881 Thank you.

**Comment by keamybams** [comment]
Hi, @Buraah thank you.

**Comment by keamybams** [comment]
@samreen_19

**Comment by keamybams** [comment]
@leenaaize thank you.

**Comment by Omabekee** [comment]
Overall this was a good second curation! @keamybams, I especially appreciate how you curated your group descriptions. However, here are some errors you made and important points to take note which will help your future curations:

1. Matched-on should only be entered if stated in the paper. You can do that easily by Ctrl + F "matched on". In cases where you're not sure, please don't assume, please ask questions.
2. It's good for source descriptions (for signatures) to be descriptive enough so that anyone who comes across the study in the future can immediately tell what's going on without reading the whole paper.
3. We don't curate Random forest or correlation results on bugsigdb. Therefore figure 3 should not be curated.
4. You did not curate the study condition for experiment 2. "response to treatment" should've been the closest, but I wonder why it's no longer available on the ontology site.
5. For experiment 2, you did not curate the right statistical test for centered log ratio (CLR) which should be linear regression, since they fitted generalized linear models (GLMs) on clr-transformed data.
6. Sample sizes for Experiments 2 and 3 weren't correct. Please see Table 1 for sample sizes for MDD expt. and psychotropic medication use experiment.
 
**CURATION RESULTS**
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0.5
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
7. Condition entered according to contrast (correct EFO ontology) (1 point): 0.5
8. Contrast groups correctly identified (1 point): 1
9. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
10. Antibiotic exclusion correctly identified (1 point): 1
11. Correctly identified sequencing details (2 points): 2
12. Identified correct statistical test (1 point): 0.5
13. Identified MHT correction (1 point): 1
14. Correctly recorded matched on factors (1 point): 0
15. Entered correct number of statistical tests per experiment (1 point): 0
16. All diversity measures identified (1 point): 1
17. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
18. All signature sources correctly identified (-1 for each error) (2 points): 1
19. Abundance direction correctly selected (1 point): 1
20. Members of Signatures identified correctly (2 points): 1
21. Correct use of NCBI taxonomy (2 points): 2
Total = **17.5** 

@SvetlanaUP, review of Study 881 complete. ✅

**Comment by keamybams** [comment]
Thank you @Omabekee . Your feedback has been noted.✨

**Comment by Omabekee** [comment]
You're welcome!
update* I went for "**Clinical treatment**" instead which means _Where a drug (in this case, psychotropic drug) or surgery has been used to treat an individual with a particular condition_ according to the [ontology site](https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0007056)

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_881 reviewed.
