### ISSUE TITLE
Changes in salivary microbiota due to gastric cancer resection and its relation to gastric fluid microbiota

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#126]
Changes in salivary microbiota due to gastric cancer resection and its relation to gastric fluid microbiota – Eri Komori – Scientific Reports 2023 

https://www.nature.com/articles/s41598-023-43108-8

**Comment by RotimiDesire** [comment]
Desire Oluwarotimi. 

I want to claim this article for curation. @SvetlanaUP @cmirzayi

**Comment by AleruDivine** [comment]
Aleru Divine

I want to claim this article for curation as my third contribution. @cmirzayi @lwaldron @SvetlanaUP

**Comment by SvetlanaUP** [comment]
Assigned.

**Comment by AleruDivine** [comment]
@SvetlanaUP Thank you so much!

**Comment by AleruDivine** [comment]
Hi! @cmirzayi @SvetlanaUP 
I have completed my curation and here's the link: https://bugsigdb.org/Study_824
I am looking forward to your review.
Thank you so much!

**Comment by AleruDivine** [comment]
Thank you so much! @SvetlanaUP

**Comment by cmirzayi** [comment]
Some small feedback. Otherwise this was an excellent curation! I made these changes myself so no need for revisions.

Prospective cohort study, not cross-sectional.

Antibiotics exclusion was 3 months according to the methods.

LEfSe generally doesn't control for factors. Smoking was not controlled for (I penalized 1 point under matched on factors).


| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 0 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 0 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 0 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 2 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 2 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 20 |

**Comment by AleruDivine** [comment]
Thank you so much for the review and for making the changes @cmirzayi
