### ISSUE TITLE
Characterization of microbial communities in the chicken oviduct and the origin of chicken embryo gut microbiota

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#155]
Characterization of microbial communities in the chicken oviduct and the origin of chicken embryo gut microbiota -- Lee S. et al. -- Sci. Rep.

https://www.nature.com/articles/s41598-019-43280-w

**Comment by Viperstacky** [comment]
Hi @SvetlanaUP . I would love to work on this paper. Please assign to me

**Comment by kwennB** [comment]
Hi @SvetlanaUP I would love to work on this issue. Thank you

**Comment by kwennB** [comment]
Thank you! @Omabekee

**Comment by kwennB** [comment]
@AleruDivine here is mine

**Comment by kwennB** [comment]
@RotimiDesire this is mine

**Comment by kwennB** [comment]
@imalovee thank you for the help. here is mine as well

**Comment by imalovee** [comment]
You are welcome, and I'm glad I could help

**Comment by kwennB** [comment]
Hello @SvetlanaUP cc: @Omabekee 
I am submitting my curation for your assessment and review. 

https://bugsigdb.org/Study_906

Thank you so much.

**Comment by Folakunmi21** [comment]
Hello @kwennB here are the corrections to your curation:
- The only differential analysis carried out was between immature egg magnum and mature egg magnum. Result is within text under "Microbiota of the chicken reproductive tract" paragraph 5. Signatures should be curated from here.  
- There was no matching in the paper
- oviduct is sufficient as body site
Please, edit one of the experiments so that I can delete the other

CURATION RESULT
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 0
6. Contrast groups correctly identified (1 point): 0.5
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 0
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 0
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 0
16. All signature sources correctly identified  (-1 for each error)  (2 points): 1
17. Abundance direction correctly selected (1 point): 0
18. Members of Signatures identified correctly (2 points): 0
19. Correct use of NCBI taxonomy (2 points): 2

Total (maximum 23 points): 13.5

@SvetlanaUP study 906 graded

**Comment by Rahila-me** [comment]
@Folakunmi21 I am effecting the correction for this paper, please delete Experiment 2, I am working on Experiment 1. Thank you

**Comment by SvetlanaUP** [comment]
Deleted.

**Comment by Rahila-me** [comment]
@SvetlanaUP Ok Noted About the deletion

**Comment by Rahila-me** [comment]
@Folakunmi21 You can checkout this: https://bugsigdb.org/Study_906 I have effected the corrections.
@SvetlanaUP if there's any up for correction after review i am in. Just tag me it will be easier for me to identify once i check my email. You too @Folakunmi21 
Thank you for the work you do. Well-done

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_906 reviewed.
