### ISSUE TITLE
Association between inflammation, lipopolysaccharide binding protein, and gut microbiota composition in a New Hampshire Bhutanese refugee population with a high burden of type 2 diabetes

### ISSUE THREAD

**Issue by Folakunmi21** [waldronlab/BugSigDBcuration#168]
Association between inflammation, lipopolysaccharide binding protein, and gut microbiota composition in a New Hampshire Bhutanese refugee population with a high burden of type 2 diabetes – Brandy Moser et al – Frontiers 

https://www.frontiersin.org/articles/10.3389/fnut.2022.1059163/full

**Comment by MyleeeA** [comment]
@cmirzayi @lwaldron @SvetlanaUP I'll like to curate this

**Comment by MyleeeA** [comment]
I'm done curating this, I curated for different covariates as well....I'll appreciate your feedback on this

**Comment by SvetlanaUP** [comment]
Ready for review. https://bugsigdb.org/Study_849

**Comment by MyleeeA** [comment]
Hi @lwaldron @cmirzayi @SvetlanaUP this article keeps popping up under studies without experiments under the TODO for Reviewers, and because of that someone else started curating and saved the first experiment, thankfully I noticed, else we would have had duplicate experiments......Can you please confirm why?
