### ISSUE TITLE
Patients with Acne Vulgaris Have a Distinct Gut Microbiota in Comparison with Healthy Controls

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#174]
Acta Derm Venereol. 2018 Aug 29;98(8):783-790. doi: 10.2340/00015555-2968. Patients with Acne Vulgaris Have a Distinct Gut Microbiota in Comparison with Healthy Controls

https://pubmed.ncbi.nlm.nih.gov/29756631/

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP
I would love to curate this. Please can this be assigned to me.

Scholastica Urua

**Comment by SvetlanaUP** [comment]
Assigned.

**Comment by Abiola-Salako** [comment]
Hello @SvetlanaUP please I would like to curate this, may I get assigned, please?

**Comment by SvetlanaUP** [comment]
@Abiola-Salako this paper is already assigned. Please choose another one.

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP this a link to my second curation (https://bugsigdb.org/Study_875). Please can it be reviewed for corrections?

Scholastica Urua

**Comment by Scholarpat** [comment]
@alerudivine

**Comment by Scholarpat** [comment]
https://bugsigdb.org/Study_875

@imalovee @mildredanashie

Please help review this curation. Thank you for your assist.

**Comment by Scholarpat** [comment]
@Lonercode thank you for your feedback.

**Comment by Omabekee** [comment]
An almost perfect curation! @Scholarpat  Kudos!⭐
Some points to take note:
1. When entering taxa for signatures on BugSigDB and they don't appear automatically, the next step is to use the [NCBI taxonomy browser](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi). For instance, when searching for a taxon like _Ruminococcaceae_, it may not directly show up in the search results. However, upon browsing the list, the first I saw on the list was _Oscillospiraceae_. By clicking on _Oscillospiraceae_, I found Ruminococcaceae listed among its **heterotypic synonyms**, which basically means different names but same taxon. It is still acceptable to enter heterotypic/ homotypic synonyms into BugSigDB. The same approach applies to other taxa like Firmicutes, Bacteroidetes, etc.
   
2. It's good for source descriptions (for signatures) to be descriptive enough so that anyone who comes across the study in the future can immediately tell what's going on without going too deep into the whole curation.

**CURATION RESULTS**
1. All elements marked "Needs review" (none "Incomplete") (1 point): **1**
2. Correct study design (1 point): **0**
3. Entered all relevant experiments and no irrelevant experiments (1 point): **1**
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): **1**
5. Condition entered according to contrast (correct EFO ontology) (1 point): **1**
6. Contrast groups correctly identified (1 point): **1**
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): **1**
8. Antibiotic exclusion correctly identified (1 point): **1**
9. Correctly identified sequencing details (2 points): **2**
10. Identified correct statistical test (1 point): **1**
11. Identified MHT correction (1 point): **1**
12. Correctly recorded matched on factors (1 point): **1**
13. Entered correct number of statistical tests per experiment (1 point): **1**
14. All diversity measures identified (1 point): **1**
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): **1**
16. All signature sources correctly identified  (-1 for each error)  (2 points): **2**
17. Abundance direction correctly selected (1 point): **1**
18. Members of Signatures identified correctly (2 points): **1**
19. Correct use of NCBI taxonomy (2 points): **2**

**Total: 21**
@SvetlanaUP review of Study 875 now complete. ✅

**Comment by Scholarpat** [comment]
Thank you very much, @Omabekee, for your review and feedback. I have taken note of your points and will strive to improve my curation in the future. 🙏🤗
