### ISSUE TITLE
Favorable subgingival plaque microbiome shifts are associated with clinical treatment for peri-implant diseases

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#177]
Favorable subgingival plaque microbiome shifts are associated with clinical treatment for peri-implant diseases – Davide Bazzani – npj Biofilms and Microbiomes

https://link.springer.com/article/10.1038/s41522-024-00482-z

**Comment by Ademolawe** [comment]
Can I curate this paper for my second contribution?
Name: Adebayo Eniola

**Comment by Ademolawe** [comment]
My curation is ready for review @ https://bugsigdb.org/Study_877
PS: I also curated a talk page for this study https://bugsigdb.org/Talk:Study_877
Thank you

**Comment by Folakunmi21** [comment]
Hello @Ademolawe I appreciate your efforts in attempting to curate this paper because it is one of those ones that are difficult to curate. This is what they did in the paper: they got the biomarkers in healthy group and peri-implantitis group at timepoint T1. Then they compared the abundance of the biomarkers in the cases after treatment (a and c), then in the contralateral samples for all groups after treatment (b and d- control sites). There were a total of 6 experiments with these comparisons.

**CURATION RESULT**
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0.5
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point):  0
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 0.5
8. Antibiotic exclusion correctly identified (1 point):1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 0.5
17. Abundance direction correctly selected (1 point): 0.5
18. Members of Signatures identified correctly (2 points): 0.5
19. Correct use of NCBI taxonomy (2 points): 2

Total (maximum 23 points): 17.5
@SvetlanaUP study 877 reviewed
