### ISSUE TITLE
Microbiome features associated with performance measures in athletic and non-athletic individuals: A case-control study 

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#178]
Microbiome features associated with performance measures in athletic and non-athletic individuals: A case-control study – Kinga Humińska-Lisowska – Plos One
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0297858

**Comment by AleruDivine** [comment]
Thank you so much!

**Comment by zheeburg** [comment]
Adedoja Isaac

Hello @SvetlanaUP, I will love to claim this article for Curation. Thank you

**Comment by SvetlanaUP** [comment]
@zheeburg this paper is already assigned. Please select another one.

**Comment by AleruDivine** [comment]
Hi @SvetlanaUP 

I have finished the curation. This article is ready for review.

Link to curation: https://bugsigdb.org/Study_873

Thank you so much!

**Comment by AleruDivine** [comment]
@RotimDesire

**Comment by AleruDivine** [comment]
@kwennb thank you for agreeing to do this

**Comment by kwennB** [comment]
> @kwennB @Scholarpat thank you for agreeing to do this

Yaay thank yo, let's do it

**Comment by AleruDivine** [comment]
@BarakatAA

**Comment by MyleeeA** [comment]
@AleruDivine 👍

**Comment by AleruDivine** [comment]
@flourishralph hey and welcome

**Comment by AleruDivine** [comment]
@Buraah thanks for the review

**Comment by Folakunmi21** [comment]
This was a good attempt for a second contribution @AleruDivine , well-done! please note the following:

•	The use of codes is not encouraged in curation. Your curation is meant to be clear enough without having to check the paper. The timepoints in the signature descriptions should have been defined in a bracket. I added this already
•	Your group definitions should properly describe the groups so that it is easy to tell the experiments apart, especially when they are similar as in your case. This is why I added the timepoints to the group definitions
•	You curated the wrong taxon for the last experiment. Ruminococcus was curated. I edited it to the correct one
•	I guess you duplicated the experiments since they were all similar. When you duplicate experiments, some parts don’t get filled in, like the MHT correction and confounders. I had to fill in both for all experiments except experiment 1. 

**CURATION RESULT**
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 0.5
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 2
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (2 points): 1
19. Correct use of NCBI taxonomy (2 points): 2

Total (maximum 23 points): 21.5

@SvetlanaUP study 873 reviewed

**Comment by AleruDivine** [comment]
Thank you so much @Folakunmi21. I truly appreciate the comprehensive feedback. I have taken thorough notes of the points highlighted and will ensure to incorporate them into my future curations. 🙏
