### ISSUE TITLE
Establishment of a non-Westernized gut microbiota in men who have sex with men is associated with sexual practices

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#179]
Establishment of a non-Westernized gut microbiota in men who have sex with men is associated with sexual practices – Kun Huang – Cell Reports Medicine

https://www.cell.com/cell-reports-medicine/fulltext/S2666-3791(24)00049-1

**Comment by uhabiba14** [comment]
hey there, i want to curate this paper. kindly assign this to me. @SvetlanaUP @cmirzayi

**Comment by uhabiba14** [comment]
hey @SvetlanaUP i completed this curation and needs review. thanks.

**Comment by SvetlanaUP** [comment]
Ready for review https://bugsigdb.org/Study_876

**Comment by cmirzayi** [comment]
| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 |0 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 0 |
| 10 | Identified correct statistical test | 1 | 0 |
| 11 | Identified MHT correction | 1 | 0 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 0 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 13 |

- Contrast for experiment 1 is number of sexual partners
- Study used shotgun/WGS and not 16S
- Statistical test was LEfSe for experiment 1
- MHT correction with LEfSe is rare and I see no evidence to suggest that was done
- Tables S2 and S4 can be curated so by my count you're missing 4-5 experiments at least

**Comment by MyleeeA** [comment]
Hi @cmirzayi @SvetlanaUP 

Can I work on effecting the corrections on this curation?
Thank you 🙏🏾

**Comment by SvetlanaUP** [comment]
@MyleeeA sure!

**Comment by MyleeeA** [comment]
Hi @SvetlanaUP 
I've been able to effect the corrections on this and I'll really love a feedback on this curation as it was a bit tricky for me and took longer than I imagined as I was prioritizing quality

**Comment by cmirzayi** [comment]
Hi @MyleeeA It looks much improved. I have one question: there's an empty experiment (experiment 5) that appears to be similar, but not identical, to experiment 7. 

I'm also not finding any evidence of controlling for confounders. Can you point me to where you're getting that information?

Also I see why you put matching but I don't think the matching reported actually has anything to do with the analysis since the matching was for people with heart diseased matched with people who did not have heart disease. It's a long article though and perhaps I'm missing something.

**Comment by MyleeeA** [comment]
Thank you @cmirzayi
I got the confounders from here 'Comparison of alpha diversity using the Shannon index revealed a higher microbiome diversity in MSM than in non-MSM (p = 0.028, Wilcoxon rank-sum test; adjusted p value [padj] = 0.017, adjusted by fixed-effect linear models for confounding effects including age, ethnicity, antibiotics use, BMI, and HIV infection (see STAR Methods; Figure 1A)'.  Did I have a wrong interpretation of this?

They were no signatures reported for Experiment 5 however the experiment exists in Supplementary Figure S4 (Alpha diversity), I felt the need to record it since the group was mentioned even though the alpha diversity was unchanged.  

For the matching I understood it as ‘The people with and without heart disease were all part of the study, matching wasn't mentioned anywhere else though so I'm thinking my interpretation could be wrong.

And yes It's a long article and seemed a bit confusing at some point

**Comment by cmirzayi** [comment]
Yeah this was an extremely challenging article. Let me think for a minute about these.

**Comment by cmirzayi** [comment]
Ok @MyleeeA I think keep experiment 5 as is. I'd remove matching and confounders controlled for. While they controlled for confounders in their alpha diversity analysis, they did not do so in their differential abundance analysis which is what counts. Let me know when that's done and I can mark it as reviewed.

**Comment by MyleeeA** [comment]
Thank you so much @cmirzayi 
Confounders and Matched on has been removed

**Comment by SvetlanaUP** [comment]
Reviewed. Thanks!
