### ISSUE TITLE
Differential effects of antiretroviral treatment on immunity and gut microbiome composition in people living with HIV in rural versus urban Zimbabwe

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#181]
Differential effects of antiretroviral treatment on immunity and gut microbiome composition in people living with HIV in rural versus urban Zimbabwe - Angela Sofia Burkhart Colorado - Microbiome 
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-023-01718-4

**Comment by Otakuwind** [comment]
Hi, I wish to curate this. thank you

**Comment by temmyoctavia08** [comment]
Hi, please can I curate this article 
Temitope

**Comment by SvetlanaUP** [comment]
@temmyoctavia08 it's already assigned. Please select another one.

**Comment by Isioma20** [comment]
Good morning @Otakuwind  I hope you are doing well.
I noticed this issue has been assigned for over 3 weeks for your second contribution and since this is the final week of contributions, I just want to know if you'd need help or want to collaborate or if you're done and need peer reviews . I'm willing to help out.

Thank you so much!

**Comment by Otakuwind** [comment]
@Isioma20  thanks for your concern, I have not been too good, that's why I have been on and off. I also need peer review if interested. Thanks for reaching out, much appreciated.

**Comment by Isioma20** [comment]
@Otakuwind you can drop the link to the study here and I'll review and give you feedback or tag me on the slack channel @idiaru Angela. I hope you feel better soon.

**Comment by Otakuwind** [comment]
Here is the link:  https://bugsigdb.org/Study_917

**Comment by Isioma20** [comment]
Hey @Otakuwind would you like me to send the review here?

**Comment by Otakuwind** [comment]
> Hey @Otakuwind would you like me to send the review here?

Sure

**Comment by Isioma20** [comment]
Hey @Otakuwind well done in the curation. These are my observations 
1. The study design seems to be longitudinal observational rather than cross-sectional observational. This is because participants were observed before and after at different time points
2. You seem to have missed the cofounders mentioned in the study. "a differential abundance (DA) analysis package for compositional microbiome data that allows for regression modeling to control for potential confounding factors. Specifically, we determined which genera differed between HC and the ART-experienced or ART-naïve cohorts in models that also included the effect of time, viral load, and location to control for confounders". This excerpt shows that cofounders were controlled for.  the recording of the office hour held last week is available on the slack channel. There is a simple and detailed explanation of cofounders
3. Antibiotics exclusion was stated in the study but it seems you might have missed it "Subjects were excluded from all cohorts if they had used antibiotics (apart from co-trimoxazole) within the prior 2 months"
4. "To determine genera that significantly differed in abundance across cohorts, we used ANCOM-BC"  Ancom which is available on the database seems to be the statistical test that was used in the study.
5. Clostridium sensu stricto has been resolved to be the clostridim genus with ncbi of 1485
6. From what I can observe in the study, I think you're supposed to have more experiments which include Comparison between the  i)PLWH ART naive vs control at baseline ii) PLWH ART naive vs control at both time points iii) PLWH ART experienced vs control at baseline iv)  PLWH ART experienced vs control at bothe timepoints. Then experiments that showed significant alpha diversity but which differential abundance was not stated are also to be curated. But they would have no signatures. 
7. The significance threshold was stated to be p-value "7.75e-05" which can be calculated to be 0.05 not 0.035 as stated in the curation.
8. The sample size would change when curating the experiments for analysis at both time points. This is because some participants were lost to follow up.
9. For the body site, feces was the only sample used for the microbiome analysis. Blood was used for the CD4 cell count. Therefore the only body site should be feces
10. I don't think the condition being contrasted is HIV rather I'm of the opinion that the condition be contrasted is the effect of antiretroviral treatment. You can look up the ontology for the closest term to this.

**Comment by keamybams** [comment]
Hello @Otakuwind , are you still curating this study, I noticed it has not been put up for review?

**Comment by Scholarpat** [comment]
Hello @Otakuwind, compliment of the day.
I'm available to collaborate with you and @keamybams to complete this curation.

Best regards,
Scholastica Urua

**Comment by SvetlanaUP** [comment]
@keamybams please finalize this curation.

**Comment by keamybams** [comment]
Alright @SvetlanaUP Thank you.

**Comment by keamybams** [comment]
@Scholarpat @MyleeeA @fiddyhamma Thanks for the review.

**Comment by keamybams** [comment]
Hello @SvetlanaUP, this study is ready for review.

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Here are the changes I made here;

- Changed condition from 'Clinical Treatment' to 'Gut Microbiome Measurement' in experiment 1. This is because patients in the case group were not yet exposed to treatment (ART naive).
- Altered group names and descriptions in all the experiments to include definition of acronyms used.

I'm uncertain about the group size for experiments 2 and 4. I've dropped this question on the slack channel and will update it once I get feedback.

Thank you!

**Comment by Scholarpat** [comment]
This was addressed during office hours. In Experiments 2 and 4, samples were collected from participants at both time points (baseline and after 24 weeks). At 24 weeks, some participants were lost to follow-up, and only participants who provided samples at both time points were used. The article was not very clear on the exact number of participants who were dropped in Experiment 4, so I have left the sample size for Group 1 blank for Experiment 4.

The curation is now complete @SvetlanaUP.

Thank you.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_917 reviewed.
