### ISSUE TITLE
Diagnosis of Crohn’s disease and ulcerative colitis using the microbiome

### ISSUE THREAD

**Issue by Folakunmi21** [waldronlab/BugSigDBcuration#183]
Diagnosis of Crohn’s disease and ulcerative colitis using the microbiome - Kang _et al_ - PMC
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10640746/

**Comment by samreen-19** [comment]
Hello, I would like to curate this paper

**Comment by AdegboyeRukayat** [comment]
@SvetlanaUP can you please assign this project to me

**Comment by samreen-19** [comment]
Hello @SvetlanaUP 

I have finished the curation. This article is ready for review.

Link to curation: https://bugsigdb.org/Study_926

Thank you

**Comment by samreen-19** [comment]
@AleruDivine here's the link to my curation https://bugsigdb.org/Study_926
thank you :)

**Comment by samreen-19** [comment]
@keamybams https://bugsigdb.org/Study_926

**Comment by samreen-19** [comment]
Hi @SvetlanaUP I just noticed that my paper has been reviewed, however it has not been scored yet. I feel like I could do better once I am aware of the errors I made. Thank you.

**Comment by SvetlanaUP** [comment]
@samreen-19 please be patient. Your curation is still under review by @Omabekee.

**Comment by samreen-19** [comment]
Thank you for informing @SvetlanaUP

**Comment by Omabekee** [comment]
This was a good second curation attempt @samreen-19. Unfortunately, you missed some basics. Here are some errors you made and important points to take note which will help your future curations:
1. The condition is what is being contrasted between group 0 and group 1 for an experiment. In this case, for experiment 3, "gut microbiome measurement" looks to me like the best fit since both groups have some type of IBD (UC and CD) and they were comparing the microbial taxa between both groups.
2. You curated from the wrong source, this made a huge impact on your final score. It's always good to look out for supplementary files (if available). The experiments in this study were curated from the supplementary files.
3. It's good for descriptions (for signatures and groups) to be descriptive enough so that anyone who comes across the study in the future can immediately tell what's going on without reading the whole paper.
4. Only one sequencing platform was used in this study- MGISEQ, you entered an additional one- Illumina which is not correct.
5. Two statistical tests were used: Mann-Whitney and T-test

**CURATION RESULTS**
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
7. Condition entered according to contrast (correct EFO ontology) (1 point): 0.5
8. Contrast groups correctly identified (1 point): 1
9. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
10. Antibiotic exclusion correctly identified (1 point): 1
11. Correctly identified sequencing details (2 points): 1
12. Identified correct statistical test (1 point): 1
13. Identified MHT correction (1 point): 1
14. Correctly recorded matched on factors (1 point): 1
15. Entered correct number of statistical tests per experiment (1 point): 0.5
16. All diversity measures identified (1 point): 1
17. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
18. All signature sources correctly identified (-1 for each error) (2 points): 0
19. Abundance direction correctly selected (1 point): 0
20. Members of Signatures identified correctly (2 points): 0
21. Correct use of NCBI taxonomy (2 points): 2

Total = 15
@SvetlanaUP, grading of Study 926 complete. ✅ Review still in progress.

**Comment by samreen-19** [comment]
Thank you so much @Omabekee. It's unfortunate that I messed up the signature sources, but I'll surely keep that in mind while curating my next papers.
