### ISSUE TITLE
Abundance alteration of nondominant species in fecal-associated microbiome of patients with SAPHO syndrome

### ISSUE THREAD

**Issue by Folakunmi21** [waldronlab/BugSigDBcuration#184]
Abundance alteration of nondominant species in fecal-associated microbiome of patients with SAPHO syndrome - Zhen _et al_ - BMC
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-021-02221-2

**Comment by omojokunoluwatomisin10** [comment]
Hello, can be assigned to this

**Comment by AdegboyeRukayat** [comment]
@SvetlanaUP can you please assign this project to me

**Comment by omojokunoluwatomisin10** [comment]
I am done with the curation of the Article, Please kindly review it @SvetlanaUP @Folakunmi21 https://bugsigdb.org/Study_902/Experiment_1

**Comment by SvetlanaUP** [comment]
Hi @omojokunoluwatomisin10,
your curated paper is with tag "needs review" that means now it's in our hands under review and you are kindly asked to not make any changes while we are reviewing it. Thank you.

**Comment by Peacesandy** [comment]
Hi @omojokunoluwatomisin10 this is a good first curation attempt, however, there were some errors, here are some points to take note ✍️

- Signatures are curated from the differential abundance result, you curated the signatures from Figure 2, which is the Relative abundances across samples at the family and genus levels, and core taxa analysis at the genus and OTU levels. 

- Figure 2 is not curatable since we are not interested in relative abundances. Thus, we curated Figure 3 for significant differential abundances.


**CURATION RESULT**

All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 1
Entered all relevant experiments and no irrelevant experiments (1 point): 1
Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
Condition entered according to contrast (correct EFO ontology) (1 point): 1
Contrast groups correctly identified (1 point): 1
Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
Antibiotic exclusion correctly identified (1 point): 1
Correctly identified sequencing details (2 points): 2
Identified correct statistical test (1 point): 1
Identified MHT correction (1 point): 1
Correctly recorded matched on factors (1 point): 1
Entered correct number of statistical tests per experiment (1 point): 1
All diversity measures identified (1 point): 1
Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
All signature sources correctly identified (-1 for each error) (2 points): 0
Abundance direction correctly selected (1 point): 0
Members of Signatures identified correctly (2 points): 0
Correct use of NCBI taxonomy (2 points): 0

**Total (maximum 23 points): 16**

@SvetlanaUP  https://bugsigdb.org/Study_902 corrected and reviewed  ✅

**Comment by omojokunoluwatomisin10** [comment]
Thanks @Peacesandy for the feedback, it's duly appreciated
