### ISSUE TITLE
Alterations of conjunctival microbiota associated with orthokeratology lens wearing in myopic children

### ISSUE THREAD

**Issue by Folakunmi21** [waldronlab/BugSigDBcuration#186]
Alterations of conjunctival microbiota associated with orthokeratology lens wearing in myopic children - Zhang _et al_ - BMC
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-023-03042-1

**Comment by Ebere330** [comment]
@SvetlanaUP Please may I be assigned to this paper to be curated?

**Comment by Ebere330** [comment]
Hi, I am through with my second contribution and would like for it to be reviewed.  Here is the link below:
https://bugsigdb.org/Study_913

@SvetlanaUP

**Comment by Peacesandy** [comment]
Hello @Ebere330 this is a fair curation attempt, you missed out on a lot of details, which I will point out below.

- The condition in the study is Myopia, which is available on EFO
- The groups were correctly entered, but it would have been great, if a little explanation was added to Group 0, instead of just writing N group, this will describe what the N group does.
- The statistical test used is LEfSe 
- Data transformation is relative abundance 
- There is an MHT correction
- Figure 6 is not curatable since we are not interested in receiver-operating characteristic (ROC) curves. Thus, we curated Figure 4 for significant differential abundances.

*N/B*: For ease, please go through the paper and the reviewed study. All corrections have been made and the study has been marked reviewed.

**CURATION RESULTS**

All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 1
Entered all relevant experiments and no irrelevant experiments (1 point): 1
Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
Condition entered according to contrast (correct EFO ontology) (1 point): 0
Contrast groups correctly identified (1 point): 1
Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
Antibiotic exclusion correctly identified (1 point): 1
Correctly identified sequencing details (2 points): 2
Identified correct statistical test (1 point): 0
Identified MHT correction (1 point): 0
Correctly recorded matched on factors (1 point): 1
Entered correct number of statistical tests per experiment (1 point): 0
All diversity measures identified (1 point): 1
Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
All signature sources correctly identified (-1 for each error) (2 points): 0
Abundance direction correctly selected (1 point): 0
Members of Signatures identified correctly (2 points): 0
Correct use of NCBI taxonomy (2 points): 2

**Total (maximum 23 points): 14**

@SvetlanaUP https://bugsigdb.org/Study_913 corrected and reviewed ✅

**Comment by Ebere330** [comment]
Thank you @Peacesandy and @SvetlanaUP  for the review and corrections made. Will make necessary amendments as suggested ... corrections well taken and noted
