### ISSUE TITLE
Oral and gut dysbiosis leads to functional alterations in Parkinson’s disease 

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#196]
Oral and gut dysbiosis leads to functional alterations in Parkinson’s disease – Sungyang Jo et al. – npj Parkinson's Disease
https://www.nature.com/articles/s41531-022-00351-6

**Comment by Hamidatmohd** [comment]
I would like to be assigned to this paper, please @SvetlanaUP 
My name is Hamidat Mohammed

**Comment by Isioma20** [comment]
Good morning @Hamidatmohd  I hope you are doing well.
I noticed this issue has been assigned for over 3 weeks for your second contribution and since this is the final week of contributions, I just want to know if you'd need help or want to collaborate or if you're done and need peer reviews . I'm willing to help out.

Thank you so much!

**Comment by SvetlanaUP** [comment]
Assigned to @Isioma20

**Comment by Isioma20** [comment]
Thank you!

**Comment by Isioma20** [comment]
Hi. This study is ready for review and feedback. Thank you
https://bugsigdb.org/Study_957

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

In this study I changed data transformation from 'raw counts' to 'relative abundance'. All other details have been correctly curated.
The curation is complete. Thank you!

Weldone @Isioma20 👏

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_957 reviewed.
