### ISSUE TITLE
Evaluation of fecal microbiota transplantation in Parkinson's disease patients with constipation

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#197]
Evaluation of fecal microbiota transplantation in Parkinson's disease patients with constipation – Xiao-yi Kuai et al. – Microbial Cell Factories
https://microbialcellfactories.biomedcentral.com/articles/10.1186/s12934-021-01589-0

**Comment by ikehdarlington** [comment]
Good morning my leader and mentor, I just finished the introductory curation for newbies and would like this paper to be assigned to me to curate as my first official task. Though I am still in the process of understanding fully the BugSigBD curation procedure, I believe with this first article I can fully comprehend the procedure practically. Thank you for the opportunity. I would also like any article on autism to be assigned to me as my son has autism and it would be helpful to me to understand the condition better and how to help him better.

**Comment by ikehdarlington** [comment]
Good day mentor, this curation is up for review. Thank you

**Comment by ikehdarlington** [comment]
Sorry! This is the link to the curation.
https://bugsigdb.org/Study_918

**Comment by Omabekee** [comment]
Overall this was a really good second curation! ⭐ @ikehdarlington , some points to take note:

1. The condition is what is being contrasted between group 0 and group 1 for an experiment. In this case, for experiment 2 upwards, 'response to transplant' is the right condition to curate.
2. You didn't curate all the taxa identified in the LeFSe result (I've added them).
3. When entering taxa for signatures on BugSigDB and they don't appear automatically, the next step is to use the [NCBI taxonomy browser](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi). For instance, when searching for a taxon like Actinobacteria, it may not directly show up in the search results. However, upon browsing the list, the first I saw on the list was Actinomycetota. By clicking on Actinomycetota, I found Actinobacteria listed among its synonyms, which basically means different names but same taxon. It is still acceptable to enter heterotypic/ homotypic synonyms into BugSigDB. The same approach applies to other taxa like Firmicutes, Bacteroidetes, etc.
4. Figure 3b, c, d and e signatures are curatable, this is because this particular relative abundance figure is clearly showing the significant differences between the groups, not just the taxa each group contains (as seen in 3a, which is not curatable).
5. It's good for source descriptions (for signatures) to be descriptive enough so that anyone who comes across the study in the future can immediately tell what's going on without going too deep into the whole curation.

**CURATION RESULTS**
1. All elements marked "Needs review" (none "Incomplete") (1 point): **1**
6. Correct study design (1 point): **1**
7. Entered all relevant experiments and no irrelevant experiments (1 point): **0.5**
8. Body site correctly identified (i.e. does not include multiple sites) (1 point): **1**
9. Condition entered according to contrast (correct EFO ontology) (1 point): **0.5**
10. Contrast groups correctly identified (1 point): **1**
11. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): **1**
12. Antibiotic exclusion correctly identified (1 point): **1**
13. Correctly identified sequencing details (2 points): **1**
14. Identified correct statistical test (1 point): **1**
15. Identified MHT correction (1 point): **1**
16. Correctly recorded matched on factors (1 point): **1**
17. Entered correct number of statistical tests per experiment (1 point): **0.5**
18. All diversity measures identified (1 point): **1**
19. Diversity results correctly entered as increased/decreased/unchanged (1 point): **1**
20. All signature sources correctly identified  (-1 for each error)  (2 points): **2**
21. Abundance direction correctly selected (1 point): **1**
22. Members of Signatures identified correctly (2 points): **1**
23. Correct use of NCBI taxonomy (2 points): **2**
**Total = 19.5**

@SvetlanaUP , review of Study 918 complete. ✅

**Comment by ikehdarlington** [comment]
@Omabekee Thank you so very much for your positive feedback and valuable corrections. I appreciate the guidance and will ensure I make use of the feedback going forward to ensure the accuracy and quality of the curation on BugSigDB.
