### ISSUE TITLE
A Pilot Microbiota Study in Parkinson's Disease Patients versus Control Subjects, and Effects of FTY720 and FTY720-Mitoxy Therapies in Parkinsonian and Multiple System Atrophy Mouse Models

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#216]
A Pilot Microbiota Study in Parkinson's Disease Patients versus Control Subjects, and Effects of FTY720 and FTY720-Mitoxy Therapies in Parkinsonian and Multiple System Atrophy Mouse Models - Vidal-Martinez et al. - Journal of Parkinson's disease
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7029363/

**Comment by FlourishRalph** [comment]
Hi @Omabekee I'd like to work on this, please assign it to me.

**Comment by FlourishRalph** [comment]
@SvetlanaUP please assign this to me

**Comment by FlourishRalph** [comment]
@buraah @scholarpat

**Comment by FlourishRalph** [comment]
Hi @SvetlanaUP  
I’m done with curating this paper and it’s ready for review 

Here is the link: 

https://bugsigdb.org/Study_922
 Thank you.

**Comment by FlourishRalph** [comment]
@rotimidesire

**Comment by cmirzayi** [comment]
| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 0 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 0 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 2 |
| 17 | Abundance direction correctly selected | 1 | 0 |
| 18 | Members of Signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 18 |

Figure 1B just repeats what is present on the genus level in Table 1 Column A. Based on Table 1, there were only 3 significant taxa in 2 experiments:

Mouse 10 month (A53T)
Firmicutes

Human
Verrucomicrobiarceae
Akkermansia

I am not sure where the significant results for 17 months A53T and 10-11 months CNPaSyn are coming from because they are not present in the identified source.

**Comment by FlourishRalph** [comment]
Hi @cmirzayi, thank you for your review.

The antibiotic exclusion is on page 186 and states that 'use of antibiotics within 2 weeks prior to initiation of the study' was part of the exclusion criteria. This was included in my curation so I'm unsure why I got zero points in number 8 (Antibiotic exclusion correctly identified).

**Comment by cmirzayi** [comment]
Apologies. I've added the point back.

**Comment by FlourishRalph** [comment]
Thank you!

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP , I'll love to help out in correcting this.

**Comment by SvetlanaUP** [comment]
@Scholarpat go ahead!

**Comment by Scholarpat** [comment]
Hello @cmirzayi @SvetlanaUP ,

Here are the changes and observations I made to this curation:

1. Humans were not matched on any factor; only mice were matched on age. Therefore, I removed "matched-on" from Experiment 1 and included it in Experiment 2.

2. The statistical test used in the human experiment (Experiment 1) is Mann-Whitney (Wilcoxon), while that of the mice group (Experiment 2) is not specified. The initial curator stated Spearman Correlation as the statistical test for Experiment 2, but I edited that part out and left it blank.

3. Two taxa are significant in the human experiment:
   - Verrucomicrobiarceae
   - Akkermansia
   Both are increased in the PD group, hence eliminating the need for 'Signature 2' in Experiment 1.

4. One significant taxon (Firmicutes) is increased in 10-month-old transgenic (Tg) mice, and none are significantly decreased, eliminating the need for 'Signature 2' in Experiment 2.

5. There are no significant results for 17-month A53T and 10-11-month CNPaSyn, as you also stated above, and there's also no alpha diversity for these experiments. Therefore, I'm wondering if there's any need to curate these experiments (Experiment 3 and 4). Can they can be deleted?

Please I’d like to delete;
- Signature 2 in exp. 1
- Signature 2 in exp. 2
- Experiments 3 & 4 and their signatures
