### ISSUE TITLE
Longitudinal and Comparative Analysis of Gut Microbiota of Tunisian Newborns According to Delivery Mode

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#231]
Longitudinal and Comparative Analysis of Gut Microbiota of Tunisian Newborns According to Delivery Mode – Mariem Hanachi et al. – Frontiers in Microbiology
https://www.frontiersin.org/journals/microbiology/articles/10.3389/fmicb.2022.780568/full

**Comment by Nana-Habiba** [comment]
please @SvetlanaUP may i curate this paper

**Comment by eve10111** [comment]
Hi @SvetlanaUP! I would like to curate this paper, can you kindly assign it to me? Thank you.

**Comment by farheengul001** [comment]
Hi @SvetlanaUP! may I curate this paper? Thank you.

**Comment by Nana-Habiba** [comment]
Thank you accepted.

**Comment by TitilayoMG** [comment]
@SvetlanaUP My name is Ganiyu Modinat. Please may I curate this paper

**Comment by TitilayoMG** [comment]
@SvetlanaUP My name is Ganiyu Modinat. Please may I curate this paper

**Comment by SvetlanaUP** [comment]
@TitilayoMG this paper is already assigned. Today we will be adding more papers, thank you for your patience.

**Comment by Nana-Habiba** [comment]
@cmirzayi @SvetlanaUP, Please this my paper needs review
https://bugsigdb.org/Study_932
Thank you.

**Comment by Nana-Habiba** [comment]
@cmirzayi @SvetlanaUP, My second curation is also ready for review:
https://bugsigdb.org/Study_1027

**Comment by Folakunmi21** [comment]
Hello @Nana-Habiba here are the corrections to your curation:
- condition is "delivery method"
- supplemental table 3 is not curatable. It does not show the groups the markers belong to and whether they are increasing or decreasing.
- no alpha diversity analysis between the groups at the different time points
please, make the corrections so that I can mark the remaining experiments as reviewed.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point):  0 
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 0.5
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 0.5
16. All signature sources correctly identified  (-1 for each error)  (2 points): 1
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (2 points): 2
19. Correct use of NCBI taxonomy (2 points): 2

Total (maximum 23 points): 19

@SvetlanaUP study 932 graded

**Comment by Nana-Habiba** [comment]
@Folakunmi21 @SvetlanaUP @cmirzayi Thanks for the review, i have made the corrections but i have a few points to make
1. supplemental table 3 is not curatable. It does not show the groups the markers belong to and whether they are increasing or decreasing. (I did not curate this before because i was not sure until during our Thursday meeting i asked @cmirzayi here was her reply 
(
![chat](https://github.com/waldronlab/BugSigDBcuration/assets/156927713/8d497823-66cf-46f5-a701-4af44fbec46f) )
Please take a look again at that paper, this time around it was the different time point that was of interest not the delivery mode again.

**Comment by Nana-Habiba** [comment]
@cmirzayi From our chat supplemental table 3 is  curatable ? @Folakunmi21  you have deleted those tables i really need a second review on this because at this point who should i follow i am confused.

**Comment by Folakunmi21** [comment]
Kindy discuss with @cmirzayi on issues concerning this curation moving forward.

**Comment by cmirzayi** [comment]
Table 3 is curatable. It's a LEfSe one-against-the rest analysis so you would curate:

An experiment for group 1 (day 0) vs. group 0 (days 15 and 30)
An experiment for group 1 (day 15) vs. group 0 (days 0 and 30)
An experiment for group 1 (day 30) vs. group 0 (days 0 and 15)

It looks like @Nana-Habiba curated it correctly. Please credit her those points back @Folakunmi21.

**Comment by Folakunmi21** [comment]
@cmirzayi I'm on it. I'm rolling back the deletion logs.

**Comment by Folakunmi21** [comment]
@Nana-Habiba I apologize for the oversight. Experiments 5-7 are back there. please correct the conditions (timepoint in this case), the group names should be the timepoints only, their definitions should be edited too, cross check that the alpha diversity is from figure 1.

**Comment by Nana-Habiba** [comment]
@Folakunmi21 I have updated based on the revert back according to @cmirzayi .
Kindly remove this: supplemental table 3 is not curatable. It does not show the groups the markers belong to and whether they are increasing or decreasing.
no alpha diversity analysis between the groups at the different time points
from the first place you scored me since you have be clarified that it is curatable for correct reference purposes.
Last but not the least after all this back and forth na 1 mark you still add, i feel cheated. I have to go back to my curation after your comment reading it over and over again and keep saying to myself that this table was curatable.  The stress in typing those taxa and in some seconds they were all just deleted.

**Comment by Folakunmi21** [comment]
@Nana-Habiba You entered alpha diversity results for the comparisons between the delivery methods at the different time points. I'm referring to experiments 2 to 4. This is why you have 0.5 points for number 14 and 15 in the marking guide. You failed the condition. These are the 2 places where I deducted your marks. So how did I cheat you out of your marks? I deleted the experiments and took my own time to put them back there and even apologized so what are you saying about "the stress in typing out those taxa". Whatever further issues you have with this curation, reach out to Chloe. Lastly, watch your fucking tone with me. You just upset me and disrupted my lunch.

**Comment by SvetlanaUP** [comment]
@Nana-Habiba we are very sorry if you feel stressed while doing an open source project which involves everyday back and forth actions. Please you should not feel cheated, all your work is noted. Thank you.

**Comment by Nana-Habiba** [comment]
@SvetlanaUP Noted, I don't feel cheated any more. As for the stress i referred to was the correct signature i created been deleted in seconds. esp. for 6 and 7 experiment it was pretty much. Learnt a lot and became familiar with many taxon names
