### ISSUE TITLE
Metagenomic analysis of faecal microbiome as a tool towards targeted non-invasive biomarkers for colorectal cancer

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#24]
https://pubmed.ncbi.nlm.nih.gov/26408641/

**Comment by sopeadeniji** [comment]
@lwaldron  Please assign this article to me.

**Comment by lwaldron** [comment]
Done, thank you!

**Comment by sopeadeniji** [comment]
@cmirzayi please review the completed curation : https://bugsigdb.org/Study_748

**Comment by claregri** [comment]
Hi, thanks for your effort on this curation! Please note that even though this study evaluates data from Denmark and Chinese studies, the Danish data are not included in the differential abundance assessment, so it should only be China in the country field (I made this update for you). Please see my notes and suggestions below in order to update your work.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 0 (even though there are case and control groups in this study, I would say this is a cross-sectional observational design)
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 0 (I wouldn’t say “cohort” here because that’s just the group overall. Since this paper is examining the difference between colorectal cancer patients and controls, Group 1 should be “Colorectal cancer cases” and the definition should be updated accordingly. Also, please use the sample sizes from Cohort 1 only - 74 cases and  54 controls)
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 0 (this is tricky because they mention several statistical tests in the paper. You should be looking for the one that they specifically use for the comparison you’re curating in the signatures. Hint: you’ll find it in the “Taxonomic alterations in CRC gut microbiomes” section)
11. Identified MHT correction (1 point): 0 (a good clue for this is if they are using FDR-corrected or q-values)
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 0
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 0 (you should be curating the mOTU results from Supplementary Table S8 - can be found at the bottom of the paper under “Online Tables”)
17. Abundance direction correctly selected (1 point): Not scored due to incorrect curation
18. Members of Signatures identified correctly (2 points): Not scored due to incorrect curation
19. Correct use of NCBI taxonomy (2 points): Not scored due to incorrect curation

Total (maximum 23 points): Not scored due to incorrect curation

**Comment by sopeadeniji** [comment]
Hi Chloe,

Please, open up the curation for other curators to finish. I have other priorities at this time and can no longer work on BugSigDB project.

Best,

Sophy

**Comment by cmirzayi** [comment]
@sopeadeniji No worries. Thank you for your efforts!

**Comment by lightamadi-stack** [comment]
Good day @SvetlanaUP, this paper is on colorectal cancer. Kindly add the CRC label.

Thank you.
