### ISSUE TITLE
Sleep deprivation-induced anxiety-like behaviors are associated with alterations in the gut microbiota and metabolites

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#248]
Sleep deprivation-induced anxiety-like behaviors are associated with alterations in the gut microbiota and metabolites – Zhang et al. – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.01437-23

**Comment by Iam-Iman** [comment]
Hi, @SvetlanaUP may I please be assigned this paper ?

**Comment by eve10111** [comment]
@SvetlanaUP , I can see this article has not been assigned yet. Would you kindly assign it to me. Thank you very much

**Comment by Juliana-Oluwatobi** [comment]
I am interested in contributing to this paper kindly assign it to me @SvetlanaUP

**Comment by Iam-Iman** [comment]
Thank you @SvetlanaUP

**Comment by SvetlanaUP** [comment]
Ready for review https://bugsigdb.org/Study_895

**Comment by SvetlanaUP** [comment]
| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 |0 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 0 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 0 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 0 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 0 |
| 17 | Abundance direction correctly selected | 1 | 0 |
| 18 | Members of signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 12 |

- Richness is reported as the Chao1 index; not both richness and Chao1.
- significant differences in alpha diversity is reported in the experiment: samples collected at baseline (BSL) versus 7 days post-SD (7d-SD)
- Figure 3D is source of the signatures in several experiments that are missed in this curation.

**Comment by AleruDivine** [comment]
@SvetlanaUP this still has "needs review" highlighted and the feedback note does not say it has been corrected. I would love to help out with the correction of this study from the feedback given.

**Comment by SvetlanaUP** [comment]
@SvetlanaUP sure!

**Comment by AleruDivine** [comment]
Good morning @SvetlanaUP, I somehow missed this email. 
I will get started with the corrections right away. 
Thank you so much!

**Comment by AleruDivine** [comment]
Hi @SvetlanaUP, I have completed the corrections to the curation based on the feedback you provided.
Corrections and changes made include: 

1. Remove the matched-on factor because the paper did not state that the rats were matched on any factor. Only that 6 weeks old rats were purchased.
2. Removed Mann-Whitney U test as one of the statistical test, the reason is Mann-Whitney U test was used to compare differences in gut microbiota alpha diversity among the groups. I left LEfSe as the statistical test used because only LEfSe was used to identify differential bacterial species between groups. 
3. Changed data transformation to be  centered-log ratio and here is an excerpt explaining why "One-way analysis of variance (ANOVA) was used to compare the relative abundances of taxa (transformed into a centered-log ratio) among the four groups.".
4. Corrected alpha diversity measures to only Chao1 index (richness) and Shannon index (diversity).
5. Corrected the contrast groups for experiment 1 and curated an additional 5 experiments resulting in a total of 6. The reason for the additional 3 experiments is because the study stated that the effect of multi-probiotic supplementation was also assessed in alleviating SD-induced anxiety-like behavior.

**Contrast groups**
Baseline (0) vs D7-SD (1)
Baseline (0) vs D21-SA (1)
Baseline (0) vs D21-MP (1)
D7-SD (0) vs D21-SA (1)
D7-SD (0) vs D21-MP (1)
D21-SA (0) vs D21-MP (1)

6. All signatures have been identified and curated from **figure 3d.**

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,
For this curation I changed data transformation from centered-log ratio to relative abundance. I've also updated the signature description for clarity. This curation is complete. 
Thank you!

Well done @AleruDivine 👏, interpreting the signatures must have been tasking.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_895 reviewed.

**Comment by SvetlanaUP** [comment]
❤️ for @AleruDivine

**Comment by AleruDivine** [comment]
Thank you @Scholarpat and @Scholarpat
