### ISSUE TITLE
Exploring nasopharyngeal microbiota profile in children affected by SARS-CoV-2 infection 

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#249]
Exploring nasopharyngeal microbiota profile in children affected by SARS-CoV-2 infection – L Roman – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.03009-23

**Comment by Druscillaa** [comment]
@SvetlanaUP please assign me this project

**Comment by omojokunoluwatomisin10** [comment]
kindly assign me this project @SvetlanaUP

**Comment by Druscillaa** [comment]
Thank you

**Comment by Druscillaa** [comment]
@SvetlanaUP please review 

https://bugsigdb.org/Study_965

**Comment by Omabekee** [comment]
This was a good second curation attempt @Druscillaa. Here are some corrections to the error you made, I've presented them as simply as I can. Please **implement** all and ask for help in the slack community where you're not sure.
**Corrections**
1. Statistical test: LEfSe was used not ANOVA (see method section).
2. Matched on: Age is the only variable that was matched on (confirm by using ctrl + f).
3. Incomplete signatures: From figure 3, there should be about 28 taxa in total for COVID-19 (increased signature) and 17 for ctrls (decreased signature).
4. Source descriptions: for signatures should be more descriptive "**Differences in bacterial taxa abundance of nasopharyngeal (NP) microbiota in COVID-19 patients VS CTRL groups**" should be more appropriate.
5. Group descriptions should also be more descriptive, "healthy control group*, COVID-19 patients*
6. Additional experiment: Figure S4 of the supplemental file should be curated as an additional experiment.
**COVID-19 vs NO COVID-19
Please read the paper again to understand the group descriptions of this new experiment so that you can curate well.**

**CURATION RESULTS**
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0.5
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
9. Antibiotic exclusion correctly identified (1 point): 1
10. Correctly identified sequencing details (2 points): 2
11. Identified correct statistical test (1 point): 0
12. Identified MHT correction (1 point): 1
13. Correctly recorded matched on factors (1 point): 0.5
14. Entered correct number of statistical tests per experiment (1 point): 0
15. All diversity measures identified (1 point): 1
16. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
17. All signature sources correctly identified (-1 for each error) (2 points): 1
18. Abundance direction correctly selected (1 point): 1
19. Members of Signatures identified correctly (2 points): 0.5
20. Correct use of NCBI taxonomy (2 points): 2

Total = 17.5
@SvetlanaUP, grading of Study 965 complete. ✅ Review still in progress

**Comment by Omabekee** [comment]
Hi @Analyst-Joan, I need your assistance here. Can you work with @Druscillaa to complete this curation?

**Comment by Analyst-Joan** [comment]
Alright @Omabekee, I'll do that.
@Druscillaa please what's your slack username, so we continue the discussion there?

**Comment by Analyst-Joan** [comment]
Good evening @Omabekee,
 I reached out to @Druscillaa on slack channel yesterday morning but yet to get any feedback.

**Comment by Omabekee** [comment]
@Analyst-Joan Let's wait till evening, if they don't respond please proceed with the curation. Thanks a bunch.!

**Comment by Analyst-Joan** [comment]
Alright

**Comment by Analyst-Joan** [comment]
> Alright, Thanks.

Good afternoon @Omabekee 

I'm now working on the required corrections. I'd revert here once i'm done. 

Thank you

**Comment by Analyst-Joan** [comment]
Good afternoon @Omabekee

I'm done effecting the corrections for [Study_965](https://bugsigdb.org/Study_965) and it's now ready for review.

Thanks.

**Comment by Omabekee** [comment]
@SvetlanaUP 2nd review complete. ✅ This issue can now be closed. Thank you.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_965 reviewed.
