### ISSUE TITLE
Metabolic disorder and intestinal microflora dysbiosis in chronic inflammatory demyelinating polyradiculoneuropathy

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#258]
Metabolic disorder and intestinal microflora dysbiosis in chronic inflammatory demyelinating polyradiculoneuropathy -- Fu et al. -- Cell & Bioscience
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9832664/

**Comment by zheeburg** [comment]
Hi @SvetlanaUP, Please assign me this study for curation.

**Comment by zheeburg** [comment]
Thank you @SvetlanaUP

**Comment by zheeburg** [comment]
Hi @SvetlanaUP I am done curating this study for review. Here is the link to the curation. https://bugsigdb.org/Study_882

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Here are the changes I made to this curation:

- Location of subjects: Changed from USA to _**China**_
- Body site: Changed from Colon and Large intestine to **_'feces'_**
- Sequencing type: Changed from 16S to **_WMS_**
- Matched on: Changed from "type I diabetes mellitus, type II diabetes mellitus, dyslipidemia, non-alcoholic fatty liver disease, neurodegenerative disorders" to **_"age and sex"_**
- Signature: Curated **_Figure 6A_** instead of Figure 5, which was initially curated.

This curation is complete.
Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_882 reviewed.
