### ISSUE TITLE
Curcumin Regulates Gut Microbiota and Exerts a Neuroprotective Effect in the MPTP Model of Parkinson's Disease

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#261]
Curcumin Regulates Gut Microbiota and Exerts a Neuroprotective Effect in the MPTP Model of Parkinson's Disease -- Zhu et al. -- Evid Based Complement Alternat Med
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9715342/

**Comment by MyleeeA** [comment]
Hi @Omabekee 
Can I be assigned  to this?

Thank you 🙏

**Comment by SvetlanaUP** [comment]
@MyleeeA could you please share your curation of https://github.com/waldronlab/BugSigDBcuration/issues/214 ?

**Comment by SvetlanaUP** [comment]
@MyleeeA sure!

**Comment by MyleeeA** [comment]
Hi @SvetlanaUP this curation is ready for for review 
Thank you 🙏🏾

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_960 ready for review

**Comment by Scholarpat** [comment]
Hi @MyleeeA,

This is a wonderful curation. Curating all those signatures must have taken a lot of effort. Well done! 🙌

I tried to resolve some of the taxa but couldn't make headway. 😅

Here are my observations:

1. I noticed that for signature 2 of experiment 3, *Candidatus Saccharimonadas* (highlighted in orange) was curated. Can you kindly recheck that? What is reported in the study is *Candidatus Saccharimonas* (TXID - 1331051).

2. I think the source description should be more descriptive. Rather than 'Analysis of specie differences by Lefse,' it would be better to use something like 'Differential distribution of gut microbiota in ABC vs. XYZ,' depending on the groups in each experiment.

Thank you very much.

**Comment by SvetlanaUP** [comment]
Let's see what's @MyleeeA's opinion!

**Comment by MyleeeA** [comment]
Thank you for your observations @Scholarpat 

I agree with your points, _Candidatus Saccharimonadas_ was possibly curated in error as _Candidatus Saccharimonas_ already exists amongst the taxas
Now I remember the curation process was really tasking, it makes me happy I didn’t make so many mistakes. 
Thanks again for your observation and I can change the description you are proposing us actually more descriptive.

**Comment by SvetlanaUP** [comment]
Please do let me know when the curation is complete @MyleeeA Thanks!

**Comment by MyleeeA** [comment]
All done @SvetlanaUP, Thanks!
Thank you again @Scholarpat

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_960 reviewed.
