### ISSUE TITLE
Modulation of the Gut Microbiota in Memory Impairment and Alzheimer’s Disease via the Inhibition of the Parasympathetic Nervous System

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#267]
Modulation of the Gut Microbiota in Memory Impairment and Alzheimer’s Disease via the Inhibition of the Parasympathetic Nervous System -- Park and Wu -- International Journal of Molecular Sciences
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9657043/

**Comment by samreen-19** [comment]
Hello, can I be assigned to curate this article please?

**Comment by SvetlanaUP** [comment]
@samreen-19 is this study ready for review?

**Comment by samreen-19** [comment]
Yes @SvetlanaUP https://bugsigdb.org/Study_997 Here's my curation

**Comment by Scholarpat** [comment]
Here's a revised version of your write-up:

---

Hi @SvetlanaUP,

Here are the changes I made:

Experiments 1-3 are part of a meta-analysis that selected and combined data from four different human AD studies. The DNA was amplified using 16S amplicon primers in the V3-V4 region for three studies and in the V2 region for one study. Because this is a meta-analysis combining data from different studies with different hypervariable regions of the 16S sequencing, I left out this field in the curation and included it in the discussion/talk page.

The groups for each experiment were not properly organized. I've corrected this and curated their signatures accordingly. I've also curated Experiment 6 (and one signature for it, which is not displaying; I have reported this issue) which was not initially curated.

Each experiment is supposed to have one signature each. Please kindly delete the following:

- Signature 2 of Experiments 1, 2, 4, and 5.

Thank you very much. This curation is complete.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_997 reviewed.
