### ISSUE TITLE
The subgingival microbiome of clinically healthy current and never smokers

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#27]
https://pubmed.ncbi.nlm.nih.gov/25012901/

**Comment by shallockh02** [comment]
I Kelvin Joseph can curate this

**Comment by shallockh02** [comment]
Hello I finished my curation [#27](https://bugsigdb.org/Study_461) ready for any corrections when I was filling the signatures some were not there and I crossed checked them via the NCBI link and included their txid is it the correct way?

**Comment by cmirzayi** [comment]
For reference: https://bugsigdb.org/Study_461

I will mark as ready for review.

**Comment by lwaldron** [comment]
Your method sounds correct @shallockh02

**Comment by shallockh02** [comment]
Has it been reviewed yet?

**Comment by shallockh02** [comment]
also, "Please work with your mentor to provide a timeline of the work you plan to accomplish on the project and what tasks you will finish at each step. Make sure take into account any time commitments you have during the Outreachy internship round. If you are still working on your contributions and need more time, you can leave this blank and edit your application later.
"

**Comment by claregri** [comment]
Hi @shallockh02 , great job, thanks so much for your curation. There were a few errors in the experiment, study design, and signature sections which we updated. Please review additional comments below as these notes will be helpful for any future curations that you work on.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 0 (this should be cross-sectional observational, not case-control)
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 0: You indicated that the testing was done with 16S sequencing, but did not indicate the variable regions of the gene. It should be V1-V9 (since the paper says V1-V3 and V7-V9). The sequencing platform is hard to find for this study but is Roche454
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 0
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 1
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 1
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 0 You wrote out "txid#####" when adding in NCBI taxon identifiers in the signatures, but the system cannot read them in this format. Enter the numbers only (#####) so that the database can update your entry

Total (maximum 24 points): 15

**Comment by cmirzayi** [comment]
@shallockh02 We are going to consider many aspects of each applicant including your contributions, scores, communications, etc. The score is only one small piece of this and a score of 15 is fairly good. Feel free to make changes to your curation which we will take into account.

**Comment by shallockh02** [comment]
@claregri tried to go through the curation based on the scores and corrections and confirmed the changes done to the curation are there still changes that need to be made to the curation?

**Comment by claregri** [comment]
Hi, I made the updates for you! thanks for checking in.

**Comment by shallockh02** [comment]
Thanks is there a way I can be of any help before the deadline passes for the contributions?
