### ISSUE TITLE
Types of tobacco consumption and the oral microbiome in the United Arab Emirates Healthy Future (UAEHFS) Pilot Study

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#28]
https://pubmed.ncbi.nlm.nih.gov/30054546/

**Comment by Abosed** [comment]
Please kindly assign

**Comment by cmirzayi** [comment]
Hi @Abosed. I appreciate your enthusiasm for curation! However, you have curated several articles already. We need a moment to review your work before we can assign another article. Thank you again for all your hard work. We are working on reviewing curations and we will get back to you soon.

**Comment by Abosed** [comment]
Thank you @cmirzayi

**Comment by mockingjay13** [comment]
I would like to get this article assigned to me for complete curation. Thank you!
Name: Aditi SIngh

**Comment by mockingjay13** [comment]
I have curated the assigned article; here's the link: https://bugsigdb.org/Study_678

Please review and let me know your feedback. Thank you!

**Comment by claregri** [comment]
Hi Aditi, you had a good start here! It looks like you didn't finish Experiment 5, so if you have a chance to do that it would be great! I also noticed that you didn't update the Group 1 name in experiment 4 (it should reflect that members of the group consume tobacco in multiple forms). Please note that the "Source" for the signatures should be Table 2, not Figure 4 - Figure 4 is not curatable by our standards because there is no measure of statistical significance (p or q value) denoted in it. Please go back and ensure that you are curating from Table 2.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 0 (though urine tests were administered, that's not where the differential abundance analysis came from. this should be saliva, since they had mouthwash samples)
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 1 - make sure to look for the variable region when you're curating 16S sequencing
10. Identified correct statistical test (1 point): 0 (this should have just been DESeq - papers often reference many statistical tests but you should look carefully to find the one that they're specifically using for the figure/table you're curating)
11. Identified MHT correction (1 point): 0 
12. Correctly recorded matched on factors (1 point): 0 (there was no matching of subjects in this study)
13. Entered correct number of statistical tests per experiment (1 point): 0
14. All diversity measures identified (1 point): 0
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 0
16. All signature sources correctly identified  (-1 for each error)  (2 points): not scored due to incorrect curation
17. Abundance direction correctly selected (1 point): not scored due to incorrect curation
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): not scored due to incorrect curation
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): not scored due to incorrect curation

Total (maximum 24 points): not scored

**Comment by mockingjay13** [comment]
> Hi Aditi, you had a good start here! It looks like you didn't finish Experiment 5, so if you have a chance to do that it would be great! I also noticed that you didn't update the Group 1 name in experiment 4 (it should reflect that members of the group consume tobacco in multiple forms). Please note that the "Source" for the signatures should be Table 2, not Figure 4 - Figure 4 is not curatable by our standards because there is no measure of statistical significance (p or q value) denoted in it. Please go back and ensure that you are curating from Table 2.
> 
> 1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
> 2. Correct study design (1 point): 1
> 3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
> 4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 0 (though urine tests were administered, that's not where the differential abundance analysis came from. this should be saliva, since they had mouthwash samples)
> 5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
> 6. Contrast groups correctly identified (1 point): 1
> 7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point): 1
> 8. Antibiotic exclusion correctly identified (1 point): 1
> 9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 1 - make sure to look for the variable region when you're curating 16S sequencing
> 10. Identified correct statistical test (1 point): 0 (this should have just been DESeq - papers often reference many statistical tests but you should look carefully to find the one that they're specifically using for the figure/table you're curating)
> 11. Identified MHT correction (1 point): 0
> 12. Correctly recorded matched on factors (1 point): 0 (there was no matching of subjects in this study)
> 13. Entered correct number of statistical tests per experiment (1 point): 0
> 14. All diversity measures identified (1 point): 0
> 15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 0
> 16. All signature sources correctly identified  (-1 for each error)  (2 points): not scored due to incorrect curation
> 17. Abundance direction correctly selected (1 point): not scored due to incorrect curation
> 18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): not scored due to incorrect curation
> 19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): not scored due to incorrect curation
> 
> Total (maximum 24 points): not scored

Hello @claregri, thank you for making out time and reviewing my curation. 
1. Per your instructions, I've now used Table 2 as the source for signatures and made the edits. 
2. I had confusion regarding experiment 5, as you mentioned, and asked the same to mentors too: The data for various diversities is provided for "Smokers" vs. "Non-smokers" but not for individual categories (Cigarettes, Dokha, Shisha) so to feed this, I created the "Experiment 5". 
quote: _"We found that microbial diversity (Shannon entropy) was marginally greater in all smokers compared with nonsmokers (p = 0.04, Fig. [2A](https://www.nature.com/articles/s41598-018-29730-x#Fig2)); however, this was not observed when comparing single tobacco type users to nonsmokers (Fig. [2B](https://www.nature.com/articles/s41598-018-29730-x#Fig2))_." 
But then, the signatures are not given for "Smokers" vs. "Non-Smokers" so I did not add any signatures, and thus Experiment 5 wasn't incomplete. Please let me know if there's a better way of presenting this information.
3. Also, I have added the "V4" Region in 16S Variable Region in all 5 experiments, but it is being displayed only in Experiment 1. This may be a technical issue. When I try to edit Experiments 2,3,4,5, it's already filled as "V4" but doesn't display the "16S Variable Region" as filled when I submit the form.
4. There's a genus "TG5" of the phylum "Synergistetes" which couldn't be identified, please let me know what could be done about this.
I'm sorry for the inconvenience caused to you. I'd request you to kindly review the study again with the edits. Looking forward to your feedback!

**Comment by claregri** [comment]
Hi Aditi,

Please see my responses to your questions below:
2. If there is alpha diversity info or experiments that do not have differential abundance information, you should just leave it out. I will delete Experiment 5 for you.
3. This is not an issue - that information doesn't show again past Experiment 1 when you're viewing the whole page for the paper, but as long as it's in each experiment form, no problem.
4. If you're not able to find it in the NCBI taxonomy/after a little googling, okay to leave it out. Please go ahead and remove where relevant.

You can find my updated review of your work below - nice job overall! I noticed some Table 2 taxa were missing (for example, in Experiment 1, proteobacteria should be increased in the controls). Also, make sure to curate the alpha diversity measure in the paper for each comparison. 

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 0 (should be saliva only)
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point):1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 0
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 0
16. All signature sources correctly identified  (-1 for each error)  (2 points): 2
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 0
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 2

Total (maximum 24 points): 18
