### ISSUE TITLE
Interaction between Cervical Microbiota and Host Gene Regulation in Caesarean Section Scar Diverticulum

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#281]
Interaction between Cervical Microbiota and Host Gene Regulation in Caesarean Section Scar Diverticulum – Xing Yang – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.01676-22

**Comment by eve10111** [comment]
Hello @SvetlanaUP ,  accepted,
Thank you very much.

**Comment by eve10111** [comment]
Hello @SvetlanaUP , my curation is ready for review. Here's the link to the file:https://bugsigdb.org/Study_987
Thank you very much

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

This curation is complete and ready for your review.
Thank you.

**Comment by SvetlanaUP** [comment]
Have you reviewed it or? @Scholarpat 
https://bugsigdb.org/Study_987

**Comment by Scholarpat** [comment]
Yes @SvetlanaUP, I reviewed it and made some corrections. I had a question though which you've answered on slack.
I've included a note like you suggested.

Also, I did notice that the **Revised curator** field is not showing another name. This is also similar to all curations I've been working on since Thursday. Could this be because of the update on BugSigDB?

**Comment by SvetlanaUP** [comment]
Ok, now it's clear :) and yes probably all the confusion is due to the bugsigdb update.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_987 is reviewed.
