### ISSUE TITLE
Increased rectal microbial richness is associated with the presence of colorectal adenomas in humans

### ISSUE THREAD

**Issue by Peacesandy** [waldronlab/BugSigDBcuration#290]
Increased rectal microbial richness is associated with the presence of colorectal adenomas in humans - Nina Sanapareddy et al. - ISME J

https://pubmed.ncbi.nlm.nih.gov/22622349/

**Comment by fetle1** [comment]
Can I curate this paper?

**Comment by omojokunoluwatomisin10** [comment]
can i be assigned to this @SvetlanaUP

**Comment by fetle1** [comment]
https://bugsigdb.org/Study_994 is ready for review @SvetlanaUP

**Comment by Omabekee** [comment]
This was a good attempt @fetle1. Unfortunately, you missed some basics. Here are some corrections to the errors you made, I've presented them as simply as I can. Please **implement all** and ask for help in the slack community where you're not sure.
**Corrections**
1. 16s region sequences is V1-V2
2. Alpha diversity: Cases have higher richness than controls (see figure 1), evenness (which should be shannon as indicated under the alpha diversity section) should be curated as unchanged.
3. Your group 0 should be control group (adenoma-free), while group 1 should be adenoma patients.
4. Additional experiments: Supplemental table S1 should be curated with Wilcoxon as the statistical test used. Ensure to enter **only statistically significant results** 
Please read the paper again to understand the group descriptions of this new experiment so that you can curate well.**

**CURATION RESULTS**

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
5. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
6. Condition entered according to contrast (correct EFO ontology) (1 point): 1
7. Contrast groups correctly identified (1 point): 1
8. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 0
9. Antibiotic exclusion correctly identified (1 point): 1
10. Correctly identified sequencing details (2 points): 1
11. Identified correct statistical test (1 point): 1
12. Identified MHT correction (1 point): 1
13. Correctly recorded matched on factors (1 point): 1
14. Entered correct number of statistical tests per experiment (1 point): 0
15. All diversity measures identified (1 point): 0.5
16. Diversity results correctly entered as increased/decreased/unchanged (1 point): 0.5
17. All signature sources correctly identified (-1 for each error) (2 points): 0
18. Abundance direction correctly selected (1 point): 0
19. Members of Signatures identified correctly (2 points): 0
20. Correct use of NCBI taxonomy (2 points): 0

Total = 12
@SvetlanaUP, grading of Study 994 complete. ✅ Review still in progress

**Comment by fetle1** [comment]
Okay, thank you for the feedback I will correct them immediately

**Comment by Rahila-me** [comment]
@fetle1 Good morning, I want to know if you have effected the correction or do you need collaboration on that if so, let me so we finish it up together. Thank you

**Comment by SvetlanaUP** [comment]
@Rahila-me @fetle1 please do collaborate in finalizing corrections of this curation.

**Comment by Rahila-me** [comment]
@SvetlanaUP  OK , but should i wait for go ahead from @fetle1 before completing the review

**Comment by SvetlanaUP** [comment]
@Rahila-me Please do try to contact @fetle1 via slack (fetlework gubena arage) as well. If there's no response by tomorrow, continue corrections.

**Comment by Rahila-me** [comment]
OK. I have reached out to her on slack, waiting for her reply

**Comment by Rahila-me** [comment]
@SvetlanaUP Good morning, It has been 2 days since i reached out to @fetle1 on slack she has not gotten back to me.

**Comment by fetle1** [comment]
Hello @SvetlanaUP  and @Rahila-me sorry for the late reply and making the work slowdown. There is some internal conflict going on in our region and the government has shutdown the connection close to a month now with only a few places with a connection. Please go a head and edit the curation I will try to help with anything you need when I access the internet again.

**Comment by SvetlanaUP** [comment]
@fetle1 no worries! Thank you for your reply.

**Comment by Isioma20** [comment]
Hi @Rahila-me. I would love to collaborate in finalising  the corrections of this curation? I have sent you a message on slack

**Comment by Rahila-me** [comment]
@Isioma20, I am already effecting the correction.

**Comment by Scholarpat** [comment]
@Rahila-me I noticed the changes have not been effected yet. I'm open to collaborate with you and @Isioma20 to complete this...

**Comment by Isioma20** [comment]
Hey @Scholarpat. I'm still waiting on a positive response for collaboration . Would love to work together.

**Comment by Isioma20** [comment]
Hi @Rahila-me. I noticed the corrections to this study have not been effected yet and I haven't gotten a favourable response from you. Can @Scholarpat and I go ahead to correct this curation?

**Comment by Rahila-me** [comment]
Guys i am still working on it ooh, once i am done correcting the experiment
then i will create the signature

**Comment by Scholarpat** [comment]
Noted @Rahila-me

**Comment by Rahila-me** [comment]
@Isioma20 @Scholarpat here: https://bugsigdb.org/Study_994, You can go through it and add correction if you find any. Thank you

**Comment by SvetlanaUP** [comment]
@Scholarpat what's the status of this study? Thanks.

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP,

@Isioma20 and I went through it together and we are of the opinion that there are still a couple of significant taxa that were not curated. So we'll be adding those and put it up for a second review soon. We agreed that the rest of the curation by @Rahila was well done.

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP , 
Please kindly delete Signature 2 (exp. 1) of this curation. It was entered in error.
Other than that, the curation is ready for a second review.

Thank you!

**Comment by Omabekee** [comment]
@SvetlanaUP 2nd review complete. ✅ This issue can now be closed. Thank you.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_994 reviewed.

**Comment by Fificode** [comment]
Hi @SvetlanaUP,
I am currently resolving missing NCBI Taxonomy IDs and noticed that Experiment 1, Signature 1 contains the taxon "TM7." https://bugsigdb.org/22622349/Experiment_1/Signature_1
I would like to update it to "Candidatus Saccharimonadota, Taxonomy ID: 95818" as this appears to be the currently accepted taxonomy. Please let me know if you have any concerns with making this change. 

Thank you!

**Comment by SvetlanaUP** [comment]
Agree.
Source: https://pmc.ncbi.nlm.nih.gov/articles/PMC6481004/
