### ISSUE TITLE
Subgingival microbiome in smokers and non-smokers in Korean chronic periodontitis patients

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#30]
https://pubmed.ncbi.nlm.nih.gov/25283067/

**Comment by atrayees** [comment]
Hello! I would like to work on this topic, could you please assign it to me?
Atrayee Samanta

**Comment by atrayees** [comment]
Hello, I am done with the second review, could you please provide me with a feedback? Here is the link to my second contribution: https://bugsigdb.org/Study_754

**Comment by ftzohra22** [comment]
Thank you @atrayees.

**Comment by ftzohra22** [comment]
@atrayees Good effort on this paper. Here's your feedback, please revise and make the changes. We need to make sure we only curate signatures that are differentially abundant. This paper was a tricky one and looks like there aren't any differential abundance testing done. All the results they reported here are relative abundance results not differential abundance.In cases like this it is okay to not enter any signatures and curate the rest of the results (till diversity). Another thing to look out for is if the results mention statistically significant difference in microbiome, only then we curate those figures/tables. 

1. All elements marked "Needs review" (none "Incomplete") (1 point):  1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point): 0 (number of samples incorrect)
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 0 (variable region and sequencing platform missing)
10. Identified correct statistical test (1 point): 0
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 0 (matched on factors missing)
13. Entered correct number of statistical tests per experiment (1 point): 0
14. All diversity measures identified (1 point): 0 (the diversity measures they used are shannon, simpson and richness)
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point):
16. All signature sources correctly identified  (-1 for each error)  (2 points): 0 
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): Not scored
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): Not scored

Total (maximum 24 points): Not scored due to incorrect curation

**Comment by atrayees** [comment]
Thank you so much for the feedback, @ftzohra22 ! I have corrected the mistakes, but I still have a 2 doubts:
1. The number of samples in both groups 0 as well as 1 are 134 according to the study, and that was what I had mentioned in the curation too- 134 samples were collected from 57 group 1 people, and 134 from 36 group 0 people. I just wanted to clarify, the sample size will then be the number of people and not the number of dental tooth samples used, right?
2. There are statistical tests, but those were not available in the curation options
3.  I tried deleting the signatures, but the permission to delete the signatures was only for the administrators, so I could not remove the signatures for the relative abundances.

I'm so sorry for the mistakes, thank you so much for clearing them

**Comment by lwaldron** [comment]
I actually agree with @atrayees that these _are_ differential abundance results: Figure 2 and related text in the Results report differentially abundant taxa with a fold-change cutoff of 1.5. Note, I also remove Significance threshold (since no p-values were used), added Data transformation: relative abundances, Added Roche 454 sequencing (the brand of sequencing that does pyrosequencing), and removed Faith Alpha Diversity since I couldn't find reference to it in the manuscript (although correct me if I'm wrong). 

To save you some time, would you combine the signatures of phylum, genus, species, and <1% / >1% into signatures 1 & 2 before I delete signatures 3+?

1. All elements marked "Needs review" (none "Incomplete") (1 point):  1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 0 (in Experiment 1 the condition is listed as “periodontitis” for a contrast of smokers vs non-smokers. Condition should refer to the condition that was contrasted between group 0 and 1, not one that was shared by everyone.)
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2 (did not deduct for missing Roche454 since it was instead called "Pyrosequencing", but should check into something like this.
10. Identified correct statistical test (1 point): 1 (did not deduct because Fold-change threshold was not among options, but it is now).
11. Identified MHT correction (1 point): 1 (N/A)
12. Correctly recorded matched on factors (1 point): 0 (the experiment matched on age and sex, but not others - it would be impossible to match on tobacco exposure since tobacco exposure is the difference between cases and controls)
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 0 (listed Faith, but Faith isn't mentioned in the paper?)
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 2 (not deducting for splitting across multiple signatures because of conflicting direction given in the first review) 
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 2 (although these still need to be consolidated into fewer signatures: <1% and >1%, phylum, genus, and species results all belong together in the same signature)
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 2

Total (maximum 24 points): 19

**Comment by lwaldron** [comment]
Apologies, this was actually 20 out of 23. I created a more easily readable scoring template below. Note, the only remaining work needing to be done on this study is combining the signatures into one increased and one decreased.

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 |1  |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 0 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 |1  |
| 9 | Correctly identified sequencing details | 2 |2  |
| 10 | Identified correct statistical test | 1 |1  |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 0 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 0 |
| 15 | Diversity results correctly entered as increased/ decreased/ unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 |2  |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 2 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 20 |

Footnotes

- 9: 1 point for sequencing type and variable region, 1 point for sequencing platform
- 18: 1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon
- 19: don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors

**Comment by atrayees** [comment]
Thank you, @lwaldron , also I have made the necessary changes in Signatures 1 and 2 by adding all the required taxa !
