### ISSUE TITLE
Gut dysbiosis induces the development of depression-like behavior through abnormal synapse pruning in microglia-mediated by complement C3

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#306]
Gut dysbiosis induces the development of depression-like behavior through abnormal synapse pruning in microglia-mediated by complement C3 – Wenzhi Hao – Microbiome

**Comment by AleruDivine** [comment]
Aleru Divine
Hi @SvetlanaUP, I'd like to claim this article for curation.

I found the link to the paper: https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-024-01756-6#

**Comment by AleruDivine** [comment]
Good evening @SvetlanaUP! I have completed the curation of this paper. I found this one particularly interesting because of the different experiments that they performed on the rats😅 It was a really interesting read.

I would like to put it up for review.

Link to study: https://bugsigdb.org/Study_1047

🥲 Unfortunately, there aren't any more papers available for curation at the moment. However, I'm committed to finding other meaningful ways to contribute.

**Comment by AleruDivine** [comment]
Hello @SvetlanaUP @cmirzayi , I found this study and another [study](https://bugsigdb.org/Study_888) completed by me on [Incomplete pages (marked as incomplete by curator)](https://bugsigdb.org/Special:Ask/-5B-5BState::Incomplete-5D-5D/mainlabel%3D/offset%3D0/format%3Dol/searchlabel%3DIncomplete-20pages-20(marked-20as-20incomplete-20by-20curator)) and I noticed that they were both from my earlier contributions (March-May). After reviewing them, I identified the mistakes in each and would appreciate the opportunity to make corrections.

For this [study](https://bugsigdb.org/Study_1047):
- I had done a pairwise comparison instead of a one-to-all experiments. 
- There should be a total of 6 experiments in this study, with the first 4 only including increased signatures due to the one-to-all comparison, rather than the 10 experiments I had initially curated.
- I missed some signatures from Additional file 6: Supplement Fig. 2. (microbial taxa at phylum level).

For this [study](https://bugsigdb.org/Study_888):
- There are more signatures to curate from the supplementary table 2, containing results on the differential abundance of families.

I sincerely apologize for the oversights, and I’d be really grateful for the opportunity to correct these studies and review my other unreviewed contributions from May for similar issues. I feel that I have a stronger grasp of the curation process now and I can better address these mistakes if given the chance to.

Thank you so much!🙏

**Comment by SvetlanaUP** [comment]
@AleruDivine Great catch! Please do all corrections. Misinterpretation of the LefSe one to all comparison caused many duplicated signatures (not only in your curations), and we should correct them. Thanks!

**Comment by AleruDivine** [comment]
Thank you so much for the approval @SvetlanaUP I’ll make changes and report back when this is ready.

**Comment by AleruDivine** [comment]
Hi @SvetlanaUP this study is ready for review (again😅).

**I made the following corrections:**

1. I corrected the conditions to be more specific to each experiment.
2. I also corrected the sequencing platform to Illumina, following the instruction provided under **Availability of data and materials**. (I had left it blank before).
4. Experiments 1 - 4 have been corrected to one-to-all experiments following the differential abundance results in figure 4f instead of the pairwise comparison that I had done previously
5. Experiments 5-7 are from the differential abundance resuts in figure 8(g-k).
6. Experiments 8 - 10 are the same comparisons from experiments 5-7, but I curated differently because of the statistical test used (Pearson's correlation) and there were additional signatures identified. 
7. All differentially abundant signatures have been curated.

I did not curate figure 4(g-i), because it will be a repetition of what has already been curated.

1. Bacteroides and Klebsiella were increased in CUMS group when compared to the control and intervention (XYS and FLX) groups. This is already evident in the one-to-all comparison in experiment 2. 
2. Lactobacillus was decreased in the CUMS group but increased in the XYS intervention group. This also evident in the one-to-all comparison in experiment 4. 

What is left for this study is to confirm the data transformation for Pearson's correlation.

Thank you so much!

**Comment by SvetlanaUP** [comment]
@KateRasheed https://github.com/KateRasheed could you please review this paper, next week?

**Comment by KateRasheed** [comment]
Yes please, I would review it. Thank you so much @SvetlanaUP

**Comment by KateRasheed** [comment]
Good morning @AleruDivine . Well done on this great curation. Here are a few things I would like you to look into:

Please use this full names in experiment 1 group names:
**chronic unpredictable mild stress (CUMS)
Xiaoyaosan (XYS)
CUMS + fluoxetine (FLX)**

Also, I believe you used control group as group 1 because it is a one-against-the-rest analysis. However, I believe it would be great to have the control group as Group 0, while the experimental groups should be group 1. This would mean changing the group names and the abundance direction.

Figure 4G-I should be curated separately as a pairwise comparison with Mann-whitney as the statistical test. See this: “a non-parametric test of K-independent samples was used for item-by-item statistical analysis.” and from Google search, Kruskal-Wallis is a non-parametric test.

For OP9 in experiment 3, OP9 phylum is known as Atribacterota as seen in this [article](https://pmc.ncbi.nlm.nih.gov/articles/PMC7782747/).

For experiment 9, _Faecalibacterium_ is having the same shade of green on both groups, I believe there was no increase/decrease. This is also repeated in experiment 10 for _Other(Unidentified)_.

**Comment by AleruDivine** [comment]
Good morning @KateRasheed I corrected the following:
1. Corrected the full names in experiment 1 group names.
2. Corrected the OP9 phylum to [Atribacterota](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Tree&id=67818&lvl=3&keep=1&srchmode=1&unlock)
3. Updated the data transformation for Peasrson's correlation.

For your second suggestion, I wanted to clarify that I curated the control group as Group 1 because of the way the signatures were reported in the paper (One-vs-all). Also, during one of the office hours, Chloe mentioned that in a one-against-all comparison, the group being compared against the others (in this case, the control group) should be labeled as Group 1. That’s why I curated this way.

For your suggestion regarding Faecalibacterium, the shades of green are slightly different. For FMTXYS, it is a darker shade (further down the negative line, indicating a decrease) **Color code = D2E9EC**, while for the CUMS group, it is lighter **Color code = D9EAED**, meaning it is increased for the CUMS group. That’s why I curated it as a decreased signature.

If the shades had been the same, I would have curated it as both increased and decreased. Since it’s at the genus level (Faecalibacterium), this would imply they were different species or strains.

I have also curated the additional experiments for the comparisons in Figure 4(g-i).

Please review again and let me know if I missed anything.
Thank you so much!

**Comment by KateRasheed** [comment]
Thank you for implementing the corrections. For the color shades, I had to zoom in to check out the difference in the shade for Faecalibacterium and Others and still couldn't see it. It's fine to leave it that way.

Can you point me to where you got the color codes @AleruDivine 

@SvetlanaUP This study has been reviewed.

**Comment by AleruDivine** [comment]
@KateRasheed I was able to tell the difference at a glance because I’ve had to deal with a lot of colors as a UI designer, but I added the codes for you to see the difference. 

There’s a color code extension called **colorpick eyedropper** you can install and check it out but I used figma in this case. 

Oh I forgot the screenshots

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1047 reviewed.
