### ISSUE TITLE
Sex, health status and habitat alter the community composition and assembly processes of symbiotic bacteria in captive frogs

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#314]
Sex, health status and habitat alter the community composition and assembly processes of symbiotic bacteria in captive frogs – Senlin Liu – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-023-03150-y

**Comment by Isioma20** [comment]
Can I be assigned to this issue. My previous assignment already exist on BugSigDB. Thank you.

**Comment by Isioma20** [comment]
Thank you!

**Comment by Isioma20** [comment]
Hello. This curation is ready for review.
https://bugsigdb.org/Study_1019

Thank you!

**Comment by Scholarpat** [comment]
Hello @Isioma20,

Well done on your curation. I noticed a few points that I would appreciate clarification on when you are free:

- **Study Design:** I noticed you opted for a cross-sectional design rather than a laboratory experiment. Could you please elaborate on this choice?

- **Figure 3a:** I observed that you curated some but not all the taxa mentioned in this figure for experiment 1. Although the text mentioned only the taxa that were curated, the figure indicated that the others were significant (marked with asterisks) as well:
Tumebacillus - decreased in females
Candidatus - increased in females

I look forward to hearing your thoughts on these points.

Thank you very much.

**Comment by Isioma20** [comment]
Hi @Scholarpat. Thank you for the review. These are my thoughts on the points you raised;
1. I had opted for a cross sectional study design because the frogs used in this experiment weren't put under any laboratory conditions. They were taken from their natural habitat and the experiment was conducted immediately without any alterations to any living conditions.
2. I didn't curate all the taxa in the figure because at the time, I could not decipher  if they were increase or decrease in the Group 1 as they didn't have any color coding as the rest of the taxa in the figure, hence I only curated those that were clearly increase or decrease in Group 1. But if you can decipher them then please add them to the duration. Thank you for your careful review. I appreciate your thoughts

**Comment by Scholarpat** [comment]
Hi @Isioma20,

Thank you for your response. I understand better now. I've added the two taxa.

**Comment by Scholarpat** [comment]
The curation is complete @SvetlanaUP.
Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1019 reviewed.
