### ISSUE TITLE
Correlation of gut microbiota with leukopenia after chemotherapy in patients with colorectal cancer

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#317]
Correlation of gut microbiota with leukopenia after chemotherapy in patients with colorectal cancer – Ni Xiaofeng – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-023-03067-6

**Comment by Nana-Habiba** [comment]
@SvetlanaUP May i curate this paper.
My first curation is marked review: https://bugsigdb.org/Study_932

**Comment by Nana-Habiba** [comment]
@SvetlanaUP can you take a second look at this paper, please unassigned me from it. i have gone through it, no statistical test and some crucial information for curation are missing.
![no test](https://github.com/waldronlab/BugSigDBcuration/assets/156927713/2cb604bc-8a99-456c-8b55-951ab4f339bd)

**Comment by SvetlanaUP** [comment]
@Nana-Habiba please go thoroughly through the paper, there is a clear presentation of the differential abundance results.

**Comment by Nana-Habiba** [comment]
@SvetlanaUP @cmirzayi My second curation ready for review:
https://bugsigdb.org/Study_1027

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Here are the changes I made to this curation:

- Added sequencing platform details for both experiments.

- Edited the statistical test field to only include LEfSe, removing Kruskal Wallis (both were initially curated).

- Altered source description for both experiments.

- Curated signature 2 for experiment 1.

- Changed the condition for experiment 2 from "colorectal carcinoma" to "leukopenia" because CRC patients were subdivided into hypoleukocytes and normal leukocytes groups for comparison.

- In signature 1 of experiment 2, changed "Eggerthella" to "Eggerthia," as originally reported.

- In signature 2 of experiment 2, changed "Ruminococcus torques group" to "[Ruminococcus] torques" to resolve the taxa.

This curation is complete.

Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1027 reviewed.
