### ISSUE TITLE
Analyzing lung cancer risks in patients with impaired pulmonary function through characterization of gut microbiome and metabolites

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#337]
Analyzing lung cancer risks in patients with impaired pulmonary function through characterization of gut microbiome and metabolites – Jiahui Luan – BMC Pulmonary Medicine
https://bmcpulmmed.biomedcentral.com/articles/10.1186/s12890-023-02825-6

**Comment by omojokunoluwatomisin10** [comment]
can i be assigned to this study

**Comment by omojokunoluwatomisin10** [comment]
i need review of the study. Thanks

**Comment by SvetlanaUP** [comment]
Ready for review. https://bugsigdb.org/Study_1051

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

I've made a few changes to this curation:

- Changed the study design from case-control to cross-sectional.

- Updated the condition to only reflect the condition of interest.

- Revised the signature description and curated the missing taxa.

- Fig. 4C was not curated because the comparison between groups was not clearly reported in the study. I've included a note on the talk page to this effect.

- Experiments 2, 3, and 4 (including signature 1 of exp. 4), initially curated, are not significant. Please kindly delete these. This study only has one curatable experiment.

Thank you very much.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1051 reviewed.
