### ISSUE TITLE
Differential Microbial Signature Associated With Benign Prostatic Hyperplasia and Prostate Cancer

### ISSUE THREAD

**Issue by Nana-Habiba** [waldronlab/BugSigDBcuration#340]
Differential Microbial Signature Associated With Benign Prostatic Hyperplasia and Prostate Cancer - Sarkar P - frontiers
https://www.frontiersin.org/articles/10.3389/fcimb.2022.894777/full

**Comment by Nana-Habiba** [comment]
@SvetlanaUP @cmirzayi Please i created this issue and i have also curated it. Please assign it to me and also make it as needs review. 
Here is Link: https://bugsigdb.org/Study_893

**Comment by SvetlanaUP** [comment]
Noted as a self-assigned curation.

**Comment by Scholarpat** [comment]
Hi Nana,

Well done on your curation. @Buraah and I reviewed and made a few changes:

1. Changed the study design from prospective to cross-sectional because participants were not followed up over time, which is a key characteristic of a prospective study.

2. In the study, samples were collected into two cohorts: Cohort-1 (Discovery Cohort) and Cohort-2 (Validation Cohort) but Cohort 2 was used to validate the sequencing data. Signatures were not reported separately for each cohort.

3. Supplementary Figure 1E was initially curated for experiment 1 and Figure 2D for experiment 2. However, I merged these into one experiment because signatures from both figures were reported for one experiment but at different taxonomic levels based on these excerpts:
   - "To identify the differentially enriched **genera** within BPH and PCa samples, we employed Linear Discrimination Analysis (LDA) Effect Size (LEfSe) method (Figure S1E)."
   - "Next, cladogram and LEfSe analyses were conducted to further uncover the differential **species** compositions between BPH and PCa tissue biopsy samples (Figures 2C, D)."

Please @SvetlanaUP, kindly delete experiment 2.

This curation is ready for your review.

Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_893 reviewed.
