### ISSUE TITLE
Alterations in the Gut Microbiome of Young Children with Airway Allergic Disease Revealed by Next-Generation Sequencing

### ISSUE THREAD

**Issue by Rahila-me** [waldronlab/BugSigDBcuration#342]
Alterations in the Gut Microbiome of Young Children with Airway Allergic Disease Revealed by Next-Generation Sequencing - Wan J - Dovepress
https://www.dovepress.com/alterations-in-the-gut-microbiome-of-young-children-with-airway-allerg-peer-reviewed-fulltext-article-JAA

**Comment by Rahila-me** [comment]
@SvetlanaUP @Omabekee Please assign this paper to me and mark as needs review
Link: https://bugsigdb.org/Study_901

**Comment by SvetlanaUP** [comment]
Notes as a self-assigned curation.

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

This curation has been reviewed. Here are the changes I made:

1. **Study design**: Changed from cross-sectional to case-control. This is because the functional and compositional features of the intestine between allergic patients and healthy individuals were compared.

2. **Condition**: Changed from atopic asthma to allergic asthma in experiment 1.

3. I've also curated the signatures that were missing.

P.S. Signature 2 of experiment 1 is not displaying but has been curated. I've added this report with the others.

Please kindly delete Experiment 3. Thank you very much!

**Comment by SvetlanaUP** [comment]
Thanks @Scholarpat!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_901 reviewed.
