### ISSUE TITLE
Dermal injury drives a skin to gut axis that disrupts the intestinal microbiome and intestinal immune homeostasis in mice

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#347]
Dermal injury drives a skin to gut axis that disrupts the intestinal microbiome and intestinal immune homeostasis in mice – Tatsuya Dokoshi – Nature Communications
https://www.nature.com/articles/s41467-024-47072-3

**Comment by RotimiDesire** [comment]
Hi @SvetlanaUP 

May I?

**Comment by SvetlanaUP** [comment]
Hi @RotimiDesire,
right now we are focused on **closing open issues**:
We encourage you to check if reviewed issues are corrected in bugsigdb, if not corrected you can make correction and/or support the main curator to correct their curation. 
Thank you!

**Comment by RotimiDesire** [comment]
Alright, thank you.

**Comment by Isioma20** [comment]
Hello @SvetlanaUP. I would like to curate this paper. Thank you!

**Comment by Scholarpat** [comment]
Hello @Isioma20 

Hope you're doing well. I noticed this study is not yet available on BugSigDB. Do you need help with the curation?

Kindly awaiting your response.

Best Regards
Scholastica Urua

**Comment by Isioma20** [comment]
Hi @Scholarpat would message you on slack. Thanks

**Comment by SvetlanaUP** [comment]
Hi @Isioma20, what's the status of this curation? Thanks!

**Comment by Isioma20** [comment]
Hi @SvetlanaUP. Unfortunately I haven't worked on this study so it has not yet been curated on BugSigDB. Thank you!

**Comment by SvetlanaUP** [comment]
No problem @Isioma20 :) we can offer it to other curators or you prefer to do it?

**Comment by Isioma20** [comment]
Hi @SvetlanaUP. My apologies for the late response. Please I'd love to open it to other curators as I'd be unable to complete it myself. Thank you!

**Comment by codeX-111** [comment]
Hello, Good day @SvetlanaUP, Please this article is ready for review 

https://bugsigdb.org/Study_1200

Thanks

**Comment by KateRasheed** [comment]
Good morning @codeX-111 . Great job on this curation. I would like you to make some adjustments on this curation:

Please change Anaerotruncus sp. to Anaerotruncus sp. G3 which has the tax. id "397284". Please do the same for Dorea sp. 5-3 - 1235798, Lachnospiraceae bacterium 3-1 - 397288, Lachnospiraceae bacterium 3-2 - 1235799, Oscillibacter sp. 1-3 - 1235797

The mice were matched on age and sex.

The study design is laboratory experiment because the mice were experiment conducted in a laboratory.

There's an additional experiment done after skin wounding. You would find the signatures in Supplementary Figure 7. The statistical test here is T-test. The sample size is 5 per group.


PS. Please let me know if you would need my assistance in correcting the study.  Thank you so much.

**Comment by SvetlanaUP** [comment]
@KateRasheed just a comment on "the mice were experiment conducted in a laboratory."
To be more precise, mice are model organisms used in experiments in a laboratory within this study.
As they are germ-free or specific pathogen-free, this might allow mice to more accurately model human disease and hence produce more applicable findings.

**Comment by KateRasheed** [comment]
Thank you so much for this explanation @SvetlanaUP . It is well noted.

**Comment by KateRasheed** [comment]
Good afternoon @SvetlanaUP . All corrections have been made on this study. Thank you so much.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1200 reviewed.
