### ISSUE TITLE
Oral Microbiome Alterations and SARS-CoV-2 Saliva Viral Load in Patients with COVID-19

### ISSUE THREAD

**Issue by AleruDivine** [waldronlab/BugSigDBcuration#355]
Oral Microbiome Alterations and SARS-CoV-2 Saliva Viral Load in Patients with COVID-19
https://journals.asm.org/doi/10.1128/spectrum.00055-21

**Comment by MyleeeA** [comment]
Thank you for adding this I'm interested in going through this

Can I be assigned this @SvetlanaUP

**Comment by MyleeeA** [comment]
Thank you @SvetlanaUP

**Comment by MyleeeA** [comment]
Hi @SvetlanaUP 

can I request to be assigned to another article while we await response for this study https://bugsigdb.org/Study_1031

**Comment by SvetlanaUP** [comment]
Hi @MyleeeA, the authors just send their supplementary material. Please finalize this curation. Thank you!
[Supplemental Information_Spectrum_revision_final_20210810.pdf](https://github.com/waldronlab/BugSigDBcuration/files/15197051/Supplemental.Information_Spectrum_revision_final_20210810.pdf)

**Comment by MyleeeA** [comment]
Okay @SvetlanaUP 
Thank you

**Comment by MyleeeA** [comment]
@SvetlanaUP 
This curation is ready for review 
https://bugsigdb.org/Study_1031

**Comment by Scholarpat** [comment]
Hi @MyleeeA,

Well done on your curation. I made a couple of observations:

1. **Study Design**: A case-control design seems better suited than a cross-sectional design because the study "aimed to elucidate the relationship between saliva microbiota and SARS-CoV-2 in a cohort of newly hospitalized COVID-19 patients and controls." The COVID-19 patients were then categorized based on saliva viral load.

2. **Antibiotic Exclusion**: There is no antibiotic exclusion. From this excerpt: "Compared to controls, COVID-19 patients had similar rates of receipt of antibiotics within 48 h of admission (P = 0.62) but were more likely to receive supplemental oxygen (P = 0.03), primarily via nasal cannula (30.2% of COVID-19 patients)," receipt of antibiotics within 48 hours of admission was part of the patients' information and not an exclusion criterion. Patients were excluded if they were intubated, otherwise medically unstable or unconscious, or admitted to an intensive care setting. Hospitalized patients with a nasopharyngeal swab negative for SARS-CoV-2 but with a history of prior COVID-19 disease were also excluded.

3. **Data Transformation**: Based on the statistical test used, raw counts should be better curated instead of relative abundance.

4. **Alpha Diversity**: The Shannon (Fig. 1A & 2A) and Chao (supp. fig S1) indices were used, not Shannon and Richness.

5. **Signature**: Streptococcus spp., which was reported, can be curated as Streptococcus sp., which is available on BugSigDB. The study also reported some signatures with numbers added to them. For example, "**Alloprevotella sp. HMT 473**" is a specific strain and different from Alloprevotella sp., so it should be curated as reported in the study. I did some research and found that **_"HMT (Human Microbial Taxon) replaces the old HOMD (Human Oral Microbiome Database) taxonomy prefix HOT (human oral taxon)"_** so I believe this can be curated as **"Alloprevotella sp. oral taxon 473"** which is available on BugSigDB. This also applies to other taxa reported this way in the study.

I have effected these changes and would love to hear your thoughts on these points.

Thank you so much!

**Comment by MyleeeA** [comment]
Thank you for your corrections and observations @Scholarpat 

Your observations are really straightforward and I agree with you
Well done and Thank you 😊 
PS: The little details we miss are really important, thank you again

**Comment by Scholarpat** [comment]
Thank you @MyleeeA 😊

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1031 reviewed.
