### ISSUE TITLE
Oral Fungal Alterations in Patients with COVID-19 and Recovered Patients

### ISSUE THREAD

**Issue by AleruDivine** [waldronlab/BugSigDBcuration#357]
Oral Fungal Alterations in Patients with COVID-19 and Recovered Patients
https://onlinelibrary.wiley.com/doi/full/10.1002/advs.202205058

**Comment by AleruDivine** [comment]
I found this paper interesting because it explores the oral fungal microbiota in COVID-19 patients and those who have recovered. This offers a fresh perspective because it sheds light on an area I had not previously explored.

**Comment by Buraah** [comment]
Hi @SvetlanaUP , @AleruDivine 
I'd love to curate this paper...Please assign it to me. Thank you

Victoria.

**Comment by Buraah** [comment]
Hi @SvetlanaUP 
I am done curating this study and it's ready for a first review.
Link to study: https://bugsigdb.org/Study_940

**Comment by AleruDivine** [comment]
I'd like to review this study @SvetlanaUP.
Thank you so much!

**Comment by AleruDivine** [comment]
Thank you so much @SvetlanaUP 😊

**Comment by AleruDivine** [comment]
Well done on your curation! 👏👏 @Buraah! You have done a great job with this.

I have a few observations and suggestions that I'd like you to consider:

**Phenotype Studied:**

- It seems that the experimental condition or phenotype being studied is the [oral microbiome](https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0801229), specifically in the context of COVID-19, rather than COVID-19 itself. The paper indicates an interest in understanding how the composition of fungal microorganisms in the oral cavity differs between individuals with and without COVID-19.

**Antibiotic Exclusion:**

- The paper states that the controls had not taken antibiotics in the past 8 weeks. Could this be considered as antibiotic exclusion? I have raised this question on Slack and am awaiting responses from the mentors.

**Signature 1 in Experiment 1:**

- Signature 1 in Experiment 1 is missing a fungi: [Fantasmomyces](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Tree&id=1932873&lvl=3&keep=1&srchmode=1&unlock).

**Signature 1 in Experiment 3:**

- I believe that Signature 1 in Experiment 3 should indicate increased abundance in the post-COVID-19 group.

**Supplemental Material - Figure S4:**

- While reviewing the supplemental material, I noticed Figure S4 (titled "The characterization of oral fungi among COVID-19-N, COVID-19-C, and control groups") can be curated. The paper states: "The 71 COVID-19 patients from Henan were divided into COVID-19 patients without comorbidities (COVID-19-N, n = 56) and COVID-19 patients with comorbidities (COVID-19-C, n = 15). Then we analyzed the oral fungal characteristics of COVID-19-N, COVID-19-C, and control (n = 132) groups." I believe this information should be included in the study as Figure S4 provides relevant data.

I hope my suggestions are helpful. I am very open to hearing your thoughts on them.

Thank you so much.

**Comment by SvetlanaUP** [comment]
Thanks @AleruDivine! I agree with all the point.

As for Antibiotic exclusion: Yes, it should be reported, with a note. That's not surprising, since it can be challenging to recruit "non-healthy" participants without any recent antibiotic treatment.

@Buraah can you correct your curation for details mentioned above?

**Comment by Buraah** [comment]
Thank you for your review @AleruDivine 
I'll indicate here when I'm done making corrections.

**Comment by Buraah** [comment]
Hi @AleruDivine, Thank you again for your review.
I agree with the condition and antibiotic exclusion.
I totally missed supplemental figure 4S while curating initially, even after the peer review.

For the signatures in experiment 3 signature 1, I recorded them as decreased because of this text from the first paragraph of the Discussion section: _After the first specimen was collected at the time of admission, some Post‐COVID‐19 patients received antibiotic therapy. The results of the analysis showed that the oral fungal diversity of the recovered patients was significantly lower than that of the control group, and the oral bacterial diversity gradually returned to normal, indicating that fungi require a longer recovery time than bacteria._
I thought it was a valid reason for the decision.

I've made corrections, but there's an issue. The new experiments I added are not showing.
I've reported this here: https://github.com/waldronlab/BugSigDB/issues/221
It looks like someone is checking it out too.

To help you review, I will link each of the 3 experiments I just added.
Experiment 4: https://bugsigdb.org/Study_940/Experiment_4
Experiment 5: https://bugsigdb.org/Study_940/Experiment_5
Experiment 6: https://bugsigdb.org/Study_940/Experiment_6

**Comment by SvetlanaUP** [comment]
@AleruDivine @Buraah great job, thanks! https://bugsigdb.org/Study_940

**Comment by SvetlanaUP** [comment]
@Buraah ha, here it is https://bugsigdb.org/Study_940
please correct the condition ;)

**Comment by Buraah** [comment]
Yes😀Doing that now.

**Comment by Buraah** [comment]
Done... @SvetlanaUP

**Comment by AleruDivine** [comment]
Good afternoon @SvetlanaUP, I hope you're doing well.

Following last week's office hours session, I reviewed some of the studies marked as incomplete by Chloe and noticed repeated signatures in experiments designed to be "one-against-all" rather than pairwise comparisons. I’d like to take on the task of cleaning up these studies, starting with this one and then proceeding to others.

For each study, I will highlight the signatures to delete in the corresponding GitHub issues for clarity.

Would it be okay for me to take on this task? 

Thank you so much!

**Comment by SvetlanaUP** [comment]
@AleruDivine great suggestion! Please just note everything as you are changing/correcting. Thank you!

**Comment by AleruDivine** [comment]
Thank you so much @SvetlanaUP 
I'll get started and make sure to note the changes.

**Comment by AleruDivine** [comment]
Good evening @SvetlanaUP 
I did a review and made corrections on this study and here are the changes I made:

1. Experiments 1 - 3 has been corrected to a one-to-all comparison following the differential abundance results from figure 4G. Sample sizes for both contrast groups and the group description for group 1 has been updated also.
2. The alpha diversities have been corrected for experiments 1-3 (now blank) since they did not measure for one-to-all comparisons.
3. An additional experiment (7) for Figure 1 (comparison between 48 patients with COVID-19 and 88 controls from the train phase) has been added.
4. I also added 3 additional experiments (8-10) for the pairwise comparisons between healthy controls, Covid-19 and Post Covid-19 patients in figure 4e and S6(b-c).
5. I updated the statistical tests for the results that were not from LEfSe analysis. 
    - Mann–Whitney U test was used to compare significant differences between two groups.
    - Kruskal–Wallis test was used to compare significant differences between multiple groups.

Please delete signature 2 in the following experiments:
- Experiment 1 
- Experiment 2

Thank you so much and I wish you a great weekend!

**Comment by SvetlanaUP** [comment]
Deleted.

**Comment by AleruDivine** [comment]
Thank you so much!😊
