### ISSUE TITLE
Current levels of microplastic pollution impact wild seabird gut microbiomes

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#366]
Current levels of microplastic pollution impact wild seabird gut microbiomes – Gloria Fackelmann – Nature Ecology & Evolution
https://www.nature.com/articles/s41559-023-02013-z

**Comment by bolanlew** [comment]
Hi @SvetlanaUP can this article be assigned to me?
Thank you.

**Comment by SvetlanaUP** [comment]
@bolanlew is this study https://github.com/waldronlab/BugSigDBcuration/issues/121 corrected and ready for 2nd review?

**Comment by bolanlew** [comment]
@SvetlanaUP Not yet, but it would be today, that’s why I requested for this.

**Comment by bolanlew** [comment]
@SvetlanaUP this study https://bugsigdb.org/Study_1017 is ready for review

**Comment by AleruDivine** [comment]
@SvetlanaUP, I'd like to review this study if that's okay.
Thank you so much!

**Comment by AleruDivine** [comment]
Hi @SvetlanaUP, is it okay for me to make edits while reviewing this, or should I outline my observations here?

Thank you so much!

**Comment by SvetlanaUP** [comment]
> Hi @SvetlanaUP, is it okay for me to make edits while reviewing this, or should I outline my observations here?
> 
> Thank you so much!

@AleruDivine yes, it's ok to do corrections while reviewing, but please note them all here. Thanks!

**Comment by AleruDivine** [comment]
Okay, got it! Thank you so much!

**Comment by AleruDivine** [comment]
Given the complexity of this paper, I understand the potential for confusion. It took me days to understand and I nearly gave up 🥲 well done @bolanlew 

I relied on Figure 2, as it contained the relevant signatures, to determine the experiments.

I also identified five experiments, based on the signature sources from Figure 2 with specific interactions noted:

**Microplastic Count:**

- Group 0: ASVs negatively correlated with microplastic count
- Group 1: ASVs positively correlated with microplastic count

**Microplastic Mass:**

- Group 0: ASVs negatively correlated with microplastic mass
-  Group 1: ASVs positively correlated with microplastic mass

**Interaction between Microplastic Count and Sample Type ((both seabird species)):**

- Group 0: Cloaca
- Group 1: Proventriculus

**Interaction between Microplastic Mass and Sample Type (both seabird species):**

- Group 0: Cloaca
- Group 1: Proventriculus

**Interaction between Microplastic Counts and Species:**

- Group 0: Cory’s shearwaters (C. borealis)
- Group 1: Northern fulmars(F. glacialis)
- 

The original curator identified 5 experiments:

* Effect of microplastic count in Cory’s shearwaters.
* Effect of microplastic mass in Cory’s shearwaters.
* Effect of microplastic count and mass in the proventriculus and cloaca of both seabirds.
* Effect of microplastic count on in northern fulmars.
* Effect of microplastic mass in F. glacialis.

I worked to refine the experiments and the associated alpha diversities, using the signatures found in Figure 2 for guidance.

Experiments 1 and 2 do not report alpha diversity or sample size. This is because alpha diversity was specifically recorded for the interactions between microplastic count and sample types (the proventriculus and cloacal microbiomes). Additionally, there was no sample size indicated for ASVs negatively or positively correlated with microplastic count and mass.

What is left for this study is the concern of the 2 host species in one experiment and this review will be complete.

Thank you so much!

**Comment by SvetlanaUP** [comment]
Excellent work, @bolanlew @AleruDivine!!

In order to complete this curation, @lwaldron please see our discussion here on having two host species: https://community-bioc.slack.com/archives/C04RATV9VCY/p1727442139045629

Thanks!

**Comment by AleruDivine** [comment]
@SvetlanaUP I wanted to remind you about this. Thank you!

**Comment by SvetlanaUP** [comment]
@cmirzayi how we will proceed with 2 species having for the Host species in the same experiment? Thanks!

**Comment by cmirzayi** [comment]
I honestly have no idea. I guess just choose one of the species and note that this is in fact an analysis of two species in the signatures and on the discussion page. The more places it's noted, the better in this case.

**Comment by AleruDivine** [comment]
Thank you so much for the suggestion @cmirzayi. I think this is a great idea. 
I'll go ahead and do this.

**Comment by AleruDivine** [comment]
Good morning @SvetlanaUP,
I have updated this study.
This review is complete.
Thank you so much! @SvetlanaUP @cmirzayi

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1017 reviewed.
