### ISSUE TITLE
A gut microbiome signature for HIV and metabolic dysfunction-associated steatotic liver disease

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#367]
A gut microbiome signature for HIV and metabolic dysfunction-associated steatotic liver disease
https://pubmed.ncbi.nlm.nih.gov/38162648/

I chose this particular article because its HIV-related. HIV remains a significant global health challenge, affecting millions of individuals worldwide. Working on research related to HIV can ultimately improve public knowledge of the virus.

**Comment by AleruDivine** [comment]
Good evening @SvetlanaUP @cmirzayi @Peacesandy @Omabekee @Folakunmi21!
I'd like to be assigned this paper for curation.
Thank you so much!

**Comment by AleruDivine** [comment]
Good morning @SvetlanaUP, I'd like to submit this study for review.
Link: https://bugsigdb.org/Study_1072
Thank you so much!

**Comment by SvetlanaUP** [comment]
@Scholarpat could you please do review of this curation?

**Comment by Scholarpat** [comment]
Yes @SvetlanaUP , will love to. Thank you

**Comment by Scholarpat** [comment]
Hello Aleru,

Great job with the curation. You've done an impressive job of summarizing the key elements of the study and I agree with most of them. I'd like to offer a few observations;

1. Study Design: I noticed that the study was described as a prospective cohort study. I understand why you would go for that, given this excerpt: **_"This is a multicenter prospective cohort study, conducted at the Hospital Universitario Ramon y Cajal and Hospital Universitario la Paz, in Madrid (Spain)."_** However, it appears that the participants were not followed over time, which is a defining characteristic of a prospective cohort study. Instead, this seems to be a cross-sectional study, as the data were collected at a single point in time from a group of people with HIV and MASLD.

2. Condition: In Experiment 1, both groups have MASLD, with the **contrasting condition being HIV status**. However, in Experiment 2, both groups have HIV but not **MASLD (contrasting condition)** which is not available on BugSigDB. According to the definition in the EFO site, [Non-alcoholic fatty liver disease (NAFLD)](https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0003095) seems like a closer term than [Hepatic steatosis](https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHP_0001397).

3. For exp. 2 signatures, can **_uncultured Lachnospiraceae bacterium_** replace Lachnospiraceae UCG-008 and **_uncultured Prevotellaceae bacterium_** replace Prevotellaceae UCG-001? (They are of different ranks; species and genus) - Not exactly sure so I'm posing this as a question.

4. I noticed that Experiment 3 might be redundant, as it appears to repeat the comparisons outlined in Experiments 1 and 2. The excerpt **_"In this study, we aim to characterize the gut microbiota composition in people with HIV and MASLD (HIV+MASLD+) and compare it with that of two control groups: PLWH without MASLD (HIV+MASLD-) and individuals with MASLD without HIV infection (HIV-MASLD+)"_** suggests that the comparisons made in Experiments 1 and 2 already cover this. Could you consider whether Experiment 3 is redundant or if it offers unique insights?

I hope these suggestions are helpful. Thank you for your hard work on this curation, well done!

**Comment by AleruDivine** [comment]
Thank you for the in-depth review @Scholarpat.

For your first and second notes, I was skeptical about the study design and the mention of cohorts made me go for it. Yes, participants were not followed over time. I should have also considered that the study did not observe the subjects over a period of time. I will make the change. Also, non-alcoholic fatty liver disease (NAFLD) is a better condition as it is the for name for Metabolic dysfunction-associated steatotic liver disease (MASLD).

For the third note, in the context of taxonomy and microbial ecology, the replacement of specific taxa with their uncultured counterparts can be complex and depends on various factors. The designation "uncultured" suggests that these bacteria have not been successfully grown or studied in laboratory conditions but I don't know if it is the case for Lachnospiraceae UCG-008 and Prevotellaceae UCG-001. Should we brand them as uncultured?

While you may be right on the fourth note, I thought that experiment 3 offered a more targeted investigation of the control groups. So I viewed it as complementary rather than redundant.

"We found that MASLD is associated with increased homogeneity across individuals, in contrast to that observed in the HIV+NAFDL- group, in which the dispersion was higher ([Figure 3], Permanova test, P value <0.001; ANOSIM, P value <0.001). In addition, MASLD but not HIV determined a different microbiota structure (Tukey multiple comparisons test: HIV+MASLD- vs. HIV+MASLD+, q-value = 0.002; HIV-MASLD+ vs. HIV+MASLD+, q-value = 0.930; and HIV-MASLD+ vs. HIV+MASLD-, q-value < 0.001)" Although this excerpt described beta diversity, I thought it would be valid to add the extra experiment.

Thanks again for these suggestions!😊

**Comment by Scholarpat** [comment]
For the 3rd point, we'll need confirmation from the mentor. For the 4th point, I see your point of view.

Well done once again @AleruDivine  👍

**Comment by SvetlanaUP** [comment]
Excellent review @Scholarpat and response to review @AleruDivine!!

I agree with @AleruDivine a signature with Lachnospiraceae UCG-008 and Prevotellaceae UCG-001 should stay as it is. Are all the other changes made so I label it reviewed?

Well done!!

**Comment by Scholarpat** [comment]
Thank you @SvetlanaUP

**Comment by AleruDivine** [comment]
Thank you so much @SvetlanaUP 😊

**Comment by AleruDivine** [comment]
@SvetlanaUP this review is complete.

Thank you so much!

**Comment by AleruDivine** [comment]
This is also complete @SvetlanaUP

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1072 reviewed.
