### ISSUE TITLE
A cross-sectional analysis about bacterial vaginosis, high-risk human papillomavirus infection, and cervical intraepithelial neoplasia in Chinese women

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#368]
A cross-sectional analysis about bacterial vaginosis, high-risk human papillomavirus infection, and cervical intraepithelial neoplasia in Chinese women
https://pubmed.ncbi.nlm.nih.gov/35459771/

I find this cross-sectional analysis interesting as it addresses a prevalent issue among women.

**Comment by Analyst-Joan** [comment]
This Sounds Quite Interesting @Scholarpat 
Please can I be assigned this paper for curation? @SvetlanaUP @cmirzayi

**Comment by Analyst-Joan** [comment]
Thank you @SvetlanaUP

**Comment by Analyst-Joan** [comment]
Good afternoon @SvetlanaUP 
This Study has been curated and is ready for review at [Study_1029](https://bugsigdb.org/Study_1029)

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP, I'll love to give this curation a review. May I?

**Comment by SvetlanaUP** [comment]
Sure! @Scholarpat

**Comment by Scholarpat** [comment]
Hi @Analyst-Joan,

Great job on your curation! I must confess, this is actually one tricky curation. Here are my observations and suggestions;

- For body site, samples collected were cervical and vaginal secretions. [Cervical mucus](http://purl.obolibrary.org/obo/UBERON_0000316) seems like a closer term for cervical secretions than Uterine cervix.

- There are 10 experiments with alpha diversities but without signatures which are the 10 experiments you curated. For the signatures, however, the LEfSe result was presented as one against all which I think should be curated as:
a. Normal & HPV (group 0) vs. BV (group 1)
	Red bars are increased
b. Normal & BV (group 0) vs. HPV (group 1)
	Green bar is increased
c. Normal (group 0) vs. BV & HPV(group 1)
	Blue bars are decreased
You merged these 3 experiments with those of the alpha diversities (exp. 1, 2 and 3) which I believe should be different.

_Although, I'm unsure if its entirely necessary to curate 10 experiments without signatures though. If just the three with signatures should be curated instead..._ 🤔

Well done on your curation. Looking forward to hear your views on these points

**Comment by SvetlanaUP** [comment]
**Hi @Analyst-Joan, excellent curation!**

Today at the team meeting we discussed @Scholarpat's comments and we agreed:
our curation is focused on recording signatures rather than only alpha diversity.

In this case we will of course record your efforts in curating alpha diversity but for future curation we will put our curation efforts in recording only experiments with signatures.  

Please do make corrections and let me know when it's finalized. Thanks!

**Comment by Analyst-Joan** [comment]
Thanks for your feedback @Scholarpat. 

- **_For the body site_**, 
[_Cervical mucus_](http://purl.obolibrary.org/obo/UBERON_0000316), refers specifically to, **_"A substance produced by the cervix and endocervical glands[BTO]. Thick acidic mucus that blocks the cervical os after mestruation[WP]. This 'infertile' mucus blocks spermatozoa from entering the uterus."_** 
**Cervical secretions**, however, is a broader term and are mostly collected from the cervix, hence while I chose [Uterine cervix](http://purl.obolibrary.org/obo/UBERON_0000002), which is the most closest  term to cervix, the site of collection.
Also, cervical mucus is not the only possible cervical secretion collected during research aimed at determining the correlation between Bacterial Vaginosis (BV), Human Papillomavirus (HPV), and Cervical Intraepithelial Neoplasia (CIN) development. 
Do you still feel otherwise?

- **_For the experiments_**,
I understand that the LEfSe result was presented as one against all. I used the approach I did based on the alpha diversity measures contrasts. However, I have separated the experiments and added the alpha diversity own separately as suggested.

Thanks for the update too @SvetlanaUP, future curation will focus on recording only experiments with signatures.

**Comment by Analyst-Joan** [comment]
Alright @Scholarpat 
@SvetlanaUP Corrections have been finalized

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1029 is reviewed.
