### ISSUE TITLE
Skin microbiome alters attractiveness to Anopheles mosquitoes

### ISSUE THREAD

**Issue by Analyst-Joan** [waldronlab/BugSigDBcuration#371]
I found this Interesting to know that one's skin microbiome can influence attractiveness to Malaria vector. 😮  
Looking forward to the study curation 😃 

Article Link - https://link.springer.com/article/10.1186/s12866-022-02502-4

**Comment by AleruDivine** [comment]
Hello @SvetlanaUP! Can I be assigned this paper considering the Outreachy contribution phase is over?

**Comment by SvetlanaUP** [comment]
@Analyst-Joan could you please review this curation done by @AleruDivine? Thanks!

**Comment by Analyst-Joan** [comment]
Alright @SvetlanaUP

**Comment by Analyst-Joan** [comment]
Hello @AleruDivine 
Well done 👍 on this curation. Here are my few observations/suggestions:

- I think the group 1 description written as , _"Post-menopausal females, aged between 50 and 90 years, whose skin/body odour were highly attractive to Anopheles mosquitoes"_, is clearer and less vague.

- Based on this Excerpts, _"In order to minimise potential confounding factors such as gender or hormonal cycles [34], while ensuring sufficient numbers of participants to be included in the study, only post-menopausal females, aged between 50 and 90 years were recruited **to control for known variation in attractiveness to mosquitoes."**_ 
I'm thinking they controlled for confounders. What do you think?

- For the signatures, the curation policy requires that we Curate all taxa no matter their taxonomic levels. From supplementary table 2, Order actinomycetales (Taxonomy ID: 2037) and Family Intrasporangiaceae (Taxonomy ID: 85021) were omitted. They should be in signature 2 (decreased abundance)

You've done a great Job 👏👏 👏 .
I hope this feedback is helpful and hope to hear your thoughts on it.

![image](https://github.com/waldronlab/BugSigDBcuration/assets/115580629/d74c5829-71bb-4660-8467-4167c85d5fd1)


-

**Comment by AleruDivine** [comment]
Thank you so much for your insightful review, @Analyst-Joan.

- I completely agree with your suggestion; it enhances clarity, and I have updated the description.
- I did not include gender and hormonal cycles as confounders since there was no mention of controlling them by either stratification or model adjustment(these I am aware of according to the curation policy). In this case, the decision to include only post-menopausal females aged between 50 and 90 years as participants likely served as a preemptive measure to reduce the influence of confounding factors such as gender and hormonal cycles, rather than controlling for them directly during the study. I hope this makes sense.

PS: This is just a thought.

- Thank you for pointing out the omission and also including the taxonomy IDs. I have updated the signatures. 

If there are no further concerns, I believe this study review is complete @SvetlanaUP

Thank you so much for your time and patience.

**Comment by Analyst-Joan** [comment]
Alright @AleruDivine 
Having given this a second read, **"In order to minimise potential confounding factors such as gender or hormonal cycle...."**,The decision to include only post-menopausal females aged between 50 and 90 years as participants likely served as a preemptive measure like you said, just to reduce the influence of confounding factors. Thanks for the explanation. 🙂 

Well done!!! 👍 

@SvetlanaUP review is completed

**Comment by AleruDivine** [comment]
Thank you so much @Analyst-Joan

**Comment by SvetlanaUP** [comment]
Woohoo! Thanks both @Analyst-Joan @AleruDivine!!
