### ISSUE TITLE
Western Kenyan Anopheles gambiae showing intense permethrin resistance harbour distinct microbiota

### ISSUE THREAD

**Issue by Analyst-Joan** [waldronlab/BugSigDBcuration#372]
Link - https://link.springer.com/article/10.1186/s12936-021-03606-4#Sec15

**Comment by Isioma20** [comment]
Interesting paper. I'd love to be assigned this for curation @SvetlanaUP . Thank you!

**Comment by Isioma20** [comment]
Thank you!

**Comment by Isioma20** [comment]
This study was curated at https://bugsigdb.org/Study_1042 and is now ready for review

**Comment by Scholarpat** [comment]
Hi @Isioma20,

This is a wonderful curation. Well done!

The MHT field was curated as 'No,' but the study used the Benjamini-Hochberg false discovery rate (FDR) for MHT. I have corrected this field.

The study has been reviewed and is now complete @SvetlanaUP.

Thank you very much.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1042 reviewed.

**Comment by Isioma20** [comment]
Hi @Scholarpat . thank you so much for the review. I has written no for MHT correction because while it stated that Benjamini-Hochberg false discovery rate (FDR) was used for alpha diversity and beta diversity indices, it did not mention that it was used when the differential abundance was determined. This also coupled with the fact that the study used Lefse for analysis buttressed my interpretation of the study.

**Comment by Scholarpat** [comment]
Thank you for pointing this out @Isioma20. I'll take a look at it again.

**Comment by SvetlanaUP** [comment]
Corrected "MHT: no". Thanks @Isioma20!

**Comment by Scholarpat** [comment]
Thank you @SvetlanaUP for the correction. Was going to ask this on slack tomorrow.
Happy Sunday!
