### ISSUE TITLE
Distinct alterations of gut microbiota between viral- and non-viral-related hepatocellular carcinoma 

### ISSUE THREAD

**Issue by MyleeeA** [waldronlab/BugSigDBcuration#374]
@MyleeeA here you could do "Edit" (... on the right upper corner of this comment box) and add all the info for this study:

Distinct alterations of gut microbiota between viral- and non-viral-related hepatocellular carcinoma – Thananya Jinato – Appl Microbiol Biotechnol.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10771587/

* Your poor-in-information message below: Link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10771587/ is deleted now.

**Comment by MyleeeA** [comment]
Link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10771587/

**Comment by Isioma20** [comment]
Hello @SvetlanaUP I'd love to curate this study. Thank you.

**Comment by Isioma20** [comment]
Thank you!

**Comment by Isioma20** [comment]
This study has been curated at https://bugsigdb.org/Study_1032 .
It is now ready for review

**Comment by MyleeeA** [comment]
Thanks @SvetlanaUP 

Can I review this?
It might be a slow review though as I have a few things to sort out but I’ll get it done

**Comment by SvetlanaUP** [comment]
Sure @MyleeeA! Thanks and no worries, take your time.

**Comment by MyleeeA** [comment]
Thank you 🙏🏾

**Comment by MyleeeA** [comment]
Hi @Isioma20 

Well done on your curation 👏🏾
I didn’t realize how a bit confusing this article was but you did a great job. 
I have a few observations and would appreciate your thoughts on them:
1. **Antibiotics Exclusion**: The article says “Within 2 weeks of Fecal sample collection, participants were asked to discontinue antibiotics, prebiotics, probiotic supplements, or proton pump inhibitors (PPIs).” In my opinion this does not clearly say they were excluded based on  Antibiotics intake. 
2. **Experiment**: I believe one experiment is missing. The Alpha diversity figure in the Supplemental Material (FigS1) shows alpha diversities for HCV-HCC vs NBNC as Chao1 to be unchanged (p-value 0.31) , Shannon to be unchanged (p-value 0.088) and Simpson to be increased (p-value 0.05). Although the article says _P_-value <0.05 shows significance, is this why this experiment wasn’t recorded?
3. **Group name and description**: The topic says “Distinct alterations of gut microbiota between viral and non viral related hepatocellular carcinoma”. And the study was conducted to investigate the differences of the gut microbiota diversity and composition between the viral and NBNC-HCC subgroups. The viral related HCC was subdivided again into the HBV and HCV. 
From this NBNC-HCC should be Group 0 in Experiment 2,3 and 5 since the NBNC group is said to be the “Non-hepatitis B, Non-hepatitis C related Hepatocellular Carcinoma group”.

What are your thoughts on this points?
Also is there a read why you curated them the way you did? I might be missing something 
Thank you 😊

**Comment by SvetlanaUP** [comment]
Wonderful review and clear feedback! Thanks @MyleeeA 
Let's hear now @Isioma20 ;)

**Comment by Isioma20** [comment]
Hi @MyleeeA. Thank you so much for the review and feedback. 
For Observation 1, the excerpt you pasted states discontinuation of antibiotics within two weeks by the participants which  implies to me, antibiotic exclusion which is why I stated in the curation as such since I interpreted it as stopping the antibiotics i.e. excluding it.
2. Like you stated, I didn't include that experiment because the significance is at 0.049 which is <0.05. since it crossed that threshold it means it is no longer statistically significant so I didn't add the experiment if all the alpha diversity indices would be unchanged and it had no differential abundance.
3. NBNC-HCC is the more severe form of Hepatocellular Carcinoma which was also cited in the article as shown "Overall, NBNC-HCC is frequently diagnosed at more advanced stages than viral-related HCC (Viral-HCC), and the survival time of NBNC-HCC is typically worse than that of viral-related cases" which is why it was chosen as the group 1 instead of viral HCC.
 I appreciate your thoughts regarding this curation.

**Comment by SvetlanaUP** [comment]
I agree on all @Isioma20's comments. All points well spotted by @MyleeeA to recheck them. Well done, both!!

https://bugsigdb.org/Study_1032 reviewed.

**Comment by MyleeeA** [comment]
Okay

Well done again 
Thank you @SvetlanaUP

**Comment by Isioma20** [comment]
thank you @SvetlanaUP , @MyleeeA
