### ISSUE TITLE
 The effects of cigarette smoking on the salivary and tongue microbiome

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#38]
https://pubmed.ncbi.nlm.nih.gov/34505401/

**Comment by Abosed** [comment]
@lwaldron 
I would like to curate this study

**Comment by Abosed** [comment]
Hello @lwaldron 

I would love to curate this study. Kindly assign

**Comment by chioma-grace** [comment]
Thank you so much for assigning this publication to me for my second contribution. I will do a good job.

**Comment by ftzohra22** [comment]
@chioma-grace You did a great job! Your curation was complete and very thorough. There were a few errors, please revise and make the necessary corrections. A point of note, we only curate signatures that are statistically significant, therefore Figure 2 in this paper is not something we need to curate, since they didn't specify anything about significance. Thank you. 

All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 1
Entered all relevant experiments and no irrelevant experiments (1 point): 1 
Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
Condition entered according to contrast (correct EFO ontology) (1 point): 0 (while the study looked at peridontal microbiome, the condition here would be smoking. They are trying to find the effect smoking has on the microbiome, hence the condition/exposure would be smoking)
Contrast groups correctly identified (1 point): 1
Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point): 1
Antibiotic exclusion correctly identified (1 point): 1 
Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2 
Identified correct statistical test (1 point): 1 
Identified MHT correction (1 point): 0 (there was no MHT correction done here)
Correctly recorded matched on factors (1 point): 0 (nothing about matching or confounder was mentioned)
Entered correct number of statistical tests per experiment (1 point): 0 ( T-test is recorded as a statistical test, it should only be Mann-Whitney)
All diversity measures identified (1 point): 1
Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 0 (Richness was not mentioned)
All signature sources correctly identified (-1 for each error) (2 points): 2
Abundance direction correctly selected (1 point): 1
Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. missing or extraneous taxon) (2 points): Incorrect
Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 2
Total (maximum 24 points): 16

**Comment by chioma-grace** [comment]
Thank you Fatima for being awesome mentor. I have effected the corrections needed. I appreciate your efforts.
