### ISSUE TITLE
Large-scale characterization of the pregnancy vaginal microbiome and sialidase activity in a low-risk Chinese population

### ISSUE THREAD

**Issue by Nana-Habiba** [waldronlab/BugSigDBcuration#381]
Large-scale characterization of the pregnancy vaginal microbiome and sialidase activity in a low-risk Chinese population - Sherrianne Ng- nature
https://www.nature.com/articles/s41522-021-00261-0?fromPaywallRec=false

**Comment by Rahila-me** [comment]
@SvetlanaUP May i curate this paper. Thank you

**Comment by Rahila-me** [comment]
Seen, Thanks

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP , please can I review this curation?

**Comment by Scholarpat** [comment]
Thank you!

**Comment by Scholarpat** [comment]
Hi @Rahila-me,

This is a great curation. You have done wonderful work here. I have made a few observations/suggestions below:

**1. Group 1 definition:** This should be altered slightly for clearer understanding. I suggest using **_"Women with high vaginal sialidase activity, which is often associated with bacterial vaginosis (BV)"_** rather than "Women with high sialidase activity had significantly higher prevalence of Lactobacillus species depleted microbiota."

**2. Source description:** This should be consistent for both signatures 1 and 2 in an experiment. I noticed slight differences in your curation. Rather than making both signature source descriptions different, you can merge them. For example, **_"LDA analysis in vaginal microbiota of women with leukocyte low (grades I-II, green) versus leukocyte high (grades III-IV, red)"_** would be a better fit for both signatures 1 and 2 source description of experiment 2.

**3. Missing taxa:** I noticed you excluded the taxa Bacteroidetes in signature 1 of experiment 1. I understand this might be because [Bacteroidia](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=200643&lvl=3&lin=f&keep=1&srchmode=1&unlock) (rank = class), a heterotypic synonym of Bacteroidetes, is already present. However, [Bacteroidota](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=976&lvl=3&lin=f&keep=1&srchmode=1&unlock) (rank = phylum) is a homotypic synonym of Bacteroidetes, and both should be curated since they are of different taxonomic ranks. Additionally, in signature 2 of experiment 2, the taxa Actinobacteria is not curated.

I hope these suggestions are helpful. Well done on your curation!

**Comment by SvetlanaUP** [comment]
Hi @Rahila-me, good job! Would you like to correct your curation based on @Scholarpat's feedback?

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP, I have effected the corrections to this curation. 

It is now complete.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1034 reviewed.
