### ISSUE TITLE
Effect of electronic cigarette and tobacco smoking on the human saliva microbial community

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#39]
https://pubmed.ncbi.nlm.nih.gov/35229279/

**Comment by Annabelcute** [comment]
Please can you assign this topic to me
NAME: Aguobi Amara

**Comment by ftzohra22** [comment]
Assigned @Annabelcute.

**Comment by Nnadichioma** [comment]
Please can you assign this topic to me
NAME: Chioma Nnadi

**Comment by lwaldron** [comment]
@Nnadichioma will you find an issue that hasn't already been assigned?

**Comment by Nnadichioma** [comment]
@lwaldron Okay. I will do that now. Thanks

**Comment by Annabelcute** [comment]
Thank you

**Comment by Annabelcute** [comment]
https://bugsigdb.org/Study_636/Experiment_1/Signature_3

**Comment by Annabelcute** [comment]
https://bugsigdb.org/Study_636

**Comment by Annabelcute** [comment]
@lwaldron please kindly review my study 

https://bugsigdb.org/Study_636

**Comment by ftzohra22** [comment]
@Annabelcute Thank you for completing your contribution. There were some errors and missing elements in your curation. Please review the feedback and make the changes. 

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 0 (this is a cross sectional study because they recruited a sample of people and divided them into groups)
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0 (there should be more than 1 experiment in this study)
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 0 (the condition should reflect the group being compared, i.e. if its tobacco vs. non smokers, the condition should say tobacco smoking.
6. Contrast groups correctly identified (1 point): 0 (the groups are clearly identified as e-cig smokers, tobacco smokers, non-smokers, and quitters
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 0 
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 1
10. Identified correct statistical test (1 point): 0
11. Identified MHT correction (1 point): 1 
12. Correctly recorded matched on factors (1 point): 0 (there was no mention matched on factors)
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 0 (they used shannon, simpson and chao1)
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 0
16. All signature sources correctly identified  (-1 for each error)  (2 points): 0
17. Abundance direction correctly selected (1 point): 0 
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 0 (wrong figure curated, only figure showing significantly different signatures is Fig 4C-F)
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 0

Total (maximum 24 points): Not scored due to incorrect curation

**Comment by Annabelcute** [comment]
Thank you @ftzohra22  
I will work on it and make the necessary corrections 
Thank you

**Comment by kahvecirem** [comment]
Hi this article have two different page 
https://bugsigdb.org/Study_635
https://bugsigdb.org/Study_636

**Comment by ftzohra22** [comment]
Thank you for catching this @kahvecirem. Removed.

**Comment by cmirzayi** [comment]
Hi @Annabelcute  Thank you so much for your contributions to the BugSigDB project. I wanted to check to see if you wanted to finish this curation. I understand that with the Outreachy applicant selection process over, you may no longer wish to help out with BugSigDB or have other priorities right now.

If not, I will open it up to other curators to finish the curation.

**Comment by atrayees** [comment]
I am unable to access the article using sci-hub, could someone please help me?

**Comment by lwaldron** [comment]
This one is available from PubMed Central - see the link from its PubMed entry just below the SpringerNature icon:

![image](https://github.com/waldronlab/BugSigDBcuration/assets/639942/12ca2060-2e58-414d-b033-dcc9f3c57cc6)

**Comment by atrayees** [comment]
Oh yes, got it thanks!

**Comment by atrayees** [comment]
I made the following changes:
1. Entered the required relevant experiments
2. Corrected the statistical test (ANOVA) 
3. Recorded all the alpha diversity changes
4. Corrected and added all the taxa whose relative abundances are statistically significant
