### ISSUE TITLE
Altered Middle Ear Microbiome in Children With Chronic Otitis Media With Effusion and Respiratory Illnesses

### ISSUE THREAD

**Issue by Analyst-Joan** [waldronlab/BugSigDBcuration#391]
Study Link -[Altered Middle Ear Microbiome in Children With Chronic Otitis Media With Effusion and Respiratory Illnesses](https://www.frontiersin.org/articles/10.3389/fcimb.2019.00339/full)

**Comment by Scholarpat** [comment]
Thank you @SvetlanaUP

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP , good morning.
This curation is ready for review; https://bugsigdb.org/Study_1080

Thank you!

**Comment by SvetlanaUP** [comment]
@Analyst-Joan would you like to review this curation?

**Comment by Analyst-Joan** [comment]
Good evening @SvetlanaUP Sorry for the late response.
If this is yet to be reviewed, I don't mind doing so. Please do let me know.
Thanks 🙂

**Comment by SvetlanaUP** [comment]
Sure! @Analyst-Joan

**Comment by Analyst-Joan** [comment]
Hello 👋  @Scholarpat 
Well done 👍  on this curation. Here are my few observations/suggestions:

- **Group Naming convention:** 
**Group 0 name**: _Chronic Otitis Media With Effusion (COME) patients without asthma or bronchiolitis_
**Group 1 name**: _Chronic Otitis Media With Effusion (COME) patients with asthma or bronchiolitis_
These I believe should be better - My thought/reason is this, if,for instance, someone navigates to just the signature page without seeing the full study page and sees _**"increased abundance in COME with asthma or bronchiolitis"**_, The meaning of **COME** will be unclear.
However, seeing _**"increased abundance in Chronic Otitis Media With Effusion (COME) patients with asthma or bronchiolitis"**_  is clearer with no need to check the paper.

> 🤔 I'm also thinking adding the age of the children **in the Group 1 definition** would provide more context to the study group's demographics, that is having something like, _"Children, **aged between 3 months and 14 years 8 months old (176 months),** with Chronic Otitis Media With Effusion (COME) with a history of lower airway disease (i.e., asthma or bronchiolitis), defined by a history of pulmonary physician-diagnosed asthma; documented chronic wheezing being treated with a daily respiratory inhaler; or PCR (+) for rhinovirus bronchiolitis diagnosis"._ What do you think?

- **Data transformation:** I think raw counts were used. From this excerpt in the study, _"Alpha diversity indices (ASV richness and Shannon diversity) were **calculated on raw counts** using the estimate_richness() function in phyloseq and plotted with ggplot2."_

- **Antibiotics exclusion:** I think inputting only 2 weeks should suffice (As per curation policy - _Include the time frame given for antibiotic exclusion e.g. 2 months, 3 weeks etc.)_

- **MHT Correction:** There was no MHT correction for the taxonomic differential abundance analysis rather it was for  functional profile analysis contrast. According to this excerpt from the study, _"**To test for significant associations between functional profiles and clinical variables,** general linear models implemented using MaAsLin, with significance considered at q < 0.25 as recommended by the authors (Morgan et al., 2012)"_

- Signature 2: On signature 2, _**Turicella**_ is a heterotypic synonym for _**Corynebacterium**_, which you rightly captured, So I think the review flag selected should be _"no known Issues"_ in place of _"review needed"_.

You've done a great Job 👏👏 👏  . 
I hope this feedback is helpful and hope to hear your thoughts on it.

**Comment by Scholarpat** [comment]
Hello @Analyst-Joan,

Thank you for your detailed review and feedback. Here are my thoughts;

- **Group Naming convention:** I felt that adding this definition might not be necessary in the group names since it was already addressed in the definition for Group 1. However, I understand your perspective. 
 
> I agree that including the age of the children can improve clarity in the group description. I have updated this information accordingly.

- **Data Transformation:** I was initially uncertain due to the repeated use of relative abundance in the study. After reviewing the excerpt again, I agree that using raw counts is more appropriate and have made the correction.

- **Antibiotics exclusion:** I acknowledge your point. I have removed the additional information and retained only the timeframe.

- **Signature 2:** I opted for the "review needed" tag so it can be changed upon review. However, I have now amended this to "no known issues."

Thank you once again for your valuable suggestions. They have greatly contributed to improving the quality of this curation.

**Comment by Analyst-Joan** [comment]
Alright, @Scholarpat Well done.
Would love to hear @SvetlanaUP perspective on the naming convention before proceeding to mark this as reviewed.

**Comment by SvetlanaUP** [comment]
Great job, @Scholarpat @Analyst-Joan!!

I agree with your suggestion @Analyst-Joan!
Since we are discussing already the clarity of this part, in my opinion, then the reader will have the same issue to understand it. So more precise and even repetitive definition would be definitely helpful in this case. 

Do let me know when this curation is done.

**Comment by Scholarpat** [comment]
Thank you @SvetlanaUP, @Analyst-Joan ,

All changes have now been effected.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1080 is reviewed.
