### ISSUE TITLE
Cigarette Smoking Modulation of Saliva Microbial Composition and Cytokine Levels

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#40]
https://pubmed.ncbi.nlm.nih.gov/30405010/

**Comment by Abosed** [comment]
@lwaldron 

i would love to work on this study

kindly assign please

**Comment by Abosed** [comment]
@lwaldron @cmirzayi 

Trust you are doing well.

I would like to curate this study. Kindly assign.

**Comment by mcarlsn** [comment]
Hi @Abosed great job, thanks so much for your curation. There were few errors in the experiment, study design, and signature sections that we addressed. One quick note, for Signature 1 and 2, the “source” field should state the table or figure where information was taken. In this case, the needed info is from Figure 4, so the source field was updated to say “Figure 4”. Please review additional comments below as these notes will be helpful for any future curations that you work on.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0 (Experiment 2 was deleted because there was only 1 significant association explored (between smokers and nonsmokers)
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 0 (condition should be changed to “smoking behavior”) 
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2
10. Identified correct statistical test (1 point): 0 (Although the Mann-Whitney-Wilcoxon test is mentioned in the results, the statistical test used to determine smoker microbial biomarkers is LEfSe, therefore the statistical test must be changed to LEfSe)
11. Correctly recorded matched on factors (1 point): 0 (we fill out the “matched” field if the authors explicitly call out matched characteristics. In this study, no matching occurred therefore those terms were removed.)
12. Entered correct number of statistical tests per experiment (1 point): 1
13. All diversity measures identified (1 point): 1
14. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 1
15. All signature sources correctly identified  (-1 for each error)  (2 points): 0 (The list of NCBI in signature 1 and 2 did not reflect the significant bacteria for nonsmokers and smokers. Those lists have been updated). 
16. Abundance direction correctly selected (1 point): 1
17. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 0 
18. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 0 

Total (maximum 23 points): 12

**Comment by mcarlsn** [comment]
@Abosed FYI I updated the review, please see above for details and the updated total score.
