### ISSUE TITLE
Gut microbiome is not associated with mild cognitive impairment in Parkinson’s disease

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#400]
Gut microbiome is not associated with mild cognitive impairment in Parkinson’s disease – Velma T. E. Aho – npj Parkinson's Disease
https://www.nature.com/articles/s41531-024-00687-1

**Comment by AleruDivine** [comment]
Hi @SvetlanaUP, can I go ahead to curate this?

**Comment by SvetlanaUP** [comment]
sure @AleruDivine 

please also help in reviewing already curated studies ;)

**Comment by AleruDivine** [comment]
Thank you so much @SvetlanaUP 😊
Happy to help anytime!

**Comment by SvetlanaUP** [comment]
Hi @AleruDivine, have you started to curate this one? If not, there is a new student who wants to do it :)

**Comment by AleruDivine** [comment]
I haven’t started curating this. Please go ahead. 
Apologies for my late reply. 🙏

**Comment by SvetlanaUP** [comment]
Sure, no problem.

**Comment by AleruDivine** [comment]
Good morning @SvetlanaUP! I made a huge mistake by saying I had not already started curating this. I did start curating it on June 20th and I completed it today. I mistook this for another issue 🙏

I only realized this today as I am about to submit it for review. I genuinely apologize for this.

This is ready for review at https://bugsigdb.org/Study_62

**Comment by SvetlanaUP** [comment]
Ready for review at https://bugsigdb.org/Study_62

**Comment by Scholarpat** [comment]
Hi @AleruDivine,

I'm currently reviewing this curation and need some clarification. I noticed you curated Supplementary Figures 2c, 3a, 3b, and 3c as your signature sources for all the experiments. However, based on my understanding, Supplementary Tables 3b, 3c, and 3d contain detailed results for the differential abundance comparisons. Could you please confirm if there is another supplementary source I should be referring to? 

Kindly check this and let me know. Thank you very much.

**Comment by AleruDivine** [comment]
@Scholarpat, those are typographical errors. Let me correct them. My apologies.

**Comment by AleruDivine** [comment]
I only curated, 3b, 3c and 3d. I don't even know how that happened🫨

**Comment by AleruDivine** [comment]
I think I’ve corrected all of them now. 🙏

**Comment by Scholarpat** [comment]
Hi @AleruDivine,

I must commend your effort on this complex curation. I spent hours trying to understand the article myself. Here are my observations/suggestions:

1. **Study design:** This should be case-control and not cross-sectional observational.

2. **Condition:** In Experiment 2, both groups had PD, and what is contrasted is the presence or absence of cognitive impairment. 'Cognitive Impairment' would be more fitting as the condition here.

3. **Data transformation:** This is often dependent on the statistical test used for differential abundance. Different tests make use of different data transformation techniques. @cmirzayi kindly explained this in detail in one of her chats [here](https://community-bioc.slack.com/archives/C04RATV9VCY/p1697145085673689?thread_ts=1697141457.022309&cid=C04RATV9VCY). For this curation, it should be raw counts for experiments using the DESeq2 statistical test, for example.

4. **Signature:** I noticed you curated both significant and non-significant taxa for all your experiments. For example, in Signature 1 of Experiment 1, taxa like Cloacibacillus (padj - 0.075), Collinsella (padj - 0.071), Coriobacteriaceae (padj - 0.064), Coriobacteriales (padj - 0.097), etc., are above the significance threshold and should not be curated. Although Supplementary Tables 3b, 3c, and 3d _(note there's a typo as you curated them as figures instead of tables)_ contain detailed results for the differential abundance comparisons (both significant and non-significant taxa), after reviewing the article several times, I think Supplementary Figure 1d is simpler to curate. Note that either is okay as a signature source since they both contain the same information; it’s totally based on your discretion. I mention Supplementary Figure 1d because this figure only highlights the significant taxa (asterisks), although the experiment comparing PD-NC vs PD-MCI is not in it, only in Supplementary Tables 3c.

I hope this is helpful. I'd love to hear your thoughts on this. Well done!

**Comment by AleruDivine** [comment]
Thank you so much for these observations @Scholarpat. I had difficulty curating this because it always redirected me every time I saved. I will go through this carefully and share my thoughts or make changes where necessary. Thank you so much!

My apologies for getting to this now, I had a really long day.

**Comment by AleruDivine** [comment]
This is such an impressive review @Scholarpat   I have made corrections for points 1, 2, and 3 and especially appreciate you pointing me to the thread by @cmirzayi.

I will proceed with curating Supplementary Figure 1d. I initially overlooked the p-values in the description of the tables, as my focus was on the log2 fold change.

I will curate Table 3c for Experiment 2, as it contains significant results for PD-NC vs. PD-MCI, which are not represented in Figure 1d.

Thank you so much!

**Comment by Scholarpat** [comment]
Thank you so much for your response @AleruDivine. Please take your time with the curation.
Well done!

**Comment by AleruDivine** [comment]
All suggestions implemented @Scholarpat @SvetlanaUP 

I'd like to delete this signature @SvetlanaUP 
https://bugsigdb.org/Study_62/Experiment_7/Signature_2

Thank you so much!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_62 reviewed.

**Comment by KateRasheed** [comment]
Good morning @SvetlanaUP . While correcting the antibiotics exclusion in this study, I noticed that Experiment 1 Signature 2 down to Experiment 7 Signature 1 is still having the "**Needs review**" tag.

Thank you so much.
