### ISSUE TITLE
Transplantation of gut microbiota derived from patients with schizophrenia induces schizophrenia-like behaviors and dysregulated brain transcript response in mice

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#402]
Transplantation of gut microbiota derived from patients with schizophrenia induces schizophrenia-like behaviors and dysregulated brain transcript response in mice – Nana Wei – Schizophrenia
https://www.nature.com/articles/s41537-024-00460-6

**Comment by JacobDeJesus** [comment]
Hi Dr. Svetlana, I hope you are very well. I would like to curate this data, I recently curated a paper regarding to treatment-resistant schizophrenia, and it cultivated my interest to understand more about the microbiota of induvivuals with this pathology.

**Comment by JacobDeJesus** [comment]
Hi Dr. @Scholarpat, I hope you are very well. This curation is ready for review.

**Comment by Scholarpat** [comment]
Hi @JacobDeJesus,

I commend your efforts and the work you have done so far. Here are my observations and suggestions for changes:

1. **Antibiotics Exclusion**: Include only the antibiotic timeframe here. BugSigDB doesn't document other forms of treatment, such as antipsychotic treatment, in this case.

2. **Data Transformation**: In Experiment 1, it should be relative abundance rather than centered log-ratio.

3. **Statistical Test**: In Experiment 1, LEfSe alone is sufficient as Kruskall-Wallis was used to compare alpha diversities (and not differential abundance) between groups.

4. **Alpha Diversity**: Six different indexes were reported (Shannon, Simpson, Faith, richness, Chao1, and Pielou’s evenness), but only one was curated. You can find this in Supplementary Figure 1A.

5. **Signature**: In Experiment 1, Figure 2B is a better signature source and should be curated instead of Figure 1E. Figure 2B has all the signatures in Figure 1E and more.

6. **Additional Experiment**: This study has two experiments. The first was done on humans (which you have curated as Experiment 1), and the second on mice transplanted with SCZ or HC fecal microbiota (not yet curated). No alpha diversity index is reported for this second experiment. The signature can be curated from Figure 4D.

Please kindly make these changes and let me know when you are done.

Thank you very much.

**Comment by Scholarpat** [comment]
https://bugsigdb.org/Study_1088

**Comment by JacobDeJesus** [comment]
Hi Dr. @Scholarpat, I hope you are very well. Thank you so much for the feedback! I have made the corrections, once again this curation is ready for review.

Thank you very much @Scholarpat

**Comment by SvetlanaUP** [comment]
Ready for review @Scholarpat

**Comment by Scholarpat** [comment]
Hi @JacobDeJesus,

You have done a commendable job on the curation. I made a few changes to enhance the accuracy and clarity of the information. Here are the adjustments I made:

1. **Signature Descriptions:** I refined the descriptions for both experiments to ensure they are more precise.

2. **Taxa Resolution:** I resolved some of the taxa that were highlighted in orange. For future reference, please use the [NCBI](https://www.ncbi.nlm.nih.gov/taxonomy) or [UniProt](https://www.uniprot.org/help/taxonomy) taxonomy browser for this purpose; 

   **Experiment 1, Signature 1:**
   - Actinobacteria to Actinomycetota
   - Enterobacteriales to Enterobacterales

   **Experiment 1, Signature 2:**
   - Bacteroidetes to Bacteroidota
   - Firmicutes to Bacillota
   - Clostridiales to Eubacteriales
   - Ruminococcaceae to Oscillospiraceae

   **Experiment 2, Signature 2:**
   - Erysipelatoclostridium to Thomasclavelia

Great work overall! 👏

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1088 reviewed.
