### ISSUE TITLE
Intestinal Microbes in Patients With Schizophrenia Undergoing Short-Term Treatment: Core Species Identification Based on Co-Occurrence Networks and Regression Analysis

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#403]
Intestinal Microbes in Patients With Schizophrenia Undergoing Short-Term Treatment: Core Species Identification Based on Co-Occurrence Networks and Regression Analysis – Min Xiang – Frontiers in Microbiology
https://www.frontiersin.org/journals/microbiology/articles/10.3389/fmicb.2022.909729/full

**Comment by JacobDeJesus** [comment]
Hi Dr. Svetlana, I hope you are very well. I would like to curate this data, I recently curated a paper regarding to treatment-resistant schizophrenia, and it cultivated my interest to understand more about the microbiota of induvivuals with this pathology.

**Comment by JacobDeJesus** [comment]
Hi Dr. @Scholarpat, I hope you are very well. This curation is ready for review.

**Comment by Scholarpat** [comment]
Hi @JacobDeJesus,

This was a good attempt and I commend your efforts here. Here are my observations;

1. **Study Design**: This is a time series/longitudinal observational study, not cross-sectional or case-control. This is because samples were collected before and after treatment, which is a defining characteristic of a time series study design.

2. **Condition**: Both groups had schizophrenia. The variable being contrasted here is 'Treatment,' which is more appropriate as the condition.

3. **Group 1 Definition**: The information previously curated here was defining Group 0.

4. **Antibiotics Exclusion**: I've included only the antibiotic timeframe here.

5. **Data Transformation**: This field is relative abundance not than centered log-ratio.

6. **Alpha Diversity**: Only two indexes (richness and Shannon diversity) were reported. There is no report of Simpson in the study.

7. **Signature**: changed fig. 2 to fig. 2A and altered the description.

8. **Taxonomy Browser**: I used the [NCBI taxonomy browser](https://www.ncbi.nlm.nih.gov/taxonomy) to resolve the taxa highlighted in orange. Another browser you can use for this purpose is [LPSN](https://lpsn.dsmz.de/](https://lpsn.dsmz.de/).

Well done 👏

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

This curation is complete.
https://bugsigdb.org/Study_1089

Thank you.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1089 reviewed.
