### ISSUE TITLE
Characterization of the Tissue and Strain-Specific Microbiota of Anopheles funestus Giles (Diptera: Culicidae)

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#416]
Characterization of the Tissue and Strain-Specific Microbiota of Anopheles funestus Giles (Diptera: Culicidae) – Chia-Yu Chen – Trop Med Infect Dis.

https://www.mdpi.com/2414-6366/9/4/84

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP, 

Please add the host species to this study; _**Anopheles funestus**_.
Thank you!

**Comment by MyleeeA** [comment]
Hi @SvetlanaUP 
Can I be assigned this paper?

**Comment by MyleeeA** [comment]
Thank you @SvetlanaUP 🙏🏾

**Comment by MyleeeA** [comment]
Hi @SvetlanaUP 

This curation is ready for review https://bugsigdb.org/Study_1228
Thank you

**Comment by AleruDivine** [comment]
Well done on your curation @MyleeeA 👏👏 You did a really good job at this.

I made two corrections: 
1. I updated the Group 1 definition for Experiment 1 from "**Adults Anopheles funestus that were three days old and had not been blood-fed were used for midgut dissections**" to "**Adults Anopheles funestus that were 15 days old and had had 3 blood meals.**" This is because Anopheles funestus (Salivary gland) was used for Group 1. In addition, I corrected the sample sizes in experiment 1 too.
2. I corrected the genus _Rahnella 1_ to _Rahnella_ in signature 2 of experiment 4 and signature 1 of experiment 6. It was reported as _Rahnella_ in the text.


Please have a look at the study to note the corrections made.
Thank you so much!

This review is complete @SvetlanaUP

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1228 reviewed.
