### ISSUE TITLE
The gut microbiome from patients with schizophrenia modulates the glutamate-glutamine-GABA cycle and schizophrenia-relevant behaviors in mice

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#421]
The gut microbiome from patients with schizophrenia modulates the glutamate-glutamine-GABA cycle and schizophrenia-relevant behaviors in mice – Peng Zheng et al. – Science Advances
https://www.science.org/doi/10.1126/sciadv.aau8317

**Comment by JacobDeJesus** [comment]
Hi Dr. @SvetlanaUP, I hope you are doing well. I would like to curate this study.

**Comment by JacobDeJesus** [comment]
Hi @SvetlanaUP and @Scholarpat, I hope you both are well. This curation is ready for review! :)

https://bugsigdb.org/Study_1093

**Comment by SvetlanaUP** [comment]
@Scholarpat can you review it, please?

**Comment by Scholarpat** [comment]
Hello @JacobDeJesus,

Here are my observations and suggestions:

- Study Design: "Case-control" alone should be sufficient.

- Data Transformation: This should be relative abundance rather than centered log-ratio transformed.

- Signature: The study reported both increased and decreased signatures in Table S2A, but only one was curated. The terms "down" indicate decreased, while "up" indicates increased in schizophrenia.

- Curation Detail: When curating, you should curate at the most specific taxonomic level possible. This allows for more detailed information capture. For example, three different OTUs from the same family, 'Bacteroidaceae', should be curated at the species level: Bacteroides eggerthii, Bacteroides massiliensis, and unclassified Bacteroides. This provides more specificity than curating just at the family level as "Bacteroidaceae".

Thank you.

**Comment by Scholarpat** [comment]
I noticed all the updates have been made. Well done @JacobDeJesus.

This curation is complete @SvetlanaUP.
Thank you.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1093 reviewed.
