### ISSUE TITLE
Gut microbial biomarkers for the treatment response in first-episode, drug-naïve schizophrenia: a 24-week follow-up study

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#422]
Gut microbial biomarkers for the treatment response in first-episode, drug-naïve schizophrenia: a 24-week follow-up study – Xiuxia Yuan et al. – Translational Psychiatry

**Comment by joyceqiu23** [comment]
Hi @SvetlanaUP , I would like to curate this article.

**Comment by SvetlanaUP** [comment]
@joyceqiu23 enjoy curating this study! And feel free to ask questions in the Slack channel #bugsigdb

**Comment by SvetlanaUP** [comment]
Hi @joyceqiu23, is this curation https://bugsigdb.org/Study_1099 ready for review? Thanks!

**Comment by MyleeeA** [comment]
Hi @joyceqiu23 

I noticed this [study](https://bugsigdb.org/Study_1099) which you started curating was listed under incomplete pages on BugSigdb 

I will like to get your permission to complete it, if that is okay

**Comment by joyceqiu23** [comment]
Hi @MyleeeA, yes, you have my permission to complete it.

**Comment by MyleeeA** [comment]
Thank you @joyceqiu23 
I’ll get right to it 🙏🏾

@SvetlanaUP can I go ahead?

**Comment by MyleeeA** [comment]
Hi @SvetlanaUP 

This curation is ready for review https://bugsigdb.org/Study_1099 
Thank you

**Comment by KateRasheed** [comment]
Good evening @MyleeeA @joyceqiu23 . Great job on this curation.

Here are some few things to correct in the study:

Please add disease duration to the confounders. Also, experiment 4-6 is missing smoking behavior as a confounder. See this ". In all statistical analyses, age, gender, education, disease duration, smoking status, and BMI were used as covariates."

In experiment 1, Faith(Phylogenetic) is decreased.

Experiment 1, Signature 2: Please curate Unidentified lachnospiraceae as it is, it is different from unclassified lachnospiraceae. Same applies to Unidentified Erysipelotrichaeae

Please request experiment 5 to be deleted as there are no significant results (I'm guessing that's why you didn't curate signatures for it).

Thank you so much.

**Comment by SvetlanaUP** [comment]
Study_1099/Experiment_5 deleted.

**Comment by MyleeeA** [comment]
Thank you so much for your review @KateRasheed 

I agree we missed out smoking status as confounder for those experiments, I would update that.

Alpha diversity for experiment 1 was curated from figure 2 and I still see PD (whole_tree index) as increased in SO (The group 1) and not decreased 🤔

For the signatures on Unclassified and Unidentified, I agree they are not entirely the same, hence a review note was left on each of the taxa curated indicating how they were originally reported in the paper. But if that shouldn’t be the case, I could update it back to unidentified 

Thank you again

**Comment by KateRasheed** [comment]
Thank you so much for the review @MyleeeA . Experiment 4 and 6 does not have smoking behavior yet 😁. Also, disease duration was not added to the confounders in all experiments.

I see the PD as increased now. Thank you so much.

Leaving a review note for the unidentified taxa is fine. Thank you.

**Comment by MyleeeA** [comment]
Yes @KateRasheed 

I’m yet to make the update, not currently with my PC. But you could update the confounders and matched on from your end though

**Comment by SvetlanaUP** [comment]
@KateRasheed please do corrections, @MyleeeA has a lot on her desk. Thanks!

**Comment by MyleeeA** [comment]
Thank you so much @SvetlanaUP 

@KateRasheed please do the corrections
Thank you 🙏🏾

**Comment by KateRasheed** [comment]
All corrections have been made on this study. Thank you so much @SvetlanaUP @MyleeeA

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1099 reviewed.
