### ISSUE TITLE
Gut microbiome diversity is an independent predictor of survival in cervical cancer patients receiving chemoradiation

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#43]
Initiated at https://bugsigdb.org/Study_677. Note - there are no guarantees that information already entered here (such as study design) is correct, so please proceed as you would for a new study with no information pre-entered.

**Comment by ObafemiBlessing** [comment]
I will like to curate this paper as my Second Contribution. Obafemi Blessing

**Comment by ObafemiBlessing** [comment]
Thank you @ftzohra22

**Comment by ObafemiBlessing** [comment]
I am done working on it. They were created by mistake.

**Comment by ObafemiBlessing** [comment]
Thank you @cmirzayi. Thanks for the review.
I noticed at number 9 you didn't state which sequencing detail I got wrong.
I would just like to know for another time.
What do I do after this?

**Comment by cmirzayi** [comment]
Sorry I should have mentioned that point was deducted because some of the information for experiment was missing including the country and a typo in the significance threshold (was 0.5 instead of 0.05).

You can submit your contributions to Outreachy. We may make more papers available for curation soon but it looks like they've mostly been claimed for now.

**Comment by ObafemiBlessing** [comment]
Thank you very much @cmirzayi. I really appreciate it.
I will do just that
