### ISSUE TITLE
Gut microbiome composition in the Hispanic Community Health Study/Study of Latinos is shaped by geographic relocation, environmental factors, and obesity

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#44]
Initiated at https://bugsigdb.org/Study_732. Note - there are no guarantees that information already entered here (such as study design) is correct, so please proceed as you would for a new study with no information pre-entered.

**Comment by H-Moji-H** [comment]
Hello @lwaldron  @cmirzayi @fbeghini I would like to claim #44 for my second contribution. Thank you

**Comment by lwaldron** [comment]
Done!

**Comment by H-Moji-H** [comment]
Thank you

**Comment by H-Moji-H** [comment]
Hello @lwaldron @cmirzayi could you please help review this https://bugsigdb.org/Study_732
Or #44. Am in need of your feedback. Thank you

**Comment by H-Moji-H** [comment]
My name is Harrydas Magangi Ombati. Thank you and sorry for the
inconvenience.

**Comment by cmirzayi** [comment]
No worries! I've associated your name with your github username in our records. Thank you!

**Comment by cmirzayi** [comment]
Hi @H-Moji-H. This was a good first attempt at a complex paper however there are some fundamental errors that prevent scoring. Specifically I think you should focus on curating supplemental tables 4, 5, 6, 7, 8, 9. Each of these is likely its own separate experiment and therefore I imagine this study should have at least 6 experiments, possibly more. You should also be clear in the Source exactly where the curation is coming from. Specifying multiple figures (in this case every figure that was in the paper) is not helpful because it is hard to find what you actually curated from. This is a complex paper with many significant results which will take time to curate properly.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): Not scored
4. Body site correctly identified (i.e. does not include multiple sites) (1 point):
5. Condition entered according to contrast (correct EFO ontology) (1 point):
6. Contrast groups correctly identified (1 point):
7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point):
8. Antibiotic exclusion correctly identified (1 point):
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points):
10. Identified correct statistical test (1 point):
11. Identified MHT correction (1 point):
12. Correctly recorded matched on factors (1 point):
13. Entered correct number of statistical tests per experiment (1 point):
14. All diversity measures identified (1 point):
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point):
16. All signature sources correctly identified  (-1 for each error)  (2 points):
17. Abundance direction correctly selected (1 point):
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points):
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points):

Total (maximum 24 points): Not scored due to missing/incomplete curation

**Comment by H-Moji-H** [comment]
Thank you for your feedback, will work on it over this weekend.

**Comment by mcarlsn** [comment]
All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 1
Entered all relevant experiments and no irrelevant experiments (1 point): Not scored
Body site correctly identified (i.e. does not include multiple sites) (1 point):
Condition entered according to contrast (correct EFO ontology) (1 point):
Contrast groups correctly identified (1 point):
Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point):
Antibiotic exclusion correctly identified (1 point):
Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points):
Identified correct statistical test (1 point):
Identified MHT correction (1 point):
Correctly recorded matched on factors (1 point):
Entered correct number of statistical tests per experiment (1 point):
All diversity measures identified (1 point):
Diversity results correctly entered as increased/ decreased/ unchanged (1 point):
All signature sources correctly identified (-1 for each error) (2 points):
Abundance direction correctly selected (1 point):
Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points):
Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points):
Total (maximum 24 points): Not scored due to missing/incomplete curation

**Comment by mcarlsn** [comment]
Thanks so much for the corrections that you made to the curation @H-Moji-H. We appreciate the time you took to review the comments/edits posted and update the curation. There are a few outstanding issues, including the members of signatures, diversity results, MHT correction,  and group labels. More specifically, it looks like the signatures added only define members for one group. There should be multiple signatures for the experiments here e.g., for Experiment 1 there are bacterial genera positively and negatively associated with obesity and early-life exposure. Also, it looks like the researchers corrected the p-value (you can control-F “FDR corrected P-value” to see where they discuss this) so MHT correction should be “Yes”. This was a complex paper so these fields are tricky. Please let me know if you have any questions! 

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1 
5. Condition entered according to contrast (correct EFO ontology) (1 point): NS
6. Contrast groups correctly identified (1 point): NS
7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point): NS
8. Antibiotic exclusion correctly identified (1 point): NS
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2 
10. Identified correct statistical test (1 point): NS (the significance threshold was not defined) 
11. Identified MHT correction (1 point): NS (You did not call out MHT correction but there are several places in the analysis where the authors discuss correcting the p-value (e.g., “FDR corrected P-value”) so MHT correction should equal “Yes”) 
12. Correctly recorded matched on factors (1 point): 1 
13. Entered correct number of statistical tests per experiment (1 point): NS
14. All diversity measures identified (1 point): 1 
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): NS (it did not decrease across the board) 
16. All signature sources correctly identified (-1 for each error) (2 points): NS
17. Abundance direction correctly selected (1 point): NS
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): NS (Currently, your signatures only define the members of signatures for one group. There should be multiple signatures for experiments e.g., for Experiment 1 there are bacterial genera positively and negatively associated with obesity and early-life exposure). 
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 2

Total (maximum 24 points): NS

**Comment by cmirzayi** [comment]
Hi @H-Moji-H  Thank you so much for your contributions to the BugSigDB project. I wanted to check to see if you wanted to finish this curation. I understand that with the Outreachy applicant selection process over, you may no longer wish to help out with BugSigDB or have other priorities right now.

If not, I will open it up to other curators to finish the curation.

**Comment by atrayees** [comment]
I made the following changes:
1. Corrected the conditions, body sites, and names of the controls and the case groups for each experiment
2. Curated the statistically significant taxa for each experiment
