### ISSUE TITLE
Gut microbiota is associated with differential metabolic characteristics: A study on a defined cohort of Africans and Chinese

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#457]
Gut microbiota is associated with differential metabolic characteristics: A study on a defined cohort of Africans and Chinese - Paul Nizigiyimana – Frontiers in Endocrinology

https://www.frontiersin.org/journals/endocrinology/articles/10.3389/fendo.2022.942383/full

**Comment by balogunadekemi** [comment]
Hello @SvetlanaUP I'd like to be assigned to this paper please

**Comment by SvetlanaUP** [comment]
@balogunadekemi  Is this curation https://bugsigdb.org/Study_1125 finalized and ready for review?
If it is, then you can assigned to another paper to curate.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1125 ready for review.

**Comment by Folakunmi21** [comment]
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0.5
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 0
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 0.5
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 1
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (2 points): 2
19. Correct use of NCBI taxonomy (2 points): 2

Total (maximum 23 points): 20

@balogunadekemi  here is a review of your curation. Excellent condition of choice! I removed “gut microbiome measurement” because “glucose metabolism measurement” is more suitable and suffices. The antibiotic exclusion wasn’t explicitly stated and was wrongly curated as 6 months. Figure 3A is curatable with its statistical test being “metastats”. Also note that Benjamin and Hochberg’s FDR method was applied to correct p-values. Please, create a second experiment using this info. I have made the needed changes in experiment 1.


@SvetlanaUP reviewed✅

**Comment by SvetlanaUP** [comment]
Correction: the study design was corrected by the reviewer @Folakunmi21, thus:
Correct study design (1 point): **0**

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1125 reviewed.
