### ISSUE TITLE
Trans-ethnic gut microbial signatures of prediabetic subjects from India and Denmark

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#458]
Trans-ethnic gut microbial signatures of prediabetic subjects from India and Denmark - Nishal Kumar Pinna – Genome Medicine

https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-021-00851-9

**Comment by KateRasheed** [comment]
Good evening @SvetlanaUP . Can I curate this paper please?

**Comment by KateRasheed** [comment]
Good morning @SvetlanaUP . This study is ready for review:

https://bugsigdb.org/Study_1203

**Comment by AleruDivine** [comment]
H @KateRasheed, well done on this curation!
I have the following observations:

1. It appears you used the OTU IDs instead of Tax IDs for the signatures in experiments 1, 2, 4, 5, and 6 as the signatures don't add up. Please check and correct accordingly.
2. No confounders were corrected for experiments 1, 3, 4, and 5 Supplementary tables S9A, S5, S7 and S8A respectively.
3. For experiment 7 (Table S10), they only corrected for geography-specific cohort effects.
4. Only experiments 2, 6, and 7 had confounders that were corrected for.

Looking forward to your feedback. Thank you so much!

**Comment by KateRasheed** [comment]
Hi @AleruDivine . Thank you for the review. You are so right. Another case of inputting OTU ID thinking it's the tax id. I'll correct them as soon as I can.

**Comment by KateRasheed** [comment]
Good morning @AleruDivine . All corrections have been made on this study. Please check Experiment 4, it also corrected for geography specific cohort (Table S7)

Thank you so much.

**Comment by AleruDivine** [comment]
Thank you so much @KateRasheed. I'll give this a second review right away!

**Comment by AleruDivine** [comment]
Well done! @KateRasheed 

This review is complete @SvetlanaUP
