### ISSUE TITLE
Dysbiosis of Gut Microbiota and Short-Chain Fatty Acids in Encephalitis: A Chinese Pilot Study

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#462]
Dysbiosis of Gut Microbiota and Short-Chain Fatty Acids in Encephalitis: A Chinese Pilot Study - Ruoting Xu – Frontiers in Immonology

https://www.frontiersin.org/journals/immunology/articles/10.3389/fimmu.2020.01994/full

**Comment by Rahila-me** [comment]
@SvetlanaUP please may i curate this paper.

**Comment by Rahila-me** [comment]
@SvetlanaUP okay thank you

**Comment by AleruDivine** [comment]
Great job on this curation, @Rahila-me  👏👏

I made a few additions to the study and also deleted some too to improve accuracy and clarity:

1. Updated the condition to **Encephalitis**. The study didn't specify it was Viral Encephalitis, as previously curated.
2. Refined the antibiotics exclusion criteria from "**Last year**" to "**Antibiotics use in the last year prior to sample collection**" for better detail.
3. Added _Enterobacterales_ to Signature 1 in Experiment 1, as it was originally omitted.
4. Added the **Simpson index** in both Experiments 1 and 2, which was also omitted.
5. Removed some signatures from Experiment 2 due to p-values above the significance threshold (0.05):
Signature 1: Deleted _Akkermansia_ (p = 0.063)
Signature 2: Deleted _Bacteroidetes_ (p = 0.078), _Clostridia_ (p = 0.075), and _Clostridiales_ (p = 0.075).

Please review the study again to take note of these updates. Thank you so much!

@SvetlanaUP this review is complete.

**Comment by SvetlanaUP** [comment]
Thanks @Rahila-me and @AleruDivine!

As for **antibiotics exclusion**, when you click on the information for this criterion it says: Number of days without antibiotics usage (if applicable) and other antibiotics-related criteria used to exclude participants (if any).

The most helpful entry (e.g. for further analysis and comparisons with other studies) would be the number of days, weeks, months, rather than "last year" or a full sentence describing it.

I corrected last year to 12 months.

https://bugsigdb.org/Study_1162 reviewed.

**Comment by AleruDivine** [comment]
Noted! @SvetlanaUP
Thank you so much for the explanation.
