### ISSUE TITLE
The gut microbial composition in polycystic ovary syndrome with insulin resistance: findings from a normal-weight population

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#465]
The gut microbial composition in polycystic ovary syndrome with insulin resistance: findings from a normal-weight population – Fangfang He, Yumei Li – Journal of Ovarian Research

https://ovarianresearch.biomedcentral.com/articles/10.1186/s13048-021-00799-9

**Comment by Princess-Ben** [comment]
Hello @SvetlanaUP, Can this article be assigned to me? Thank you.

**Comment by TheTosin** [comment]
Hello @Princess-Ben please feel free to reach out if you need any assistance in curating the article. I would be happy to collaborate to make the process smoother and more efficient. You can reach me as “Adeshile Oluwatosin” on slack.

**Comment by Princess-Ben** [comment]
That would be nice @TheTosin

**Comment by TheTosin** [comment]
@Princess-Ben i will reach out on slack.
I will go through the blockers you have on this issue so I can provide solution. 

I would start working on it immediately.

**Comment by Princess-Ben** [comment]
Thank you @TheTosin. However, I am done with this article. So don't worry about this. We can collaborate on the next one.

**Comment by TheTosin** [comment]
@Princess-Ben That is great to hear!
I think you should drop a link to your study then tag Svetlana.
So the tag can be changed to “ready for review”.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1175 ready for review.

**Comment by Princess-Ben** [comment]
@SvetlanaUP, Pls can you remove the ready-for-review label? I am currently editing the curation. I'm so sorry for the inconvenience, thank you.

**Comment by Princess-Ben** [comment]
Hello @SvetlanaUP, Can you help delete Signature 2 for Experiment 1? Thank you.
https://bugsigdb.org/Study_1175

**Comment by Princess-Ben** [comment]
@SvetlanaUP Also you can assign the ready for review tag. Thank you.

**Comment by KateRasheed** [comment]
Good morning @Princess-Ben . Great job on this curation. 

Here are few things I would like you to correct in this study:

- The patients were matched on age and body mass index.
- Please state the full meaning of PCOS in the group 0 name and group 1 definition.
- Please change MHT to No because there was no MHT correction done.

See this: "In the PCOS-IR group, the abundance of Peptostreptococcaceae, Enterococcaceae, and Micrococcaeae was higher than that of the other two groups. Lactobacillaceae was the highest in the PCOS-NIR group (Fig. 3). Compared with the HC group, PCOS patients exhibited a higher abundance of Enterococcus. The relative abundance of Rothia, Ruminococcus, Lachnospira, and Enterococcus was significantly higher in the PCOS-IR patients than in the other two groups (P < 0.05), whereas the abundance of the Prevotella was dramatically decreased (P < 0.05). Lactobacillus and Akkermansia were more abundant in the PCOS-NIR group than in the PCOS-IR and HC groups (P < 0.05) (Fig. 4)."

Please add these taxa to their respective experiments and add "Within text result" to the signature sources.

Please let me know if you would need my help in correcting this study. Thank you so much.

**Comment by SvetlanaUP** [comment]
@KateRasheed @Princess-Ben be more precise, instead of "Within text result":
add "In text of the "Gut microbiota composition among PCOS patients section""

**Comment by KateRasheed** [comment]
Okay. This is noted. Thank you so much.

**Comment by KateRasheed** [comment]
Good afternoon @SvetlanaUP . All corrections have been made on this study.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1175 reviewed.
