### ISSUE TITLE
Salivary microbiota and inflammation-related proteins in patients with psoriasis

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#47]
Initiated at https://bugsigdb.org/Study_710. Note - there are no guarantees that information already entered here (such as study design) is correct, so please proceed as you would for a new study with no information pre-entered.

**Comment by shallockh02** [comment]
I Kelvin Joseph can curate this one

**Comment by lwaldron** [comment]
We'll wait until https://github.com/waldronlab/BugSigDBcuration/issues/27 is reviewed before assigning another issue to you @shallockh02.

**Comment by shallockh02** [comment]
It has been reviewed can i proceed to make this my third curation

**Comment by Kiiki015** [comment]
Hello, @lwaldron please can I work on this?

**Comment by lwaldron** [comment]
Sorry @shallockh02 how do you know #27 has been reviewed? I don't see a review there. @Kiiki015 is this your first "second contribution" ?

**Comment by Kiiki015** [comment]
> Sorry @shallockh02 how do you know #27 has been reviewed? I don't see a review there. @Kiiki015 is this your first "second contribution" ?

It's my first contribution.

**Comment by Bahati308** [comment]
hello, @lwaldron , can i take over this

**Comment by Ellajessica** [comment]
@cmirzayi @Bahati308 @lwaldron @cmirzayi @fbeghini . Please can this be assigned to me .

**Comment by cmirzayi** [comment]
@Kiiki015 assigned

**Comment by ftzohra22** [comment]
@Ellajessica Good effort on this curaton. You start was good, however none of the signatures you curated from figure 2 were correct. We have to make sure that we are entering the bacteria upto the species level as it appears on the figure not just part of it. Also you did not enter all the experiments that were being compared. Please review the rest of the feedback and make the necessary changes. Thank you. 

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0 (There should be 2 experiments one comparing P vs. PS and one comparing HC vs. PS)
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 0 (the samples are saliva samples. "saliva" should be the correct term)
5. Condition entered according to contrast (correct EFO ontology) (1 point): 0 (condition should be whatever the case group is, if group 1 is psoraisis, condition should say psoriasis)
6. Contrast groups correctly identified (1 point): 11
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1 (just entering the time period i.e. 3 months is fine)
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 0 (matching only applies if it was specifically mentioned)
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point):  0 (diversty measures were incorrectly identified, there was only one measure used)
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 0 (results were wrong. please review result section again)
16. All signature sources correctly identified  (-1 for each error)  (2 points):  0
17. Abundance direction correctly selected (1 point): 0
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 0
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 0

Total (maximum 24 points): Not scored due to incorrect curation

**Comment by Ellajessica** [comment]
@ftzohra22 . i have corrected it

**Comment by atrayees** [comment]
Study 710
Added a new experiment recording differentially abundant taxa in healthy controls vs. Periodontitis patients in the Signature.
