### ISSUE TITLE
The Potential of Gut Microbiota in Prediction of Stroke-Associated Pneumonia

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#472]
The Potential of Gut Microbiota in Prediction of Stroke-Associated Pneumonia – Zhongyuan Li – Brain Sciences

https://www.mdpi.com/2076-3425/13/8/1217

**Comment by TheTosin** [comment]
Hi @SvetlanaUP 
Please I would like to curate this article

**Comment by Rahila-me** [comment]
@TheTosin @SvetlanaUP , Please tosin are you open for collaboration, so we could finish this paper up. If you are still working on it and you are stuck we can do it together. waiting for your reply. Thank you.

**Comment by TheTosin** [comment]
Hello @Rahila-me I have finished curating this paper 2 days ago. I just needed confirmation on some things which was clarified in today’s meeting.
Thank you for the kind gesture.

@SvetlanaUP https://bugsigdb.org/Study_1115 This study is ready for review.

**Comment by Rahila-me** [comment]
Ok..noted

**Comment by Scholarpat** [comment]
Good morning @SvetlanaUP, I'll be reviewing this curation.

**Comment by Scholarpat** [comment]
Hi Tosin,

Great attempt! Well done. However, there are a few points to note:

- **Study design**: The key feature of a prospective cohort study is missing in this study.
- **Group 1 definition**: The definition should focus solely on Group 1, without defining Group 0 as well.
- **Signature description**: The description needs to be more descriptive.
- **Signature 2 of Exp 1**: Bacteroidetes is reported as a phylum, not a class. Its homotypic synonym, Bacteroidota, should be curated instead of Bacteroidia (which is a class).
- **Signature 2 of Exp 1**: Clostridium XIVb is reported but not curated, while Lachnospiraceae is curated but not reported in the study.
- **Supplementary Figure S3**: This should be curated as Signature 2 of Exp 2.

Please make the necessary corrections.

**CURATION RESULTS:**

| S/N | Criteria                                                           | Total Points | Points Earned |
|-----|--------------------------------------------------------------------|--------------|---------------|
| 1   | All elements marked "Needs review" (none "Incomplete")             | 1            | 1             |
| 2   | Correct study design                                                | 1            | 0             |
| 3   | Entered all relevant experiments and no irrelevant experiments      | 1            | 1             |
| 4   | Body site correctly identified (i.e. does not include multiple sites)| 1            | 1             |
| 5   | Condition entered according to contrast (correct EFO ontology)      | 1            | 1             |
| 6   | Contrast groups correctly identified                                | 1            | 1             |
| 7   | Groups correctly labeled as 1 and 0 (1=cases, 0=controls)           | 1            | 1             |
| 8   | Antibiotic exclusion correctly identified                           | 1            | 1             |
| 9   | Correctly identified sequencing details                             | 2            | 2             |
| 10  | Identified correct statistical test                                 | 1            | 1             |
| 11  | Identified MHT correction                                           | 1            | 1             |
| 12  | Correctly recorded matched on factors                               | 1            | 1             |
| 13  | Entered correct number of statistical tests per experiment          | 1            | 1             |
| 14  | All diversity measures identified                                   | 1            | 1             |
| 15  | Diversity results correctly entered as increased/decreased/unchanged| 1            | 1             |
| 16  | All signature sources correctly identified (-1 for each error)      | 2            | 1             |
| 17  | Abundance direction correctly selected                              | 1            | 0.5             |
| 18  | Members of signatures identified correctly                          | 2            | 1             |
| 19  | Correct use of NCBI taxonomy                                        | 2            | 1             |

**Total = 18.5/23**

**Comment by TheTosin** [comment]
@Scholarpat Thank you for the review.
 clostridium XIVb is now Lachnospiraceae.

Supplementary Figure S3 wasn’t curated because the differential analysis is for taxa in phylum and family level. Should I still go ahead with curating it.

**Comment by TheTosin** [comment]
@Scholarpat @SvetlanaUP Thank you so much for the review. However, I would appreciate if you take a look at these points below.

Clostridum XIVb is now Lachnospiraceae.(This is also in the discussion page).

Supplementary S3 wasn’t curated because it shows the relative abundance of the groups at phylum and family level, where Figure 2 reports same but for genus level which was curated because the curation guide (as well as the discussions that I’ve seen on slack) states that the lowest level of taxonomy should always be curated.

In that case should S3 still be curated. Kindly have a look again.

For the description, Should it not be just what describes the source which is in this case the Figures? Am I to summarize something from the study as well.

Study design: it was stated under the “methods” section of the paper that it is a prospective observational cohort study.

**Comment by SvetlanaUP** [comment]
We (@Folakunmi21 and @Scholarpat) carefully went through your discussion points, please see below our answers for each: 

- Someone entered on the discussion page that “**Clostridum XIVb**” is now known as “lachnospiraceae” which isn’t true. @Folakunmi21 checked the database the person referenced and it was for “Clostridium XIVa”. Clostridium XIVb is still unresolved, however we decide to not deduct points for your curation because you followed the discussion page which is good curation practice. 

- It is correct **to not curate supplementary fig S3**. The figure presents the difference between the 2 groups at phylum and family level. Fig 2 shows the differences at genus level (the lowest taxonomic level in this case) and it was curated. Thus, new scoring: All signature sources correctly identified: 2 and Abundance direction correctly selected: 1

-  The study design is indeed stated in the paper but that design is wrong. The study is cross-sectional observational (corrected). Sometimes authors are wrong in defining their study design type.

- There is a mistake in curating “bacteroidia” instead of “bacteroidetes”. Thus, 1 point is deducted for “correct use of NCBI taxonomy” but “members of signature identified currently”: 2

**Comment by TheTosin** [comment]
Thank you so much @SvetlanaUP @Folakunmi21 @SvetlanaUP I truly appreciate.

I will make the corrections now

**Comment by TheTosin** [comment]
@SvetlanaUP @Folakunmi21 @Scholarpat 
All corrections have been made to the study.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1115 reviewed.

**Comment by SvetlanaUP** [comment]
@TheTosin Please be more specific: which Figure/Table or Signature is under question? Thank you.

**Comment by TheTosin** [comment]
Thank you for responding @SvetlanaUP The idea of not curating supplementary Figure s3. As the conversation on slack is similar to this and that’s why I insisted on curating taxa lower in the taxonomical rank. Chloe’s text was just picked out for reference as that is not the exact illustration.

**Comment by SvetlanaUP** [comment]
@TheTosin thank you very much for bringing this up again!

The original @Scholarpat's (cc @Folakunmi21) comment was correct: Supplementary Figure S3: This should be curated as Signature 2 of Exp 2.

There are two cases of curating different taxonomical levels:
1. different taxonomical levels presented as a categorisation for a particular taxon as a signature
2. differential analysis of different taxonomical levels

In this curation, we have case 2.

Once again, @TheTosin our apologies for this confusion (to be honest, I was not checking supplementary material, and I should!) and please correct this.

**Comment by TheTosin** [comment]
Thank you for clarifying @SvetlanaUP 

I have been curating with this in mind. I would also correct that in this study.

**Comment by TheTosin** [comment]
Hello @SvetlanaUP @Scholarpat Experiment 2/signature 2 has been added to this study. Thank you
