### ISSUE TITLE
The human microbiota is associated with cardiometabolic risk across the epidemiologic transition

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#473]
The human microbiota is associated with cardiometabolic risk across the epidemiologic transition – Na Fei – PlosOne

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0215262

**Comment by AleruDivine** [comment]
Hi @SvetlanaUP I'd like to be assigned this paper for curation.

Taking your advice to explore a wide range of microbiome studies, I haven't worked on a paper that investigates the relationship between the human microbiota and cardiometabolic risk. Also, this study did not utilize lefse. 😅

**Comment by AleruDivine** [comment]
Thanks!

**Comment by SvetlanaUP** [comment]
Hi @AleruDivine, is this curation https://bugsigdb.org/Study_1167 ready for review?

**Comment by AleruDivine** [comment]
Almost ready @SvetlanaUP I am doing a quick final review to check for any unintended omissions.🙏

**Comment by AleruDivine** [comment]
Good morning @SvetlanaUP, I'd like to put this study up for review.
https://bugsigdb.org/Study_1167
Thank you so much!

**Comment by KateRasheed** [comment]
Good afternoon @AleruDivine . Great job on this curation with 28 experiments 😁.

Here are some things I would like you to correct on this curation:

For experiment 1, please use the full name of CMD; signature 2 in this experiment has peptostreptococcaceae not streptococcaceae.

For experiment 5, I see you used Coprococcus 1 as Coprococcus and Coprococcus 2 as Coprococcus sp; however, it's stated that the taxonomy rank is genus. Please curate it as stated in the paper. This would also apply to similar taxa with figures in experiment 7, 13, 19, 2

Same thing applies to the family Clostridiaceae in experiment 6. Please remove the Clostridiaceae bacterium since it's showing species. For this experiment, Clostridiaceae was repeated.

For the group names, kindly specify if it's male and female/male/female in the experiments like we have in the group definition. 

Experiment 15 should be splitted; separate for Ghana and South Africa. The alpha diversity would be unchanged.

Experiments 16, 17, 27, 28 alpha diversity is unchanged 

In experiment 21, Neisseria and Rothia is decreased while Prevotella and Veillonella is increased.

In the signature description and group 1 definition for experiment 25, the analysis was for male not female.

Experiment 26 should also be splitted; separate for Ghana, USA and South Africa. The alpha diversity would be unchanged for all. 

PS: We would be having three additional experiments 

Thank you so much

**Comment by AleruDivine** [comment]
Thank you for the review @KateRasheed. 
I’ll take my time to go through the suggestions and make appropriate corrections and adjustments.

**Comment by AleruDivine** [comment]
All corrections have been effected. @KateRasheed Kindly review again for any omissions.
Thank you so much!

**Comment by KateRasheed** [comment]
Thank you so much for the corrections @AleruDivine . Please request that Signature 2 be deleted from experiment 15(Blautia is for Ghana).

Once this is done, the review would be completed.

**Comment by AleruDivine** [comment]
Oh my! I totally forgot. 

@SvetlanaUP please delete signature 2 in experiment 15. 

Thank you so much!

**Comment by SvetlanaUP** [comment]
Experiment 15/Signature 2 deleted.

**Comment by KateRasheed** [comment]
This study is reviewed @SvetlanaUP

**Comment by KateRasheed** [comment]
This study has been reviewed @SvetlanaUP . Thank you so much.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1167 reviewed.
