### ISSUE TITLE
Decreased microbial co-occurrence network stability and SCFA receptor level correlates with obesity in African-origin women

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#476]
Decreased microbial co-occurrence network stability and SCFA receptor level correlates with obesity in African-origin women – Lara R Dugas – Scientific Reports

https://www.nature.com/articles/s41598-018-35230-9

**Comment by balogunadekemi** [comment]
Hello @SvetlanaUP , I'd like this paper to be assigned to this paper for curation

**Comment by SvetlanaUP** [comment]
@balogunadekemi you have been assigned to this paper https://github.com/waldronlab/BugSigDBcuration/issues/457

**Comment by balogunadekemi** [comment]
Hello @SvetlanaUP , I'd like this paper to be assigned to this paper for curation

**Comment by SvetlanaUP** [comment]
@balogunadekemi you have been already assigned to this paper https://github.com/waldronlab/BugSigDBcuration/issues/457

**Comment by vandana123maddi** [comment]
Hello @SvetlanaUP ma'am I'd like this paper to be assigned to this paper for curation

**Comment by vandana123maddi** [comment]
Hi @Ini-25 i am studying this i will let u know if i got stucked thanks for reaching da... 🙂

**Comment by Ini-25** [comment]
You're welcome

**Comment by vandana123maddi** [comment]
Hi  @SvetlanaUP could u please delete experiment 2 
Thank you

**Comment by SvetlanaUP** [comment]
@vandana123maddi your study link please?

**Comment by AleruDivine** [comment]
Hi @vandana123maddi, trust you are having a great day.
I am checking in to see if you need any help in completing this curation. I am very open to collaborating or answering any questions you may have.

Thank you so much, looking forward to hearing from you.

**Comment by SvetlanaUP** [comment]
@vandana123maddi @Ini-25 @AleruDivine please team up and finalize this curation.

**Comment by AleruDivine** [comment]
Alright @SvetlanaUP will do!

@vandana123maddi @Ini-25  I’ll create a group on Slack for easy communication. Looking forward to working together 🤗

**Comment by vandana123maddi** [comment]
@AleruDivine sure da... !

**Comment by vandana123maddi** [comment]
Hi ma'am @SvetlanaUP can u please delete experiment 3 
Link : https://bugsigdb.org/Study_1191

**Comment by SvetlanaUP** [comment]
@vandana123maddi Deleted.

**Comment by vandana123maddi** [comment]
Hi @SvetlanaUP hope ur going great 
https://bugsigdb.org/Study_1191
Please review ma'am 
Thank you @AleruDivine thanks a lot ur presence added a great value great to collaborate with u 😊

**Comment by AleruDivine** [comment]
Thank you @vandana123maddi

**Comment by AleruDivine** [comment]
Hi @KateRasheed, I wasn not able to access the supplementary tables either but Yoko C helped with sending the tables on Slack. 
See thread - https://community-bioc.slack.com/archives/C04RATV9VCY/p1731873166393969

**Comment by KateRasheed** [comment]
Good morning @AleruDivine . Thank you for sharing the link to the supplementary tables. It was really helpful.

This study is quite an interesting one with lots of experiments. Well-done on this curation. 

**Here are the corrections to be made on this study:**

For experiment 1, signature 2 Please remove the bacteroides sp. and ruminococcus sp(they were referenced as genus not species). 

In experiment 2, Lachnospiraceae is missing from Signature 1

For Experiment 3, Signature 1, Bacteroides ovatus is missing. Please remove Bacteroides sp and Ruminococcus sp(do this in experiment 6, signature 1 too).

For Experiment 4, Signature 1, please remove Ruminococcus sp. 

From experiment 2, signature 2 to the last signature in experiment 15, you changed the source description from Table to Figure; kindly correct these changes. 

From experiment 8-15, the p-value threshold is 0.001 without MHT correction.

Sutterella is missing in experiment 8 and 13.

 Lactobacillus ruminis and Parabacteroides distasonis are missing in experiment 9 signature 1. There is meant to be decreased signature for experiment 9 too; consisting Parabacteroides distasonis and Clostridiales

In experiment 10, only Sutterella is increased. There is meant to be decreased signature for experiment 10 too; consisting Lactobacillus ruminis, Parabacteroides distasonis and Clostridiales

In experiment 14, Sutterella, Lactobacillus ruminis, Clostridales are missing.

Table S16 is curatable without MHT correction and p-value threshold is 0.05. The human differential abundance is in 4-49, while the mice from 50 downwards (when you scroll to the right, you would see the groups). This table is an expansion of Figure 5c which is curatable.

See this “As with the human subjects, we employed GLMs to identify the murine fecal ESVs associated with the lean Ghanaian humanized mice. While no sequences were significantly enriched in the lean Ghanaian humanized mice, 5 ESVs were significantly depleted (p < 0.001), all of which were associated with Lactobacillus sutterella and Parabacteroides distasonis (Table S15). A phylogenetic tree analysis was used to determine the overlap between the human and murine stool ESVs between mice humanized with lean Ghanaian stool, compared to the rest. Only ESVs that had significantly different abundance between these two groups were used in the analysis (p < 0.05, Table S16).

Thank you so much.

**Comment by AleruDivine** [comment]
Thank you so much for the review @KateRasheed I have gone through and made most of the corrections but I'd like for you to review again and check the following:

For experiment 8 and 13, Sutterella has a p value of 0.0502125619527546 and 0.135171890399016 respectively, which means it is above the significance threshold 

All the signatures in experiments 9, 10, and 14 are actually above the significance threshold (0.001), which would mean I was not supposed to curate Sutterella, Clostridiales and 
Parabacteroides distasonis

I don't think Figure 5C or Table S16 are curatable. Here's why: 

From part of the excerpt you shared says "A phylogenetic tree analysis was used to determine the **overlap** between the human and murine stool ESVs between mice humanized with lean Ghanaian stool, compared to the rest. Only ESVs that had significantly different abundance between these two groups were used in the analysis (p < 0.05, Table [S16](https://www.nature.com/articles/s41598-018-35230-9#MOESM17)). The human and murine ESVs had **similar trends** in terms of relative abundance between cohorts. Two phylogenetic branches including ESVs assigned to the genera Parabacteroides and Bacteroides, and the family Lachnospiraceae were depleted in both the lean Ghanaian human stool and mouse stool (Fig. [5c](https://www.nature.com/articles/s41598-018-35230-9#Fig5))."

I believe Table S16 and Figure 5C focuses specifically on co-abundance trends, rather than differential abundance. It kind of shows trends of abundance that occur similarly. Also check Table S16 description "Table S16. Human-murine co-abundance: Ghana0: Ghana lean, Ghana1: Ghana obese, USA0=USA lean, and USA1=USA obese"

@SvetlanaUP please delete signature 1 in experiments 9, 10 and 14 as they were not significant.

Thank you so much!

**Comment by KateRasheed** [comment]
Good evening @AleruDivine . Thank you for effecting most of the corrections. Please don't delete any of the signatures because they are all significant.

All taxa in Table S15 are significant. Their p-values are in the negative. To prove this, look at an excerpt from the text: "5 ESVs were significantly depleted (p < 0.001), all of which were associated with Lactobacillus sutterella and Parabacteroides distasonis (Table S15)."

For Table S16, please let's confirm this during office hours on Tuesday.

**Comment by AleruDivine** [comment]
@KateRasheed Yes, 5 ESVs were depleted, but not significantly. 
The p-values are not on the negative side. 
1.E-01 is 1 raised to the power of negative 1 and simply means 0.109969349223622. If you click on the value in the sheet, it will give you the real number.

So these should be deleted.

I agree with confirming Table S16 on Thurday.

**Comment by KateRasheed** [comment]
Yes yes. I see it now. I have previously come across exponential values and I was told it's in the negative.

Experiment 9, 10 and 14 should be deleted.

Thank you so much @AleruDivine

**Comment by SvetlanaUP** [comment]
Experiment_9/10/14 deleted.

**Comment by AleruDivine** [comment]
Good morning and thank you so much @SvetlanaUP

**Comment by AleruDivine** [comment]
Hi @KateRasheed, this study is ready for a second review.
Please note the following are the new experiments added:
Experiment 9
Experiment 10
Experiment 14
Experiment 16-28

Thank you so much!

**Comment by KateRasheed** [comment]
Good morning @AleruDivine . Happy holidays. Welldone on the addition of these experiments. Here are few corrections to be made on this study:

- Clostridiaceae is missing from experiment 16, signature 2. 
- In experiment 19 signature 2, Faecalibacterium… is missing
- In experiment 20 signature 1, Dorea should be removed while collinsella aerofaciens should be removed from signature 2
- In experiment 23 signature 2, Clostridiales is missing while Lachnospiraceae is missing from signature 1
- In experiment 24, only Defluviitalea saccharophila is decreased
- In experiment 26, Clostridiales was increased and decreased
- In experiment 9 signature 2, Lachnospiraceae should be removed
- In experiment 10 signature 1, Ruminococcaceae is missing
- In experiment 14 signature 2, Clostridiales should be removed while in signature 1, it’s Bacteroides not Bacteroides uniformis; Clostridiales and Coprococcus are missing from signature 1

Thank you so much

**Comment by AleruDivine** [comment]
Thank you for the second review @KateRasheed 
All corrections have been made.

**Comment by KateRasheed** [comment]
Thank you so much for effecting the corrections. Sincere apologies for the long study 😎 @AleruDivine 

This study is reviewed @SvetlanaUP

**Comment by AleruDivine** [comment]
No need to apologize @KateRasheed 😊
I'm glad this review is complete😅

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1191 reviewed.
