### ISSUE TITLE
Perturbations of the Gut Microbiome and Metabolome in Children with Calcium Oxalate Kidney Stone Disease

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#48]
Initiated at https://bugsigdb.org/Study_539. Note - there are no guarantees that information already entered here (such as study design) is correct, so please proceed as you would for a new study with no information pre-entered.

**Comment by sopeadeniji** [comment]
@lwaldron Please, assign study 539 to me.

**Comment by sopeadeniji** [comment]
@cmirzayi. Can I work on this study after reviewing https://bugsigdb.org/Study_708?

**Comment by ftzohra22** [comment]
@sopeadeniji We'll assign this after we reviewed all your previous curations.

**Comment by sopeadeniji** [comment]
@ftzohra22 got you.

**Comment by mockingjay13** [comment]
I would like to get this article assigned to me for complete curation. Thank you!
Name: Aditi SIngh

**Comment by BlessingKaz** [comment]
@cmirzayi and  @Iwaldron can i work on this ?

**Comment by Kiiki015** [comment]
@cmirzayi  I'll like to work on this, please.

**Comment by ObafemiBlessing** [comment]
@lwaldron one of my work has been reviewed #43, I would like to work on this to help me work on my corrections

**Comment by ftzohra22** [comment]
@Kiiki015 and @Anthonyqueencode #13 and #37 not assigned to anyone, please pick from those. or you could wait till more options are available.

**Comment by Kiiki015** [comment]
> @Kiiki015 and @Anthonyqueencode #13 and #37 not assigned to anyone, please pick from those. or you could wait till more options are available.

Thank you

**Comment by BlessingKaz** [comment]
thanks so much @ftzohra22  for assigning this to me.

**Comment by BlessingKaz** [comment]
hello @ftzohra @cmirzayi and @lwaldron please kindly review my work. I really need your feedbacks about my curation.

**Comment by claregri** [comment]
Hi Blessing, good start on this curation! Be sure to thoroughly review the captions before curating a figure or table - Figure 2 is characterizing the metabolites in the samples, not statistically comparing taxon abundance. Please note that the LDA field should be blank; though they used LDA in their analysis, it was not done for any curatable experiment so is not applicable to what you curated.
1. All elements marked "Needs review" (none "Incomplete") (1 point): 0
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 0
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2
10. Identified correct statistical test (1 point): 0
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1 (they did not adjust for the match factors in the analysis, so those should not be listed as confounders in the experiment)
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 0 (too many identified)
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 1 
16. All signature sources correctly identified  (-1 for each error)  (2 points): not scored due to incorrect curation
17. Abundance direction correctly selected (1 point): not scored due to incorrect curation
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): not scored due to incorrect curation
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): not scored due to incorrect curation

Total (maximum 24 points): not scored

**Comment by BlessingKaz** [comment]
@claregri thank you so much for the feedback I appreciate. the corrections are noted I would carefully work on them.

**Comment by cmirzayi** [comment]
Hi @BlessingKaz  Thank you so much for your contributions to the BugSigDB project. I wanted to check to see if you wanted to finish this curation. I understand that with the Outreachy applicant selection process over, you may no longer wish to help out with BugSigDB or have other priorities right now.

If not, I will open it up to other curators to finish the curation.

**Comment by sopeadeniji** [comment]
Hi Chloe,

Please, open up the curation for other curators to finish. I have other priorities at this time and can no longer work on BugSigDB project.

Best,

Sophy


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
