### ISSUE TITLE
Sustained gut dysbiosis and intestinal inflammation show correlation with weight gain in person with chronic HIV infection on antiretroviral therapy

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#487]
Sustained gut dysbiosis and intestinal inflammation show correlation with weight gain in person with chronic HIV infection on antiretroviral therapy - Aya Ishizaka – BMC Microbiology

https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-024-03431-0

**Comment by omojokunoluwatomisin10** [comment]
@SvetlanaUP, please kindly assign this to me

**Comment by MyleeeA** [comment]
Hi @omojokunoluwatomisin10 and @KateRasheed 
I am currently done as well and open to offer assistance/collaborate with you on this, if you need any assistance 

Thank you 🙏🏾

**Comment by SvetlanaUP** [comment]
@KateRasheed @omojokunoluwatomisin10 please do finalize this curation together.

**Comment by KateRasheed** [comment]
Thank you. I'll get on it.

**Comment by KateRasheed** [comment]
Good day @SvetlanaUP. This study is ready for review:

https://bugsigdb.org/Study_1180

**Comment by KateRasheed** [comment]
Good day @SvetlanaUP . I'm so sorry, I forgot to mention that as at when I was assigned this article, I noticed that a study hadn't been created, hence, I created a new study for it. Thank you.

**Comment by KateRasheed** [comment]
No duplicate. All good with one curation @SvetlanaUP .

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1180 ready for review.

**Comment by KateRasheed** [comment]
Good day @SvetlanaUP . I was going through this article afresh and noticed a hidden experiment. I would appreciate if you can remove the needs review tag so I could quickly add the experiment. Thank you so much.

**Comment by SvetlanaUP** [comment]
@KateRasheed When we claimed our curation for review and got a label "needs review" any edits from this point are not allowed.
However, you can do edit, since this is not your first "second contribution", but please specify here in the comment what you edited after claiming for review.

**Comment by KateRasheed** [comment]
Thank you @SvetlanaUP . Here are the edits made to the curation:
1. Added two experiments
2. Changed the description of experiment 1 signatures.

**Comment by Folakunmi21** [comment]
Hi @KateRasheed @omojokunoluwatomisin10 here is the result of your curation:

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 0
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 0.5
16. All signature sources correctly identified (-1 for each error) (2 points): 1
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (2 points): 2
19. Correct use of NCBI taxonomy (2 points): 2

Total (maximum 23 points): 19.5

1.	Replace Corynebacterium1 with “unclassified corynebacterium”
2.	Figure 2 is not curatable
3.	Correct the alpha diversity measurements for experiment 3 using fig 3C
4.	Correct the statistical test in experiment 1 to MaASlin2 as stated in the figure caption
5.	Correct the statistical test in experiment 3 to Maan U Whitney
6.	There are confounding factors mentioned in this paper
Please make these corrections so that I can mark the study as reviewed. Great group 1 definitions by the way, well done!

**Comment by KateRasheed** [comment]
Thank you so much @Folakunmi21

**Comment by SvetlanaUP** [comment]
Please make corrections @KateRasheed. Well done!

**Comment by KateRasheed** [comment]
@Folakunmi21 Please may I know why figure 2 is not curatable?

**Comment by KateRasheed** [comment]
Good morning @Folakunmi21 . I have made corrections to most of the review. 

Please I need clarifications on figure 2 and the alpha diversity. For figure 2, it is stated in the caption that the analysis was done using LEfSe (although the figure does not look like LEfSe). Should I use "within text result" as the signature source or I should delete the experiment?

For the alpha diversity in figure 3C, it is not describing experiment 2 that is why I left it blank. Should I curate the alpha diversity like that or it's okay for it to be left blank?

**Comment by Folakunmi21** [comment]
Hi @KateRasheed For the alpha diversity, I see what you mean. Please leave it blank. For figure 2, it doesn't show a differential abundance result in my opinion, even within text. I can't see a clear lefse experiment showing differential abundance between 2 groups. It also seems like a correlation analysis more than a differential analysis.

**Comment by KateRasheed** [comment]
@Folakunmi21 Experiment 2 has been deleted and corrections have been made.

**Comment by Folakunmi21** [comment]
@SvetlanaUP changes reviewed
