### ISSUE TITLE
Preconception helminth infection alters offspring microbiota and immune subsets in a mouse model

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#489]
Preconception helminth infection alters offspring microbiota and immune subsets in a mouse model - Donald D Nyangahu – Parasite Immunol.

https://pubmed.ncbi.nlm.nih.gov/32277499/

Full paper: 
[nyangahu2020.pdf](https://github.com/user-attachments/files/17444716/nyangahu2020.pdf)
Supporting Information: it's available at https://onlinelibrary.wiley.com/doi/10.1111/pim.12721

**Comment by Eniola-C** [comment]
Eniola Kolawole

I will like to be assigned to curate this paper. Thank you.

**Comment by KateRasheed** [comment]
Hi @Eniola-C . How is this curation going? Do you need any help with it?

**Comment by codeX-111** [comment]
@Eniola-C 
Hope you're doing okay? We were assigned to reach out to curators to know how the process is going on. I notice that a fellow member reach out to you last week and you're yet to respond. I will be reaching out to you on other platforms that are available here so to be able to reach you.

**Comment by KateRasheed** [comment]
Good day @SvetlanaUP . I can see that @Eniola-C has created a [study](https://bugsigdb.org/Study_1121). However, she's yet to add experiments or signatures. I've reached out to her on slack and I'm awaiting her feedback on how to collaborate with her in completing this curation.

**Comment by SvetlanaUP** [comment]
@codeX-111 @KateRasheed you can work together in finalizing this curation, enjoy!

**Comment by KateRasheed** [comment]
Thank you @SvetlanaUP . I tried accessing the full text but it's requesting I pay in dollars.

**Comment by SvetlanaUP** [comment]
@KateRasheed please see updated original comment, I just added the pdf to download.

**Comment by codeX-111** [comment]
@SvetlanaUP Thank you. I'm sorry for the late response @KateRasheed

**Comment by KateRasheed** [comment]
Good day @SvetlanaUP . This study is ready for review:

https://bugsigdb.org/Study_1121

@codeX-111

**Comment by Buraah** [comment]
Hi @SvetlanaUP,
I want to review this.

**Comment by Buraah** [comment]
Hi @KateRasheed, @codeX-111 
Thank you, this is nicely done. I removed one body site, "Feces", from experiment 4 because only the spleen was used for the immune analysis experiment. Great work!
See: Section 2.2 | Mouse experimental design (pdf).

S/N | Criteria | Total Points | Points Earned
-- | -- | -- | --
1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1
2 | Correct study design | 1 | 1
3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1
4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 0.5
5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1
6 | Contrast groups correctly identified | 1 | 1
7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1
8 | Antibiotic exclusion correctly identified | 1 | 1
9 | Correctly identified sequencing details | 2 | 2
10 | Identified correct statistical test | 1 | 1
11 | Identified MHT correction | 1 | 1
12 | Correctly recorded matched on factors | 1 | 1
13 | Entered correct number of statistical tests per experiment | 1 | 1
14 | All diversity measures identified | 1 | 1
15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1
16 | All signature sources correctly identified (-1 for each error) | 2 | 1
17 | Abundance direction correctly selected | 1 | 1
18 | Members of signatures identified correctly | 2 | 2
19 | Correct use of NCBI taxonomy | 2 | 2
  | TOTAL | 23 | 22.5


</body>
</html>

[Study 1121](https://bugsigdb.org/Study_1121) reviewed @SvetlanaUP

**Comment by KateRasheed** [comment]
Thank you so much for this review. I am really grateful @Buraah @SvetlanaUP .

**Comment by SvetlanaUP** [comment]
It's great to see a good curation done by @KateRasheed  @codeX-111 team effort.

**Comment by codeX-111** [comment]
Thank you @Buraah @SvetlanaUP. Great Work @KateRasheed

**Comment by SvetlanaUP** [comment]
@KateRasheed thanks for spotting this. Please change it. Thank you!

**Comment by KateRasheed** [comment]
It's corrected now. Thank you so much
