### ISSUE TITLE
Effect of gut microbiome modulation on muscle function and cognition: the PROMOTe randomised controlled trial

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#494]
Effect of gut microbiome modulation on muscle function and cognition: the PROMOTe randomised controlled trial – Mary Ni Lochlainn – Nature Communications
https://www.nature.com/articles/s41467-024-46116-y

**Comment by Rukaya-lab** [comment]
@SvetlanaUP Can I be assigned to this one?

**Comment by Rukaya-lab** [comment]
@SvetlanaUP can you please accept my account creation request on Bugsigdb? Thank you

**Comment by cmirzayi** [comment]
Hi @Rukaya-lab. Thank you for your contribution. This was a good start at a curation. Unfortunately I think you missed a few experiments and made a few common mistakes we see from beginning curations. Please see the details below and revise. Also please ask questions on the Slack channel--this is a challenging curation and collaboration is encouraged!

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 |  1|
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 0 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 0 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 0 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 0 |
| 14 | All diversity measures identified | 1 | 0 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 0 |
| 17 | Abundance direction correctly selected | 1 | 0 |
| 18 | Members of Signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 12 |

- Source for Experiment 1 Signature 1 should be the table or figure the signature data were sourced from. In this case, it appears to be Figure 2 (you were not penalized for this).
- Several experiments are missing: Figure S6, Figure S8, Figure S10.
- Condition should be the prebiotic.
- Antibiotic exclusion criterion should be entered specifically as past 3 months not just as "recent"
- In the supplementary methods, it's stated they used linear models that were CLR-transformed.
- I would change matched on to just twin pairs (you were not penalized for this).
- No changes in alpha diversity for the experiment that was curated as stated in the caption for Figure 2.
- Missing many taxa from Figure 2 and some of those present are coded in the wrong direction (P. massiliensis)

**Comment by Rukaya-lab** [comment]
@cmirzayi  I have made more edit now. Can you kindly review it for me? Also, I don't understand why I can not view all the signatures and experiments on the main page, does it take time to populate after I make changes?
I also have a duplicate signature for experiment 2 and I wanted to delete it but it says I do not have the access to do that.

**Comment by cmirzayi** [comment]
Hi @Rukaya-lab I will take a look next week. Thank you for the edits!

**Comment by Rukaya-lab** [comment]
Hello @cmirzayi  and @SvetlanaUP, I still haven't received feedback on my latest edits. Kindly see to this.

**Comment by SvetlanaUP** [comment]
@cmirzayi will get back to you asap. Thank you for your patience, @Rukaya-lab!

**Comment by cmirzayi** [comment]
Hi @Rukaya-lab. Thank you for your patience as I wanted to give your revision the thorough review it deserved. Unfortunately, I think there are still significant problems with the curation. I highly recommend asking questions on Slack and at the office hours for additional help.

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 |  1|
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 0 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 0 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 0 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 0 |
| 14 | All diversity measures identified | 1 | 0 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 2 |
| 17 | Abundance direction correctly selected | 1 | 0 |
| 18 | Members of Signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 14 |

- Condition is still incorrect as noted previously. "Gut microbiome measurement" is not a condition. The condition should be something that the experiment contrasted on. This can be really hard to identify in EFO for dietary conditions but I think you were on the right track with fructose in experiments 3 and 4. I might just go with the general "diet" since EFO doesn't have a lot of good options for supplements or prebiotics.
- Experiment 2/Figure S6 is not contrasting prebiotic vs. placebo. It's contrasting on time points. Also it's three separate experiments (both arms, placebo, prebiotic)
- Statistical test infromation is still incorrect. As noted previously, they used CLR-transformed data and the statistical test was linear models.
- Diversity information for experiments 2, 3, and 4 appear to be incorrect and I'm not sure where this info is coming from.
- The signatures still contain mistakes and missing taxa. For instance, Bifidobacteriaceae was increased in experiment 1 but is not included. There are many taxa missing from each experiment it appears. All taxa in the figures/tables need to be accounted for in the curation.

**Comment by chrisawoke** [comment]
Hi, @Rukaya-lab. How are you doing today? I’d be happy to join you in reviewing your curation and assist wherever you might be facing a challenge.

@SvetlanaUP suggested I offer help if you need any support.

**Comment by MyleeeA** [comment]
Happy to collaborate on this as well @chrisawoke and @Rukaya-lab 
If this is okay @SvetlanaUP

**Comment by Rukaya-lab** [comment]
@chrisawoke Thank you for message. I'll be very glad for your help. Do we need to set up a meeting to discuss? Let me know when you're available.
@MyleeeA Sure, It's okay by me if you want to also help. We can set up the meeting so.
Thank you both.

**Comment by chrisawoke** [comment]
@Rukaya-lab, thanks for the opportunity! Please let me know what time works best for you. Today or tomorrow works for me.

In the meantime, I'm already going through the study.

**Comment by Rukaya-lab** [comment]
@chrisawoke Is 3pm today okay? Or we could do tomorrow by 11am.

**Comment by chrisawoke** [comment]
Hello, @Rukaya-lab. I'm sorry I’m just seeing your message now. I've sent you a message via the Slack channel.

**Comment by MyleeeA** [comment]
Thank you @chrisawoke and @Rukaya-lab 

I am @Mildred Anashie on slack

**Comment by Rukaya-lab** [comment]
@chrisawoke I didn't see your message, my name on slack is Ruqayyah

**Comment by SvetlanaUP** [comment]
@MyleeeA @chrisawoke @Rukaya-lab enjoy your collaboration! Please continue your communication in Slack.

**Comment by MyleeeA** [comment]
Noted @SvetlanaUP 
Thank you 🙏🏾

**Comment by SvetlanaUP** [comment]
@chrisawoke what's the status of this collaboration and curation?

**Comment by MyleeeA** [comment]
Hi @SvetlanaUP 

We are currently working on it
With permission from @Rukaya-lab, I am done making the necessary corrections to the experiment and including the omitted ones while @chrisawoke is adding the signatures

**Comment by chrisawoke** [comment]
Hello, @SvetlanaUP,

As @MyleeeA mentioned, we're almost done. I'm almost finished adding the signatures.

**Comment by SvetlanaUP** [comment]
@MyleeeA @chrisawoke ok, just wanted to check if you are stuck :) Keep up the good work!

**Comment by Rukaya-lab** [comment]
@cmirzayi @SvetlanaUP Thank you for your feedback so far. We have the curation for review now. Kindly go through it.

**Comment by cmirzayi** [comment]
| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 |  1|
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 0 |
| 14 | All diversity measures identified | 1 | 0 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 2 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 1 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 22 |

This is nearly there! Great improvement! You've fixed every outstanding issue that I could find, except I am still noticing some missing taxa and other issues in the signatures--for instance in Experiment 1, Signature 2 Phocea (NCBI taxonomy name: Merdimmobilis) is missing. Similarly, in experiment 1, signature 1 Actinobacteria (NCBI: Actinomycetota) is not actually increased in the prebiotic group (which is why it has a white/empty bar in Figure 2). I think with a review to ensure that the taxa are curated correctly this will be a perfect curation.

**Comment by chrisawoke** [comment]
Oh, great. Thanks so much, @cmirzayi.

We'll fix that ASAP.

Thanks again for the review.

**Comment by MyleeeA** [comment]
Hi @cmirzayi @SvetlanaUP 

Thank you for your patience

We have effected the corrections
@Rukaya-lab @chrisawoke

**Comment by cmirzayi** [comment]
There were some minor outstanding issues with the signatures but I have resolved them. Study marked as reviewed.

**Comment by MyleeeA** [comment]
Thank you again @cmirzayi 🙏🏾

**Comment by chrisawoke** [comment]
Thank you so much, @cmirzayi.
