### ISSUE TITLE
Integrating respiratory microbiome and host immune response through machine learning for respiratory tract infection diagnosis

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#498]
Integrating respiratory microbiome and host immune response through machine learning for respiratory tract infection diagnosis – Hongbin Chen – npj Biofilms and Microbiomes
https://www.nature.com/articles/s41522-024-00548-y

**Comment by MarthaKJ** [comment]
I would like to claim this article for curation 
Name : KISAKYE MARTHA

**Comment by SvetlanaUP** [comment]
Hi @MarthaKJ, have you completed your first contribution https://cunysph.az1.qualtrics.com/jfe/form/SV_1RfUgk72TYmcBHE ?

**Comment by MarthaKJ** [comment]
Yes I completed my first contribution and I submitted the survey already so
am ready for the second contribution

**Comment by MarthaKJ** [comment]
Thank you

**Comment by AleruDivine** [comment]
Hello @MarthaKJ, I hope you're doing well! 
How's your curation process coming along?

I'm finished with my second contribution and would be happy to assist if you're facing any blockers.

Thanks!

**Comment by MarthaKJ** [comment]
Ooh woow thank you so much Aleru I would be glad

**Comment by AleruDivine** [comment]
@MarthaKJ please let me know where you are facing any challenge.

Have you created the study on BugSigDB?

**Comment by SvetlanaUP** [comment]
@AleruDivine no, the study has not been created. You can easily check this out by putting PMID into Search BugSigDB (in the right upper corner on the platform).

@MarthaKJ @AleruDivine please continue your discussion in Slack DM and enjoy your team work!

**Comment by AleruDivine** [comment]
Got it @SvetlanaUP 

I'll send a DM on slack @MarthaKJ

**Comment by MarthaKJ** [comment]
@SvetlanaUP this paper is ready for review 

https://bugsigdb.org/Study_1177
https://bugsigdb.org/Study_1177/Experiment_1/Signature_1
https://bugsigdb.org/Study_1177/Experiment_1/Signature_2

**Comment by Folakunmi21** [comment]
Hello @MarthaKJ @AleruDivine Here is the result of your curation. Please note that I have made the necessary correction to it.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 0
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point):  1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point):1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 2
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (2 points): 2
19. Correct use of NCBI taxonomy (2 points): 2

Total (maximum 23 points): 22

@SvetlanaUP I have graded this applicant's curation and marked the experiments in the study as reviewed. However, I didn't mark the entire study as reviewed because the paper has contamination issues. I have added the quality control tag to it.

**Comment by SvetlanaUP** [comment]
Thanks @Folakunmi21! Please specify contamination issues.

**Comment by SvetlanaUP** [comment]
Ok, I see, a lot of taxa as potential contaminants recorded. Well done, curators and reviewer!

**Comment by Folakunmi21** [comment]
> Thanks @Folakunmi21! Please specify contamination issues.

A lot of the signatures were flagged to be suspected contaminants by the database. Considering that they were isolated from patients with lower respiratory tract infections, should this be ignored and taken as accurate results?

**Comment by SvetlanaUP** [comment]
@Folakunmi21 yes you are right! Please share this curation in Slack and tag Levi and Chloe for advice.

**Comment by AleruDivine** [comment]
Thank you so much for the review @Folakunmi21
