### ISSUE TITLE
Fecal Dysbiosis and Immune Dysfunction in Chinese Elderly Patients With Schizophrenia: An Observational Study

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBcuration#5]
Condition: Schizophrenia
URL: https://www.frontiersin.org/articles/10.3389/fcimb.2022.886872/full

**Comment by Abosed** [comment]
Hi, I would like to work on this article. Esther Ewete

**Comment by Abosed** [comment]
Thank you.

**Comment by cmirzayi** [comment]
@anshikabhatt Hi sorry but this has been assigned to Esther. Please look at the other articles available (ones without the "assigned" tag.

**Comment by Abosed** [comment]
@cmirzayi @ftzohra22 

Trust you're doing great

Kindly help review my study curation.

https://bugsigdb.org/Study_729

Thank you.

**Comment by ftzohra22** [comment]
@Abosed you did good, however it was not complete as majority of the signatures were missing. Here are some other areas you got correct and wrong. Please revise and finish curating all the signatures. 

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 0  (Anytime a study uses matching in selecting their participants it's a case control study, unless stated otherwise)
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0 
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point):1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2
10. Identified correct statistical test (1 point): 1 
11. Identified MHT correction (1 point): 1 
12. Correctly recorded matched on factors (1 point): 0 (Enter the factors on which participants were matched on)
13. Entered correct number of statistical tests per experiment (1 point): 1 
14. All diversity measures identified (1 point): 0 (Richness missing)
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 0 
16. All signature sources correctly identified  (-1 for each error)  (2 points): 1
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): Incorrect
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 0

Total points (maximum 24 points): 14

**Comment by Abosed** [comment]
@ftzohra22 

Thanks for your review, will work on it

**Comment by Abosed** [comment]
I don't understand what you mean by Entered all relevant experiments and no irrelevant experiments.

**Comment by ftzohra22** [comment]
@Abosed it means you added some experiments that were not relevant to the study such as Experiment 3, 4 and 5.

**Comment by Abosed** [comment]
Thank you @ftzohra22 

Please kindly help delete experiment 3,4, and 5.

i tried deleting it during my curation, I couldn't.

**Comment by Abosed** [comment]
@ftzohra22 

Kindly help review my corrections.

https://bugsigdb.org/Study_729

**Comment by Abosed** [comment]
please help delete Experiment 3,4,and 5

**Comment by Abosed** [comment]
@ftzohra22 

Trust you are doing great.
I'm still awaiting your review on my study

**Comment by ftzohra22** [comment]
@Abosed. Please review the paper again according to the comments. Let us know if you have any questions. Thank you. 
- Matched on factors are incorrect in both experiments
- diversity results not correct in both experiments
-statistical test incorrect in experiment 2 (check Figure 2B)
-source in experiment 2 incorrect and all signatures missing in experiment 2. (check Figure2B). You also added 5 seperate signatures for experiment2.

**Comment by Abosed** [comment]
Thank you Fatima,

You stated earlier that there are irrelevant experiments for the study.

Do you mind helping me deleting the irrelevant experiments

**Comment by Abosed** [comment]
Hello @ftzohra22 
Trust you are doing great.

Please kindly review my study.

https://bugsigdb.org/Study_729

**Comment by Abosed** [comment]
Set of questionnaires was used to determine participant enrollment.

Is it true to say the questionnaires was a matched factor? @ftzohra22

**Comment by Abosed** [comment]
@ftzohra22 

Trust you are doing great

Please help review the corrections made and kindly delete Signature 3,4 and 5

**Comment by atrayees** [comment]
I made the following changes:
1. corrected the antibiotics exclusion
2. deleted signatures 3, 4 and 5 from experiment 2
3. corrected the source (Figure 2A) for the two signatures of experiment 1
