### ISSUE TITLE
Metagenome-wide association study of gut microbiome revealed novel aetiology of rheumatoid arthritis in the Japanese population

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#50]
Initiated at https://bugsigdb.org/Study_540. Note - there are no guarantees that information already entered here (such as study design) is correct, so please proceed as you would for a new study with no information pre-entered.

**Comment by EuniceMiriti** [comment]
Kindly assign me this issue to curate.

**Comment by EuniceMiriti** [comment]
Hello, I am unable to open the study when I click the open button. Also on the PMID, I have made attempts to add and it tells me to make it unique.

**Comment by cmirzayi** [comment]
@EuniceMiriti Please don't make a new study. Instead add to the existing study here which already has the PMID: https://bugsigdb.org/Study_540

**Comment by EuniceMiriti** [comment]
@cmirzayi Okay, well noted. Thank you

**Comment by EuniceMiriti** [comment]
When I open the existing study 540, seems different from the one I had curated as on my BugSigDB account, it is study 615. Is that a problem?

**Comment by claregri** [comment]
Hi Eunice, good start with this assignment! Figure 1 is not really curatable for our database - I would suggest curating Table 1 instead. Please see my comments below.
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 0 (observational cross-sectional not case control would be more appropriate)
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 0 (hint: check methods)
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2
10. Identified correct statistical test (1 point): 0 (this should have just been PERMANOVA - papers often reference many statistical tests, but the one that your experiment in particular is using is often found in the caption of the figure/table that you're curating)
11. Identified MHT correction (1 point): 0
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): not scored due to incorrect curation (also, please write out the title of the source ie. Figure 4 instead of putting a link in the source field)
17. Abundance direction correctly selected (1 point): not scored due to incorrect curation
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): not scored due to incorrect curation
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): not scored due to incorrect curation

Total (maximum 24 points): not scored due to incorrect curation

**Comment by EuniceMiriti** [comment]
Greetings,

I am happy to get feedback  on the review. I will definitely the necessary
changes and get back to you. Thank you.

Kind regards,

Eunice.

**Comment by EuniceMiriti** [comment]
Hello @claregri I have gone through your comments and made changes where required. I have a few questions, I had made a mistake of curating figure 1 instead of table one 1, while making the changes, I noticed that all clades increased in RA samples as compared to control. I wanted to deleted signature 2as there was no significant decrease but I could not as only administrators are able to do that. Secondly I noticed that when curating signature 1,there are microbes which indicated that they are potential contaminants, is this one a problem? The ones in orange, I was not be able to find them in the NCBI taxonomy browser. Lastly, after the review done, I did not receive any score. I am requesting if you could review my work and changes made for a score. Thank you

**Comment by claregri** [comment]
Hi Eunice, 

Thanks for making those updates! I deleted signature 2 for you. Potential contaminants is not an issue for you to deal with :) I noticed that you updated the significance threshold to 0.00001 but it should remain 0.05. see my updated scoring below.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2
10. Identified correct statistical test (1 point): 1 
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 2
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 2
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 0 (make sure to really check your spelling when looking these up - I was able to find both of the highlighted taxa in the NCBI database)

Total (maximum 24 points): 22

**Comment by EuniceMiriti** [comment]
@claregri Thank you for the feedback. I  appreciate. I have made the changes on the taxa.

**Comment by cmirzayi** [comment]
Seems like this is good so I'm closing it.

**Comment by EuniceMiriti** [comment]
@mcarlsn NS means Not Scored, right? I think from @claregri comments there was a score below. Is this okay?

**Comment by mcarlsn** [comment]
@EuniceMiriti thank you for posting! I updated the label.
