### ISSUE TITLE
Inactivation of the MSTN gene expression changes the composition and function of the gut microbiome in sheep

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#503]
Inactivation of the MSTN gene expression changes the composition and function of the gut microbiome in sheep – Chenchen Du – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-022-02687-8

**Comment by Mabwas** [comment]
good day, please i would love to work on this

**Comment by Mabwas** [comment]
Thanks @SvetlanaUP , I would start working on it immediately

**Comment by MyleeeA** [comment]
Hi @Mabwas 

Trust you are doing good
I would like to know how your curation is going and if you are experiencing any blockers, willing to collaborate with you on this

Thank you 🙏🏾

**Comment by KateRasheed** [comment]
Good morning to you @Mabwas . I see that you are yet to create a study for this article. Please let us know if you are experiencing a blocker. We are ready to help in any way.

**Comment by MyleeeA** [comment]
Hi @KateRasheed can we collaborate on this?
The more the merrier 😄

@SvetlanaUP is this okay

**Comment by SvetlanaUP** [comment]
@KateRasheed is the original curator who will ask/accept assistance if needed.

**Comment by KateRasheed** [comment]
Thank you @SvetlanaUP . I would have love to collaborate with you on this @MyleeeA but I can only see one experiment in this study.

**Comment by MyleeeA** [comment]
That’s Okay @KateRasheed 

I see more than one experiment in this study though 

There’s a mention of four groups, there are results in the supplementary information please check that

**Comment by KateRasheed** [comment]
Hi @MyleeeA . I saw it while working on it. I'm done working on experiment 1 and I would like to carry on with experiment 2. I'll really appreciate a peer review when I'm done.

**Comment by MyleeeA** [comment]
Okay

I’ll be happy to do that
Just let me know when it’s ready for a peer review @KateRasheed

**Comment by KateRasheed** [comment]
Good day @SvetlanaUP . This study is ready for review:

https://bugsigdb.org/Study_1182

@MyleeeA

**Comment by KateRasheed** [comment]
Hello @Mabwas. Good day to you. I'm so sorry about the laptop issues. We just finished the study. Can you pick another paper.

**Comment by MyleeeA** [comment]
Thank you for tagging me to this @KateRasheed 
I already gave peer review on slack and we collaborated in editing it

It was great working with you, Thank you @SvetlanaUP for assigning me alongside Kate

**Comment by SvetlanaUP** [comment]
@AleruDivine https://github.com/AleruDivine could you please do review of this curation?

**Comment by AleruDivine** [comment]
Absolutely @SvetlanaUP Thank you 😊

**Comment by AleruDivine** [comment]
Well done on your curation! 👏👏 @KateRasheed @MyleeeA  You have done a great job with this.
I have a few observations and suggestions for your consideration:

1. **Group 1 definition**: Including the full meaning of MSTN (Myostatin) in the definition would be very helpful. When we write the full form of abbreviations the first time they appear, it helps with clarity for potential readers.
2. **MHT correction**: Since LEfSe does not perform multiple hypothesis testing, the MHT field should be marked as "NO" for experiments 2 and 4.
3. **Omitted signatures**: Could you clarify the omission of signatures from figure 2C and Supplementary figure 2C for experiments 1 and 3, respectively? My understanding is that we are to curate all taxa, regardless of their taxonomic levels, and I think we should in this case.

Thank you so much!

**Comment by KateRasheed** [comment]
Thank you so much for the review @AleruDivine . All corrections have been made.

Thank you for pointing out the figures, it has been added too.

**Comment by MyleeeA** [comment]
Thank you so much @AleruDivine 😊

**Comment by AleruDivine** [comment]
Thank you both! @KateRasheed @MyleeeA 
Good morning @SvetlanaUP, I believe this review is complete. 
Thank you so much!
