### ISSUE TITLE
Changes in the nasopharyngeal and oropharyngeal microbiota in pediatric obstructive sleep apnea before and after surgery: a prospective study 

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#509]
Changes in the nasopharyngeal and oropharyngeal microbiota in pediatric obstructive sleep apnea before and after surgery: a prospective study – Lucheng Fang – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-024-03230-7

**Comment by Somali10** [comment]
Mohamed

**Comment by TheTosin** [comment]
Hello @Mohamed, please feel free to reach out if you need any assistance in curating the article. I would be happy to collaborate to make the process smoother and more efficient. You can reach me as “Adeshile Oluwatosin” on slack.

**Comment by vandana123maddi** [comment]
Hi @SvetlanaUP please do assign me this 
😃 Seems like other new intresting topic to research

**Comment by TheTosin** [comment]
Hi @vandana123maddi This paper is currently assigned to Mohammed. 
It has the assigned label on it already.
You might need to pick another issue/article.

**Comment by SvetlanaUP** [comment]
Hi @vandana123maddi, this paper is under curation (see label: "assigned"). Please select other "paper to curate".

**Comment by MyleeeA** [comment]
Hi @Somali10 

Trust your curation is going well and you are doing well 

I am currently done with my second contribution and I am awaiting grading, I’m available to help if you are experiencing any blockers

Thank you 🙏🏾

**Comment by SvetlanaUP** [comment]
@TheTosin @MyleeeA @Somali10 please finalize this curation together,

**Comment by TheTosin** [comment]
Noted @SvetlanaUP i will begin immediately.

**Comment by MyleeeA** [comment]
Okay @SvetlanaUP 
Thank you 🙏🏾

**Comment by TheTosin** [comment]
@SvetlanaUP we have not heard from @Somali10 .
We need permission to edit directly.

Can we go ahead?
The study has not been created at all.

**Comment by MyleeeA** [comment]
@TheTosin I think this is a nice idea for you and I to go ahead with the curation we were to collaborate on with @Somali10  
But maybe we can wait it out a bit, until tomorrow. Hopefully we would get a response and pending @SvetlanaUP reply to this.

What do you think?

**Comment by SvetlanaUP** [comment]
Enjoy your team work! @MyleeeA @TheTosin

**Comment by TheTosin** [comment]
@MyleeeA let us get to work.

**Comment by MyleeeA** [comment]
Thank you @SvetlanaUP

**Comment by TheTosin** [comment]
Hello @SvetlanaUP This study is ready for review

https://bugsigdb.org/Study_1181

**Comment by SvetlanaUP** [comment]
@AleruDivine https://github.com/AleruDivine could you please do review of this curation?

**Comment by AleruDivine** [comment]
Well done on this curation! 👏👏 @TheTosin @MyleeeA . I remember this study 😅 and you both did a great job with the curation.
I have a few observations and corrections for you to consider:

**Neisseria in Signature 2 (Experiment 3, Figure 5B):**
Neisseria was increased compared to Groups B and C but decreased compared to Group D. For this reason, curating it as "decreased" might not be the best approach.
Please also check Experiment 7 (Figure S5B) for a similar issue.

**Prevotella in Experiment 8 (Figure S5C):**
Prevotella was decreased compared to mild and moderate severity groups but increased compared to the severe group. Curating it as "decreased" for a one-to-all comparison may not fully capture this.
**Suggestion:** Bring this up in the next office hours for clarification on how to approach this type of result.

**Experiment 9 (Figure 6F – Preoperative vs. Postoperative OSA patients):**
The curated signatures appear inaccurate.
Please check again. Based on the figure, Porphyromonas and Treponema seem to be increased in Postoperative OSA patients, while Moraxella appears decreased.

**Statistical Test for Experiment 9:**
The correct test should be Mann-Whitney (Wilcoxon).
Refer to this excerpt: "The Mann-Whitney test was employed to assess the presence of a significant difference between the two groups in relation to continuous variables."

**Group Name for Experiment 10:**
The name for Group 0 and its signature descriptions need correction.
"Non-Obstructive Sleep Apnea (OSA) Severe" is contradictory since severity does not apply to individuals without OSA.

**Signature Correction in Experiment 12 (Signature 1):**
"Ruminococcus2" should be corrected to "Ruminococcus."

**Sample Sizes for Experiments 1, 3, 5, and 6:**
I understand there were 10 individuals per severity group, with samples collected from different sites (10 samples per site). For example:
Experiment 1: Non-OSA Group A would have 10 samples from the oropharynx site, 10 from the surface of the palatine tonsil, 10 from the palatine tonsillar capsule, and 10 from the adenoid/nasopharynx site.
In this case, Group 1 would have a sample size of 10, and Group 0 would have a total of 30 samples. Let me know what you think.

I hope these observations and suggestions are helpful. I look forward to hearing your thoughts on this.
Thank you so much!

**Comment by TheTosin** [comment]
Hello @AleruDivine 
Thank you for the review

We would get on it

**Comment by MyleeeA** [comment]
Thank you so much @AleruDivine 

Experiment 9 and 10 corrections effected, I understand the concern with using severe for the None OSA group.

The sample sizes for the contrasts done on the parts wasn’t stated that’s why we left those experiments without sample size. In my opinion the combination (30 vs 10) can only apply to the contrasts done on the groups (None, Mild, Moderate and Severe) so I agree with @TheTosin that this should still be left blank

**Comment by AleruDivine** [comment]
Thank you so much for going through my suggestions. 
I’d suggest clarifying the curation of Neisseria and Prevotella during office hours. Or has this been confirmed by a mentor @TheTosin @MyleeeA 

Regarding the sample sizes, I completely understand, it should be left blank since it was not exactly specified. 

Well done again you both 👏🏽👏🏽

**Comment by KateRasheed** [comment]
@AleruDivine Can you clarify the curation of Neisseria and Prevotella during office hours tomorrow so we can close this curation.

Thank you so much.

**Comment by AleruDivine** [comment]
Yes, I’ll do that.
Thanks!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1181 reviewed.
