### ISSUE TITLE
HIV-associated gut dysbiosis is independent of sexual practice and correlates with noncommunicable diseases

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#51]
Initiated at https://bugsigdb.org/Study_466. Note - there are no guarantees that information already entered here (such as study design) is correct, so please confirm the information yourself as you would for a new study with no information pre-entered.

**Comment by Tsoure** [comment]
I will curate this.

**Comment by Tsoure** [comment]
Hello mentors, I believe you are doing well today. Kindly review my curation at https://bugsigdb.org/Study_466. I would appreciate your feedback. Thank you.

**Comment by cmirzayi** [comment]
Hi @Tsoure Thank you for your work on this. Unfortunately there are some critical errors in this curation that make it difficult to score. The condition should be the disease of interest. Separate experiments should be entered for each contrast. Sample sizes appear to be incorrect. The 16S variable region is incorrect. Figures 1 and 3 are difficult to curate--instead the same information appears to be available in Supplemental Tables 4-6 in an easier format.  I highly recommend reviewing the videos provided for proper curation and asking questions in the Slack channel. For now, this curation is unscored due to being incomplete.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1 
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 0
5. Condition entered according to contrast (correct EFO ontology) (1 point): 0
6. Contrast groups correctly identified (1 point): 0
7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point): Not scored from here on due to incorrect curation
8. Antibiotic exclusion correctly identified (1 point):
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points):
10. Identified correct statistical test (1 point):
11. Identified MHT correction (1 point):
12. Correctly recorded matched on factors (1 point):
13. Entered correct number of statistical tests per experiment (1 point):
14. All diversity measures identified (1 point):
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point):
16. All signature sources correctly identified  (-1 for each error)  (2 points):
17. Abundance direction correctly selected (1 point):
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points):
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points):

Total (maximum 24 points): Not scored due to incorrect and missing curation

**Comment by Tsoure** [comment]
Hello @cmirzayi I'm so sorry about that. Thank you for the review

**Comment by Aiysha689** [comment]
Hello, @lwaldron @cmirzayi this study already exist in Bugsigdb database,here the link to the original curation of the study https://bugsigdb.org/Study_543 
" https://bugsigdb.org/Study_466 and https://bugsigdb.org/Study_549 "are duplication of the study.

**Comment by atrayees** [comment]
I have checked all the studies and they were indeed duplicates. Study 466 and 549 have been deleted.
