### ISSUE TITLE
Mild atopic dermatitis is characterized by increase in non-staphylococcus pathobionts and loss of specific species

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#510]
Mild atopic dermatitis is characterized by increase in non-staphylococcus pathobionts and loss of specific species – Lize Delanghe – Scientific Reports

https://www.nature.com/articles/s41598-024-74513-2

**Comment by Joiejoie1** [comment]
I want to curate this !

**Comment by Rahila-me** [comment]
Good morning @Joiejoie1  @SvetlanaUP ,  joy please I am open for collaboration i just wanted to know if you need help to finish up this paper. Waiting for your reply.. Thank you

**Comment by Joiejoie1** [comment]
> Good morning @Joiejoie1 @SvetlanaUP , joy please I am open for collaboration i just wanted to know if you need help to finish up this paper. Waiting for your reply.. Thank you

Hi @Rahila-me . Thanks for reaching out. I am done with the paper. It needs review. Is there anyway you can help with the review?

**Comment by Joiejoie1** [comment]
This is the link for review: https://bugsigdb.org/Study_1084

Guys kindly review. Thanks

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_108 ready for review.

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP, can I review this?

**Comment by Scholarpat** [comment]
Hi @Joiejoie1,

This curation requires some improvements. Although there were a few correct entries, some areas need further attention. Kindly review the points listed below and make the necessary corrections:

*CURATION RESULTS:*

| S/N | Criteria                                                           | Total Points | Points Earned |
|-----|--------------------------------------------------------------------|--------------|---------------|
| 1   | All elements marked "Needs review" (none "Incomplete")             | 1            | 0.5             |
| 2   | Correct study design                                                | 1            | 1             |
| 3   | Entered all relevant experiments and no irrelevant experiments      | 1            | 0             |
| 4   | Body site correctly identified (i.e. does not include multiple sites)| 1            | 0             |
| 5   | Condition entered according to contrast (correct EFO ontology)      | 1            | 0.5             |
| 6   | Contrast groups correctly identified                                | 1            | 0.5             |
| 7   | Groups correctly labeled as 1 and 0 (1=cases, 0=controls)           | 1            | 0.5             |
| 8   | Antibiotic exclusion correctly identified                           | 1            | 0.5             |
| 9   | Correctly identified sequencing details                             | 2            | 1             |
| 10  | Identified correct statistical test                                 | 1            | 0             |
| 11  | Identified MHT correction                                           | 1            | 0.5             |
| 12  | Correctly recorded matched on factors                               | 1            | 0             |
| 13  | Entered correct number of statistical tests per experiment          | 1            | 0             |
| 14  | All diversity measures identified                                   | 1            | 0             |
| 15  | Diversity results correctly entered as increased/decreased/unchanged| 1            | 0             |
| 16  | All signature sources correctly identified (-1 for each error)      | 2            | 0             |
| 17  | Abundance direction correctly selected                              | 1            | 0             |
| 18  | Members of signatures identified correctly                          | 2            | 0             |
| 19  | Correct use of NCBI taxonomy                                        | 2            | 0             |

*Total = 5/23*

### Notes for correction:

- There are 3 distinct experiments to curate:
  - mildAD vs Healthy
  - mildAD vs Healthy under 12 years old
  - mildAD vs Healthy above 12 years old
- Signatures can be found in *Figure 3a. Be sure to curate **only significant taxa*.
- For healthy participants, skin swabs were taken from the elbow bend. For AD patients, swabs were taken from a selected lesion site (which included different skin surface for each participant). *Skin* is a more correct term since they refer to different skin surfaces and not just the elbow.
- There was no antibiotic exclusion for the cases, but healthy participants were excluded for antibiotic use. Note this on the discussion page.
- *Maaslin2* was used for differential abundance analysis.
- Leave the *LDA* field blank if it doesn't apply—no need to enter a value of zero.
- For alpha diversity, only *two measures* were used: *observed diversity* (richness) and *Inverse Simpson index*.

Please make the necessary corrections and ask for a second review.

**Comment by Joiejoie1** [comment]
> Hi @Joiejoie1,
> 
> This curation requires some improvements. Although there were a few correct entries, some areas need further attention. Kindly review the points listed below and make the necessary corrections:
> 
> **CURATION RESULTS:**
> 
> S/N	Criteria	Total Points	Points Earned
> 1	All elements marked "Needs review" (none "Incomplete")	1	0.5
> 2	Correct study design	1	1
> 3	Entered all relevant experiments and no irrelevant experiments	1	0
> 4	Body site correctly identified (i.e. does not include multiple sites)	1	0
> 5	Condition entered according to contrast (correct EFO ontology)	1	0.5
> 6	Contrast groups correctly identified	1	0.5
> 7	Groups correctly labeled as 1 and 0 (1=cases, 0=controls)	1	0.5
> 8	Antibiotic exclusion correctly identified	1	0.5
> 9	Correctly identified sequencing details	2	1
> 10	Identified correct statistical test	1	0
> 11	Identified MHT correction	1	0.5
> 12	Correctly recorded matched on factors	1	0
> 13	Entered correct number of statistical tests per experiment	1	0
> 14	All diversity measures identified	1	0
> 15	Diversity results correctly entered as increased/decreased/unchanged	1	0
> 16	All signature sources correctly identified (-1 for each error)	2	0
> 17	Abundance direction correctly selected	1	0
> 18	Members of signatures identified correctly	2	0
> 19	Correct use of NCBI taxonomy	2	0
> **Total = 5/23**
> 
> ### Notes for correction:
> * There are 3 distinct experiments to curate:
>   
>   * mildAD vs Healthy
>   * mildAD vs Healthy under 12 years old
>   * mildAD vs Healthy above 12 years old
> * Signatures can be found in **Figure 3a**. Be sure to curate only significant taxa.
> * For healthy participants, skin swabs were taken from the elbow bend. For AD patients, swabs were taken from a selected lesion site (which included different skin surface for each participant). **Skin** is a more correct term since they refer to different skin surfaces and not just the elbow.
> * There was no antibiotic exclusion for the cases, but healthy participants were excluded for antibiotic use. Note this on the discussion page.
> * **Maaslin2** was used for differential abundance analysis.
> * Leave the _LDA_ field blank if it doesn't apply—no need to enter a value of zero.
> * For alpha diversity, only **two measures** were used: _observed diversity_ (richness) and _Inverse Simpson index_.
> 
> Please make the necessary corrections and ask for a second review.

Thanks @SvetlanaUP I'll make the necessary corrections.

**Comment by Joiejoie1** [comment]
> Hi @Joiejoie1, I'll be very happy to collaborate on reviewing and making the necessary corrections in this study if that's okay with you.
> 
> Thank you so much!

Yes please @AleruDivine , Let's collaborate. Thank you

**Comment by AleruDivine** [comment]
Okay @Joiejoie1 what is your slack username so i can send a message

**Comment by Joiejoie1** [comment]
> Okay @Joiejoie1 I'll send a message on Slack Thank you!

Greetings @SvetlanaUP , I trust you are doing great, @AleruDivine would like to collaborate with me on this can she also be assigned to it. Thanks

**Comment by Joiejoie1** [comment]
Hi @SvetlanaUP, @Scholarpat,  @AleruDivine and I are done with curating the paper:  https://bugsigdb.org/Study_1084. It is ready to be graded. Thanks

**Comment by SvetlanaUP** [comment]
@Scholarpat please see corrections here, thanks!

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP, in experiment 3, signature 2, I corrected the signature source from Fig **3b** to **3a**. The curation is now complete. Thank you, and well done @Joiejoie1 and @AleruDivine!

**Comment by AleruDivine** [comment]
Thank you so much for the review 😊 @Scholarpat

**Comment by Joiejoie1** [comment]
Thank you @Scholarpat and @SvetlanaUP for the review. 😊
