### ISSUE TITLE
Characterization of the Gut and Skin Microbiome over Time in Young Children with IgE-Mediated Food Allergy

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#528]
Characterization of the Gut and Skin Microbiome over Time in Young Children with IgE-Mediated Food Allergy – Michèle S. Roth – Nutrients
https://www.mdpi.com/2072-6643/16/22/3942

**Comment by AleruDivine** [comment]
Good morning @SvetlanaUP I’d like to be assigned this paper. Thank you so much!

**Comment by AleruDivine** [comment]
Good morning @SvetlanaUP 
I'd like to submit this study for review 
Link: https://bugsigdb.org/Study_1238

**Comment by AleruDivine** [comment]
Good morning @KateRasheed, please can you review this paper?
Thank you!

**Comment by KateRasheed** [comment]
Good morning @AleruDivine . Yes please. Thank you.

**Comment by KateRasheed** [comment]
Good afternoon @AleruDivine . Welldone on this curation. Here are few things to note in this study:

- For experiment 1, Shannon is unchanged . See this: "We observed a higher alpha diversity (Shannon) in patients’ feces samples at t1 and in patients’ forearm samples at t0 and t1 compared with controls (betta test; feces t1 p = 0.0048; forearm t0 and t1 p < 0.0001). The alpha diversity of feces samples at t0 was similar between patients and controls (betta test: t0 p = 0.4113)"
- The study design should be a prospective cohort study since they looked at "patients at enrollment" and "patients at followup".
- There are additional experiments in Supplementary Figure 6 and Fig. 4 (what do you think of this?)

Thank you so much.

**Comment by AleruDivine** [comment]
Thank you for the review @KateRasheed I have made corrections on the alpha diversity for experiment 1 and the study design.

I didn’t curate Figure 4 and Figure S6 because they show correlations between microbial abundances and allergy, not directly comparing microbial abundance between groups like “nut allergy” and “no nut allergy.”

For example, in the figures, you see both positive and negative correlations for nut allergy and the same for no nut allergy across all body sites. It would have made sense if we had a column for one condition (e.g., nut allergy) and compare cases (nut allergy) to controls (no nut allergy), identifying taxa that are increased or decreased in cases relative to controls using the colors.

I may be missing something and totally wrong.

Please what do you think? I honestly don't know how I'd curate this.

Thank you so much!

**Comment by KateRasheed** [comment]
Okay. In my opinion, it's actually curatable. If you look below, you would see the columns for each. 
For Fig. 4, only Collinsella had significant increase for feces and elbow between low and high. 
See this too: "High total IgE positively correlated with a high abundance of the genus Collinsella in the gut and skin microbiome when stratifying according to number of allergies/sensitization" 

@AleruDivine

**Comment by AleruDivine** [comment]
what would be the contrast groups? @KateRasheed

**Comment by KateRasheed** [comment]
No-nut vs Nut
Low IgE vs High IgE 

@AleruDivine

**Comment by AleruDivine** [comment]
Thank you Kate. 
Also, when you say only Collinsella had significant increase for feces and forearm between low and high and nut vs no-nut, does this mean this is the only curatable signature?

**Comment by KateRasheed** [comment]
Yes please. The p-values are on both contrast groups that's why it's the only curatable signature.

Nut vs no-nut is for feces and elbow.

**Comment by AleruDivine** [comment]
Thank you so much!
I'll complete the curation ASAP

**Comment by AleruDivine** [comment]
This curation is complete @KateRasheed.
Please give it a second review.

Thank you so much and have a great weekend!

**Comment by KateRasheed** [comment]
Good afternoon @AleruDivine. Thanks for this curation. 
For experiment 13 and 14 group 1 definition, please add "or equal to" after greater than.

**Comment by AleruDivine** [comment]
Added!
Thank you @KateRasheed

**Comment by KateRasheed** [comment]
Good afternoon @SvetlanaUP . This review is complete

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1238 reviewed.
