### ISSUE TITLE
Gut Microbiota Dysbiosis and Diarrhea in Kidney Transplant Recipients

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDBcuration#55]
Link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6301138/
Condition: Diarrhea in kidney transplant patients

**Comment by joy-commits** [comment]
Hello @ftzohra22
Please, can I be assigned this study?
Thank you

Name: Ufuoma Ejite

**Comment by joy-commits** [comment]
Hello @ftzohra22 @lwaldron @cmirzayi 
I'm done with this study
https://bugsigdb.org/Study_728
Please, kindlt review

**Comment by cmirzayi** [comment]
Hi @joy-commits This is a good start; however, I believe you missed the supplement which contains several subgroup analyses (i.e. additional experiments) that could be curated. Specifically Tables S1, S2, S4, S5, S6, S7, S10, and S11 have significant results that could be curated. Many of these tables are perhaps superfluous to the figure you curated; however I do think some of them are important subgroups to include (such as the antibiotics excluded comparison). Overall, I think tables S1 (time matched analysis), S2 (antibiotics excluded analysis), and S7 (before and after diarrhea analysis) are all important analyses that are worth curating.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 0 (cohort study)
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0 (many curatable tables in the supplement)
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 0 (missing several important subgroup analyses)
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 2
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 2

Total (maximum 24 points): Not scored due to incomplete curation

**Comment by cmirzayi** [comment]
Hi @joy-commits  Thank you so much for your contributions to the BugSigDB project. I wanted to check to see if you wanted to finish this curation. I understand that with the Outreachy applicant selection process over, you may no longer wish to help out with BugSigDB or have other priorities right now.

If not, I will open it up to other curators to finish the curation.

**Comment by atrayees** [comment]
Added the rest of the curatable experiments along with their signatures, and corrected the signatures of all other already curated Experiments.
