### ISSUE TITLE
Smoking may lead to marginal bone loss around non-submerged implants during bone healing by altering salivary microbiome: a prospective study

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#60]
https://pubmed.ncbi.nlm.nih.gov/28844190/ (PDF attached)
[PMID-28844190.pdf](https://github.com/waldronlab/BugSigDBcuration/files/11213730/PMID-28844190.pdf)

**Comment by chioma-grace** [comment]
Please I want to curate this paper. Please assign me to me @lwaldron, @ftzohra22, @cmirzayi. Thank you

**Comment by shallockh02** [comment]
I Kelvin Joseph can curate this paper

**Comment by shallockh02** [comment]
Yes am intrested

**Comment by chioma-grace** [comment]
Hello @lwaldron, please one of the tables on MBL (marginal bone loss) to be curated is not in the PDF file of this paper. Rather it is in a site that have to be paid for. 

I have been able to curate two experiments and for signatures. 

Please kindly review. Thank you.

**Comment by ftzohra22** [comment]
@chioma-grace the supplmental table reporting species association with MBL is not exactly a differential abundance result. Those are results showing correlation which we don't need to curate. 
And could you please link your bugsigdb curation here. I'm unable to find it on the wiki using the PMID or the title of the paper. Thanks!

**Comment by chioma-grace** [comment]
Thank you @ftzohra22, below is the link to the curation.
https://bugsigdb.org/Study_634/Experiment_3

**Comment by chioma-grace** [comment]
Hello @ftzohra22, thank you.
Attached below is the link to the Curation.

https://bugsigdb.org/Study_634

**Comment by ftzohra22** [comment]
Experiment 3 deleted.

**Comment by chioma-grace** [comment]
Thank you @ftzohra22.
Please kindly review.
Best regards.

**Comment by chioma-grace** [comment]
Thank you @ftzohra22.
Please kindly review.
Best regards.

**Comment by chioma-grace** [comment]
Greetings Fatima,
Please this just crossed my mind, though species association with MBL is not exactly a differential abundance result. I hope it is still proper to curate experiment 2 to emphasize the second body part without any signature.

**Comment by shallockh02** [comment]
Hello @ftzohra22 I have been trying to add a signature to my curation [#62](https://bugsigdb.org/Study_635)

**Comment by shallockh02** [comment]
But it's not reflecting on the page

**Comment by shallockh02** [comment]
they all reflected and they have been duplicated would you help remove the signatures 3,4,5,6

**Comment by chioma-grace** [comment]
Greetings @ftzohra22 
Please I am waiting for a review on this curation.
Thank you.

**Comment by shallockh02** [comment]
I was already assigned the curation @chioma-grace

**Comment by ftzohra22** [comment]
@chioma-grace Thank you for your efforts on the paper. Here are the notes and corrections I made in each section and field:
Study design: Studies usually follow only one type of design. In this case, the title says this was a prospective cohort study.
Sequencing platform: This was slightly tricky as they didn't mention directly on the text, but added a superscript on the part where they say they used a sequencing platform. On the 3rd page of the PDF, towards the bottom right the footnote has the name of the platform-Ilumina.
Signatures: We can add 2 signatures for this study instead of 4, because they used only one statistical test to report differential abundance test (i.e. Mann-Whittney U test). Also Figure 3 is not curatable as it is reporting relative abundance only, not differential abundance. Only Figure 4 and Table 2 has results that are showing signficant differences in bacteria. We can put together these results in just 2 signatures showing increase and decrease in smoker vs. non-smokers as they are between same groups using same statistical test. 
I've also deleted experiment 2 in addition to Signature 3 and 4 as it was not necessary. 

Please review the corrections I made on bugsigdb. Thank you.

**Comment by chioma-grace** [comment]
Thank you so much @ftzohra22 .
I appreciate your response. I will effect the changes as soon as possible. 
Best Regards.

**Comment by ftzohra22** [comment]
I already made the corrections and changes. You can review it so that you understand what I did for future reference.

**Comment by chioma-grace** [comment]
Thank you so much for your efforts. I really appreciate it. 
Best Regards.
