### ISSUE TITLE
Sociodemographic variation in the oral microbiome

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#62]
https://pubmed.ncbi.nlm.nih.gov/31151886/

**Comment by atrayees** [comment]
I would love to curate this paper!
Atrayee Samanta

**Comment by Cindy-erella** [comment]
Assign me this one. Cindy

**Comment by shallockh02** [comment]
can I curate this study?

**Comment by lwaldron** [comment]
Sorry for the slow reply - I assigned @shallockh02 since @Cindy-erella 's request was two weeks old - @Cindy-erella are you still interested in a new assignment? I can find another.

**Comment by ftzohra22** [comment]
@shallockh02 I deleted the duplicate signatures 3,4,5,6. what do you mean by you are unable to add signatures?

**Comment by shallockh02** [comment]
Initially they were not reflecting on the curation page so I kept on adding
new signatures and today all the numerous attempts I had filled they
finally appeared duplicated four times.
Thanks for the response

**Comment by shallockh02** [comment]
Hello @lwaldron @ftzohra22 @cmirzayi finished my curation on [#62](https://bugsigdb.org/Study_635) would you help review the curation.

**Comment by shallockh02** [comment]
@claregri 635

**Comment by claregri** [comment]
study 635
Hi there, good start on this paper - it's a little difficult to curate. Please see my scoring and comments below. You actually need to curate from the Supplementary material spreadsheet, as I don't see any documented differential abundance for the smoking comparison groups in the text. In that spreadsheet you'll find there are a number of different comparisons that should each have their own experiment (not just smoking vs nonsmoking).
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 0 (this should be "smoking behavior")
6. Contrast groups correctly identified (1 point): 1 (but I would update the group 1 definition because as of now it is not the definition of group 1)
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 0
9. Correctly identified sequencing details (2 points):  1 (sequencing platform should be Illumina only)
10. Identified correct statistical test (1 point): 0 (should be edgeR)
11. Identified MHT correction (1 point): 0 (references to FDR valus throughout the paper means that the p-values were corrected)
12. Correctly recorded matched on factors (1 point): 0 (those were not matching factors - could argue that they were confounders adjusted for in the model however)
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 0 (should be Chao1 only)
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): not scored due to incorrect curation
17. Abundance direction correctly selected (1 point): not scored due to incorrect curation
18. Members of Signatures identified correctly (2 points): not scored due to incorrect curation
19. Correct use of NCBI taxonomy (2 points): not scored due to incorrect curation

**Comment by shallockh02** [comment]
Hello let me get to it

**Comment by shallockh02** [comment]
@claregri this is the pdf file I was able to access [Sociodemographic variation in the oral microbiome](https://sci-hub.se/10.1016/j.annepidem.2019.03.006)  am having troubles locating the supplementary information. can you help me out?

**Comment by shallockh02** [comment]
can I list is a contribution on the outreachy page?

**Comment by claregri** [comment]
Hi there, here's the link to the online version which includes links to the supplementary data! https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6626698/

**Comment by shallockh02** [comment]
Thanks a lot @claregri

**Comment by shallockh02** [comment]
Hello @claregri how do I go ahead with the curation it has over 1000 entries on the spreadsheet could you shed some light on how am supposed to tackle the curation

**Comment by claregri** [comment]
Hi there, you'll see that there's a column for the model type in the spreadsheet. Since you're looking at smoking status, there are a few sets of outcomes for smoking status, but I would curate the smoking status differential taxa for the model that's adjusted for age and sex (and put those factors in the confounders field of the experiment). If the log FC column is negative then it's decreased in the smoking group and vice versa.

**Comment by shallockh02** [comment]
so I write experiment for the same condition for the case smoking status and match on age and sex for the first experiment then education for the second experiment, then family income for the third and so forth???

**Comment by shallockh02** [comment]
Hello @claregri can you check the progress of the curation? [635](https://bugsigdb.org/Study_635)

**Comment by shallockh02** [comment]
Hello @cmirzayi @lwaldron @ftzohra22  can you check the progress of the curation?

**Comment by shallockh02** [comment]
Thanks have been trying to curate it and the spreadsheet is so confusing

**Comment by lwaldron** [comment]
Note to self to review this curation!

**Comment by lwaldron** [comment]
@shallockh02 what spreadsheet are you referring to?

**Comment by shallockh02** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6626698/
was told that I am to curate this instead of text

**Comment by atrayees** [comment]
Curated all the experiments and signatures dealing with relative abundances with respect to smoking status, race, age, education level and sex.

**Comment by cynthianwauzor-sudo** [comment]
Hi @SvetlanaUP, I would like to change the doi of this curation from https://doi.org/10.1016/j.annepidem.2019.03.006 to 10.1016/j.annepidem.2019.03.006 and the URI from https://pubmed.ncbi.nlm.nih.gov/31151886/ to https://doi.org/10.1016/j.annepidem.2019.03.006.

**Comment by cynthianwauzor-sudo** [comment]
Done @SvetlanaUP
