### ISSUE TITLE
Characteristics of fecal gut microbiota in patients with colorectal cancer at different stages and different sites

### ISSUE THREAD

**Issue by atrayees** [waldronlab/BugSigDBcuration#64]
https://pubmed.ncbi.nlm.nih.gov/31611994/

**Comment by lightamadi-stack** [comment]
Good day @SvetlanaUP ,

I wanted to add this study **Characteristics of fecal gut microbiota in patients with colorectal cancer at different stages and different sites** to the **CRC google worksheet**. I checked GitHub issues and found that this is the only issue previously opened for it was later closed because the study already exists in BugSigDB. After confirming on BugSigDB, I see that it has indeed been curated and reviewed (https://bugsigdb.org/31611994), but there is no corresponding GitHub issue for it.

I just wanted to bring this to your attention, as I’m not sure what the appropriate next step should be in this case. Meanwhile, can I go ahead and add it to the CRC Google worksheet and mark it as curated?

Thank you.

**Comment by SvetlanaUP** [comment]
Just add it as curated in the CRC working table.

**Comment by lightamadi-stack** [comment]
Ok. Thank you @SvetlanaUP

**Comment by lightamadi-stack** [comment]
Good day @SvetlanaUP, kindly add the CRC label.

Thank you.
