### ISSUE TITLE
Cigarette smoke promotes colorectal cancer through modulation of gut microbiota and related metabolites

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBcuration#7]
Condition: Cigarette smoke
URL: https://gut.bmj.com/content/gutjnl/71/12/2439.full.pdf

**Comment by Busayo-ojo** [comment]
Hi, I would like to work on this article. Busayo Ojo

**Comment by Busayo-ojo** [comment]
Curated Article for review: https://bugsigdb.org/Study_186

**Comment by mcarlsn** [comment]
Hi @Busayo-ojo great job curating this study. Please review our notes below - you may use them to revise your curation. & If you decide to update your curation then addition to these notes, please update the description of Signature 1 and 2 to “Differentially abundant bacteria in smoke-free and smoke-exposed mice intraperitoneally injected with carcinogen azoxymethane.” Also, please update the “Abundance in Group 1” field in both Signature 1 to “increased abundance in smoke-exposed group” and update Signature 2 to, “decreased abundance in smoke-exposed group” in order to make the language consistent. Let us know if you have any questions! 

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1 
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1 (not removing points for this but I would change Group 0 to match the language used in the paper, “smoke-free” and  Group 1 to be “smoke-exposed”. Also, the definition of Group 1 should be updated to match the language used in paper: “Mice exposed to cigarette smoke directly (4% of 2000 mL/ min airflow) 2 hours per day for 28 weeks.”) 
7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1 
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 0 (update sequencing details e.g., shotgun metagenomic sequencing or “WMS” was used as primary sequencing type). 
10. Identified correct statistical test (1 point): 0
11. Identified MHT correction (1 point): 1 
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 2
17. Abundance direction correctly selected (1 point): 1 
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 0 (incomplete list, see Figure 2C and add remaining items to the correct signature). 
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 2

Total (maximum 23 points): 18

**Comment by Busayo-ojo** [comment]
Thank you for the review, I'll take a look at the mentioned issues.

**Comment by mcarlsn** [comment]
Hi @Busayo-ojo thanks for messaging. I reviewed my notes and the article you're right - you deserve that point. Please see the updated total score and revisions (above). Let me know if you have any other questions or comments about the review! You did a great job

**Comment by Busayo-ojo** [comment]
Hi @mcarlsn I have updated all the corrections: 18, 10, 9. 
Thank you!
