### ISSUE TITLE
Meta-analysis reveals the vaginal microbiome is a better predictor of earlier than later preterm birth

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#77]
Meta-analysis reveals the vaginal microbiome is a better predictor of earlier than later preterm birth – Caizhi Huang et al. – BMC Biology 2023
DOI: 10.1186/s12915-023-01702-2
https://bmcbiol.biomedcentral.com/articles/10.1186/s12915-023-01702-2

**Comment by cmirzayi** [comment]
**NOTE TO CURATOR:** This is a specific time of systematic review (a study of studies) called a meta-analysis and is therefore a bit different from normal articles we curate. Please expect that:

- This may be a more challenging curation than others because of these differences
- The way results are presented may differ from examples of other curations
- Tasks like identifying the sample size, lab methods, etc. will be more difficult

If you do not have a working knowledge of meta-analysis, I advise choosing another paper to curate.

**Comment by Folakunmi21** [comment]
Afuape Esther

**Comment by cmirzayi** [comment]
Assigned.

**Comment by cmirzayi** [comment]
Unassigned. Please note if you want this paper that it will be particularly challenging since it's a meta-analysis which is a bit different from the typical observational studies we see.
