### ISSUE TITLE
Gut microbiota analyses of inflammatory bowel diseases from a representative Saudi population

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#78]
Gut microbiota analyses of inflammatory bowel diseases from a representative Saudi population – Raed M. Alsulaiman et al. – BMC Gastroenterology 2023
DOI: 10.1186/s12876-023-02904-2
https://bmcgastroenterol.biomedcentral.com/articles/10.1186/s12876-023-02904-2

**Comment by Omabekee** [comment]
Chioma Blessing Onyido.

I want to claim this article for curation @cmirzayi @lwaldron @SvetlanaUP

**Comment by cmirzayi** [comment]
Assigned.

**Comment by Omabekee** [comment]
Yes! Thank you Chloe.

**Comment by Omabekee** [comment]
Hi @cmirzayi, I finished my curation: https://bugsigdb.org/Study_777 . Waiting for your reviews.

**Comment by Omabekee** [comment]
Hi. @cmirzayi , I wanted to bring your attention to the annotated paper that we used for our mini-curation a few days ago, I had already finished curating the annotated paper before  I got to know that I was meant to use it to answer the survey instead. I sincerely apologize for that. Could it be deleted? The curation link is: https://bugsigdb.org/Study_775

**Comment by Omabekee** [comment]
Also, I would like to ask if I may look through and attempt to solve some taxonomic issues, pending when my second curation is reviewed :)

**Comment by cmirzayi** [comment]
@Omabekee Overall this was an excellent curation of a challenging paper. I did notice you are missing several taxa from each signature. I assume this was because you were unable to identify them in the NCBI taxonomy. Even if you were unable to, you should still add their names to the signature. They will show in red on the page but that's ok.

All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 1
Entered all relevant experiments and no irrelevant experiments (1 point): 1
Body site correctly identified (i.e. does not include multiple sites) (1 point): 1 
Condition entered according to contrast (correct EFO ontology) (1 point): 1
Contrast groups correctly identified (1 point): 1
Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
Antibiotic exclusion correctly identified (1 point): 1
Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2
Identified correct statistical test (1 point): 1
Identified MHT correction (1 point): 0 (p. adj. means MHT correction)
Correctly recorded matched on variables (1 point): 1
Entered correct number of statistical tests per experiment (1 point): 1
All diversity measures identified (1 point): 1
Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 1
All signature sources correctly identified (-1 for each error) (2 points): 2
Abundance direction correctly selected (1 point): 1
Members of signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 0 (Some taxa are missing from both experiments 1 and 2)
Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 2
Total (maximum 23 points): 21

**Comment by Omabekee** [comment]
Wow @cmirzayi Thank you for your email. I have taken note of the corrections and have added the missing names to the signatures like you've pointed out. I genuinely appreciate for your guidance. Now, I feel more confident to move on to my third curation!

**Comment by SvetlanaUP** [comment]
@Omabekee well done!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_777 reviewed. ✅
