### ISSUE TITLE
Cerebral small vessel disease burden is associated with decreased abundance of gut Barnesiella intestinihominis bacterium in the Framingham Heart Study

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#81]
Cerebral small vessel disease burden is associated with decreased abundance of gut Barnesiella intestinihominis bacterium in the Framingham Heart Study – Bernard Fongang – Scientific Reports
DOI: 10.1038/s41598-023-40872-5
https://www.nature.com/articles/s41598-023-40872-5

**Comment by Sinmisoluwa01** [comment]
Sinmisoluwa Adesanya

**Comment by cmirzayi** [comment]
Assigned.

**Comment by Sinmisoluwa01** [comment]
Hi team, I am done with curating this paper @cmirzayi @SvetlanaUP @lwaldron

**Comment by cmirzayi** [comment]
Marked as ready for review.

**Comment by Sinmisoluwa01** [comment]
Thank you, Chloe! @cmirzayi

**Comment by cmirzayi** [comment]
This is a good start to this curation but I think that tables S5 and S6 should also be curated since those results are there. I think you were confused about the statistical testing which is understandable as it is presented pretty poorly in the paper.

I would also put more information in the group names and definitions on what a lower burden/high burden specifically means.

Statistical test appears to be MaAsLin2.

There was no matching.

Observed = Richness and should be curated as unchanged for all experiments.


| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 0 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 0 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 0 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 0 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 1 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 2 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 18 |

**Comment by Peacesandy** [comment]
Reviewed

https://bugsigdb.org/Study_793
