### ISSUE TITLE
Lower respiratory tract microbiome composition and community interactions in smokers

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#85]
Lower respiratory tract microbiome composition and community interactions in smokers – Michael Campos et al. – Access Microbiology 2023
DOI: 10.1099/acmi.0.000497.v3
https://www.microbiologyresearch.org/content/journal/acmi/10.1099/acmi.0.000497.v3

**Comment by OdigiriGreat** [comment]
i want to claim this paper please

**Comment by cmirzayi** [comment]
Assigned.

**Comment by OdigiriGreat** [comment]
thank you

**Comment by OdigiriGreat** [comment]
I have completed my curation @cmirzayi

**Comment by OdigiriGreat** [comment]
i have completed my curation please help me review 
https://bugsigdb.org/Study_761   @cmirzayi @SvetlanaUP

**Comment by SvetlanaUP** [comment]
Marked as ready for review.

**Comment by OdigiriGreat** [comment]
Please @SvetlanaUP I made a mistake with the link. I added https://bugsigdb.org/Study_761 (a study I worked on) instead of https://bugsigdb.org/Study_797 which is my originally assigned paper. 


Please I'm sorry for any inconveniences this must have caused.

**Comment by cmirzayi** [comment]
This is a good curation but with one mistake that unfortunately will require some updates. Taxa should be curated at the correct taxonomic level. Every genus in this curation has a species with it. Those species should not be curated--only the genus. For instance: Streptococcus should just be curated as that and not as Streptococcus mitis.

Table 5 is the LEfSe results and can be curated. The LDA score threshold is for the LEfSe analysis, not the DESeq2 analysis.

There was no statistical testing between alpha diversity measures so they should not be recorded.


| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 0 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 1 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 0 |
|  | TOTAL | 23 | 17 |

**Comment by OdigiriGreat** [comment]
Thank you for taking your time to do this review @cmirzayi . i am very grateful. 
 Also please if you can take a look at the following i will be delighted maam 

_1. **"Every genus in this curation has a species with it"** : I am recording the genus and taking out the species right away ma'am._

_2. There was no **statistical testing** between alpha diversity measures so they should not be recorded.**_

I am abit confused about this.  the reason I recorded alpha diveristies was because of the statements (discussions done at the end of the paper during the peer review) below. 

_"_L210: Were any statistical tests used to look for significant differences in alpha diversity? It appears as though NS have a higher alpha diversity than the other groups but I would like to see this tested using a One-Way ANOVA or Kruskal-Wallis test (whichever is more appropriate).

Added the statistical tests you mentioned, using ANOVA. Changed:

Never smokers exhibited markedly higher average and diversity compared to FS and AS (Figs. 4A and 4B)

Never smokers exhibited markedly higher average richness (ANOVA (32) , p=1e-9) and diversity (ANOVA, p=0.00075) compared to FS and AS (Figs. 4A and 4B)"_

Another question was posed below too...
_"L211: In my opinion, Simpson's index better measures species evenness than diversity. Was any difference observed between the groups using Faith's Phylogenetic Diversity?"_

We computed Faith’s Phylogenetic Diversity index among the three groups, and also a higher phylogeneic diversity was observed for Never smokers. This is now our new Fig. 4D, and we added:_

It was as a result iof these statements that I recorded the alpha diversities the way i did. However, I just wanted to state my reasons so you can look at them ma. 

3. _**Table 5 is the LEfSe results and can be curated.**_
Please ma'am, will this be curated as a different experiment (NS vs AS & FS) using LEfse 
then adding the LDA score of 2.5 in this experiment. 

If I go this route, then I will record all the genus as increasing taxa for AS & FS (Group 1) since it states that...
_".......While our earlier compositional analysis provided feedback on differences between highly abundant 
taxa, LEfSe can be helpful for discovering **less abundant taxa** that tended to only occur in one of the three groups, and considers their taxonomic relationships. Interestingly, **only the NS group came away with any distinguishing taxa, including the genera** **Prevotella, Veillonella, Haemophilus, Mogibacterium, Eubacterium, Lautropia, Megasphaera and Methylobacterium**"_

5.**The LDA score threshold is for the LEfSe analysis, not the DESeq2 analysis**
I will take out the LDA score since it was not stated for DESeq and impute for LEfse experiment I will be creating

Please your feedback will help me a lot. Thank you for always being patient.

**Comment by OdigiriGreat** [comment]
@cmirzayi I have been able to effect all the changes I am sure about. I will effect corrections for the alpha diversity immediately after your response to the questions i have raised for clarification. 
again thank you for being patient always

**Comment by OdigiriGreat** [comment]
Good morning @cmirzayi @lwaldron I know it's been a really tough week for our mentors and I understand. However I just wanted to drop a reminder 😊 about the response I was waiting for. Thank you so much

**Comment by Peacesandy** [comment]
Reviewed
