### ISSUE TITLE
_Ascaris suum_ infection was associated with a worm-independent reduction in microbial diversity and altered metabolic potential in the porcine gut microbiome

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#89]
_Ascaris suum_ infection was associated with a worm-independent reduction in microbial diversity and altered metabolic potential in the porcine gut microbiome

https://www.sciencedirect.com/science/article/pii/S0020751919300074?casa_token=zTI42d_k7gAAAAAA:CdhNW8hJpkMRhKHhamjBx-PNHhZm1IcX4Idbrze4ab7QpJTcxcE6wvzDz85SIeR6ZZ_wHrdRyjb-

![image](https://github.com/waldronlab/BugSigDBcuration/assets/639942/ad2aed88-31f1-4b4f-aab4-a62abeea8c00)

**Comment by TharaEhizogie** [comment]
Thara Ehizogie

I would like to be assigned this project
Thank you

**Comment by cmirzayi** [comment]
Hi @TharaEhizogie. I'm not able to find your first curation. Have you submitted that yet? If so did you perhaps give a different github username? Thanks.

**Comment by TharaEhizogie** [comment]
Hello, Yes i gave a wrong name. i contributed as TharaaOmo not TharaEhizogie. Do i need to do it again?

**Comment by cmirzayi** [comment]
No that's fine. I just wanted to make sure you've done the first contribution before proceeding to the second contribution. Assigning you this article.

**Comment by BearGrabs** [comment]
Hello, Roderick Momin here. I would like to tackle this for my Second Contribution.

**Comment by BearGrabs** [comment]
@Omabekee Hello, re-comment as per request.

**Comment by BearGrabs** [comment]
I am unable to access the [supplementary materials](http://10.0.68.224/zwr6x3f4vy.2) provided in the article. Would someone kindly check if this it the case for them as well?

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_886 Ready for review.

**Comment by Omabekee** [comment]
This was a good attempt @BearGrabs. Here are some errors you made and their corrections. Please work with Scholastica to effect the corrections.
- Figure 1A and table 2 should not be combined because they’re different stat tests and diff experiments; one of them is from LEfSe the other is from Kruskal Wallis.
1A compared CC vs INC,
Table 2 compared WBH vs WBL

- There should be only 5 alpha diversity measures. I’m not sure where you saw Richness. 

- Experiment 2 group descriptions should be stated clearly for proper comprehension without reading the whole paper.

- All source descriptions should be re-written for proper comprehension.

- I wouldn’t curate Figures 2 and 3 because they’re relative abundance results and they did not indicate the significance (p value).

**CURATION RESULTS**

1.All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0.5
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 0.5
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 0
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 0
14. All diversity measures identified (1 point): 0.5
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
16. All signature sources correctly identified (-1 for each error) (2 points): 1
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (2 points): 0
19. Correct use of NCBI taxonomy (2 points): 2
Total = 16.5
@SvetlanaUP, grading of Study 886 complete. ✅ Review still in progress

**Comment by Omabekee** [comment]
@Scholarpat please I need your assistance here, can you work with @BearGrabs to complete this curation?

**Comment by Scholarpat** [comment]
I'll love to @Omabekee .
Thank you 😊

**Comment by Scholarpat** [comment]
Hello @Omabekee , please can you help with the supplementary file as I'm unable to access it. 🙏

Thank you.

**Comment by SvetlanaUP** [comment]
@Scholarpat @Omabekee we could not get the supplementary material. Roderick @BearGrabs even tried to email them (https://community-bioc.slack.com/archives/C04RATV9VCY/p1711029904115979) but no luck.

**Comment by Scholarpat** [comment]
Okay @SvetlanaUP , thank you.
I'll see what I can deduce from the main article.

**Comment by BearGrabs** [comment]
@Omabekee Changes made based on feedback (more to come), however I have some questions that I would like cleared up.

- MHT correction: My understanding is there is no MHT correction for this case study which I've inputted as, yet I received 0 marks on it. I would like to know where I went wrong and which part I overlooked in the study.
- I agree with Figure 3 not being curated as it is using Normalized Counts however I am confused as to why Figure 2 should not be? (I've removed data from it regardless) My understanding is that Figure 1A and Figure 1B are also using relative abundances for Statistical Analysis with a p-value of < 0.05, LDA>2 using LEfSe  and my understanding is that Figure 2 is implying to have done the same for its statistical analysis using LEfSe.

**Comment by Scholarpat** [comment]
Hello @Omabekee,

We have implemented some of the corrections you recommended. However, we require clarification on how to proceed with Table 2. I have tagged you in a post on the Slack channel regarding this matter. I posted on Slack so others can contribute and learn alongside us. We eagerly await your response.

[Link to Slack post: https://community-bioc.slack.com/archives/C04RATV9VCY/p1712751340538189]

Thank you.

**Comment by Omabekee** [comment]
@BearGrabs Figures 2 and 3 can't be curated because they’re relative abundance results and they did not indicate the significance (p value). There's a difference but we can't really tell from the image if the difference is significant. 

I've added the mark for MHT, I apologize for the oversight.

**Comment by BearGrabs** [comment]
@Omabekee Final changes made which is the addition of data from Table 2. 

Table 2 is comparing Uninfected Piglets to WBL and WBH in line with the title of the study/table. (In contrast to what you have stated as WBL vs WBH above). 

However, I have added the information as Experiment 3 (Uninfected vs WBL) and Experiment 4 (Uninfected vs WBH) after the thread in Slack.

Signatures of both Experiment 3 and 4 that has been added are identical. Should you wish to condense the information to one Experiment of either Uninfected vs Infected (in line with results/title of the paper) or Uninfected vs WBL+WBH combined (condensed version of the Slack thread) then delete Experiment 4 kindly and I will make the changes to the relevant descriptions to reflect so.

**Comment by SvetlanaUP** [comment]
Ready for 2n review @Omabekee

**Comment by Scholarpat** [comment]
Hello @Omabekee, the source description for the signatures has also been updated to be more descriptive. Thank you for your time and patience.

**Comment by Omabekee** [comment]
Thank you both!

**Comment by AleruDivine** [comment]
Good evening @SvetlanaUP @cmirzayi, this study was recently marked as incomplete by and I attempted to review and resolve it. 

Here are my observations:
1. To the best of my knowledge, the signatures from the figures and tables are curated accurately. I believe the reason for the duplicate signatures in experiments 3 and 4 is because of how the results in the table are presented. They may appear as duplicates, but that is how the results are reported in table 2. 
2. My only concern is the alpha diversity measures in experiment 4. From table 1, it appears that only Chao 1 was decreased in High worm burden ascaris suum infected piglets (WBH) compared to controls and the rest are unchanged because there is no indication for significance. 

@cmirzayi do you think these observations address the reason it was marked as incomplete, or is there something else I might have missed? These are the observations I have so far from the study. Thank you so much!

**Comment by SvetlanaUP** [comment]
@cmirzayi said we should leave the older studies the way they are, from study 1 to 100.

**Comment by AleruDivine** [comment]
Noted! @SvetlanaUP 
Thank you so much!
