### ISSUE TITLE
Evolution of the Gut Microbiome in HIV-Exposed Uninfected and Unexposed Infants during the First Year of Life

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBcuration#9]
Condition: HIV
URL: https://journals.asm.org/doi/pdf/10.1128/mbio.01229-22

**Comment by ObafemiBlessing** [comment]
I would like to work on this article. Obafemi Blessing

**Comment by cmirzayi** [comment]
Assigned!

**Comment by ftzohra22** [comment]
@ObafemiBlessing if you haven'y already please make sure to create a BugSigDB account (https://bugsigdb.org/Special:RequestAccount) and follow the website prompts to complete the curation. Thank you!

**Comment by ObafemiBlessing** [comment]
Thank you

**Comment by ObafemiBlessing** [comment]
Please I need review on this, https://bugsigdb.org/Study_721. Thank you in anticipation

**Comment by ObafemiBlessing** [comment]
Thank you for the review, I'll go through it and get back to you

**Comment by ObafemiBlessing** [comment]
2. I have changed the study design to Prospective cohort.
4. I have added the body site to the one missing, I think I mistakenly cancelled it due to continuous edits.
15.  I initially left it as unchanged but the author stated "....changes over time showed that
richness increased significantly from 6 to 28 weeks" so I changed it to increased.
11. ![Screenshot_20230314-192054](https://user-images.githubusercontent.com/105362488/228492131-6f9555db-6259-4e42-ae00-39d66fae4ac0.png)
This is stated the MHT is yes when the p value  is stated as False discovery rate and this was stated in "...false-discovery-rate (FDR)-adjusted level of 0.05."

I am working on the other reviews

**Comment by ObafemiBlessing** [comment]
Please can shed a little light on what matched on factors are? I get a bit confused.
I have also made the  corrections you mentioned.
I'll be awaiting your reply

**Comment by cmirzayi** [comment]
@ObafemiBlessing If they say somewhere in the results or methods "We matched on..." It will often be a sentence like "We matched on age, sex, and income" or "Differential abundance analysis of age-matched cases and controls was conducted."

You can often ctrl+F and look for "matched on" or "matched" or "match."

**Comment by ObafemiBlessing** [comment]
Thank you Chloe

**Comment by mcarlsn** [comment]
Thank you for making those corrections, @ObafemiBlessing, and for your clarification related to matching @cmirzayi. FYI @ObafemiBlessing thanks for your response to MHT = Yes, please see the update in my review.

**Comment by ObafemiBlessing** [comment]
Okay, thank you.

**Comment by atrayees** [comment]
Reviewed.
